### ISSUE TITLE
Linux wheels

### ISSUE THREAD

**Issue by c-martinez** [skvark/opencv-python#1]
I saw there is already a ubuntu wheel, but came across this, and thought it might be useful:

https://github.com/pypa/manylinux

**Comment by skvark** [comment]
Looks interesting. I will definetely at least test if I can get the manylinux builds working (would be great for other than Ubuntu users).

The current builds for Windows and Ubuntu are now passing, but I haven't pushed the results yet to PyPI (setup.py is incomplete and I have to do some cleaning). Next phase is to get OS X builds working in Travis, and after that I will propably test the manylinux thing.
