### ISSUE TITLE
Is there any way to give the path of libGL.so.1 file manually

### ISSUE THREAD

**Issue by AmirHJabari** [skvark/opencv-python#1019]
### Expected behaviour
when importing mediapipe package which uses opencv_contrib_python==4.9.0.80 gives this error:
`libGL.so.1: cannot open shared object file: No such file or directory`

### Steps to reproduce

- operating system linux
- architecture x86_64
- opencv_contrib_python==4.9.0.80

Now I have a question is there any option to give it the path of this file or any other files like this `/lib64/libc.so.6` or `libGLX.so.0` manually for example in an environment variable? Or can you share a solution to fix this in another way?

I'm running this on aws lambda function by the way.

**Comment by asmorkalov** [comment]
See LD_LIBRARY_PATH environment variable. OpenCV package just follows manylinux2014 convention and relies on system level libs.
