### ISSUE TITLE
Is opencv-python v3.4.18.66 planned for the WebP update?

### ISSUE THREAD

**Issue by smokhov** [skvark/opencv-python#1026]
Similarly to https://github.com/opencv/opencv-python/releases/tag/78, is v3.4.18.*66* planned to update WebP?
Thank you.

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version **v3** of ``opencv-python``

**Comment by asmorkalov** [comment]
No

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv/wiki/Branches#eol-branches
