### ISSUE TITLE
How to view/modify the source code of Python OpenCV functions?

### ISSUE THREAD

**Issue by DoongLi** [skvark/opencv-python#1028]
I want to modify the code of a specific function in the Python version of OpenCV, such as findHomography().

But I don't know how to proceed. When I click on findHomography(), I only see the header file, not the source code.
![2024-09-11_23-12](https://github.com/user-attachments/assets/5fd57425-7895-44f6-ba1d-61872e88d87a)

**Comment by skvark** [comment]
The OpenCV code is written in C++ in another repository: https://github.com/opencv/opencv
