### ISSUE TITLE
Black Sceern comes when running opencv simple program

### ISSUE THREAD

**Issue by atmecskrishna** [skvark/opencv-python#104]
### Expected behaviour

Live feed should come

### Actual behaviour

black sceen appears when running the program

### Steps to reproduce

- 
import numpy as np
import cv2

cap = cv2.VideoCapture(0)

while(True):
     Capture frame-by-frame
    ret, frame = cap.read()

     Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

     Display the resulting frame
    cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

- windows 10
- 64bit
- opencv-python 3.4.1

**Comment by skvark** [comment]
Probably not related to this repo. You could try `cv2.VideoCapture(-1)` or `cv2.VideoCapture(1)`. Common usage questions belong in here: http://answers.opencv.org/questions/

**Comment by atmecskrishna** [comment]
I tried those options but didn't work. apart from these, I tried running my program from the terminal there, it is working successfully able to capture the image or video from the frame but when running using spyder there its is giving black screen instead of a video frame. Might be a problem is with anaconda or spyder.
