### ISSUE TITLE
has no ‘cv2.partition'

### ISSUE THREAD

**Issue by GuanRainy** [skvark/opencv-python#105]
When I use ’cv2.partition‘ this function, I get follow:
AttributeError: module 'cv2.cv2' has no attribute 'partition'

- operating system win7
- architecture ( x86)
- opencv-python 3.4.1

**Comment by skvark** [comment]
Please open an issue to the OpenCV repository. According to docs that function has not been exposed to Python: https://docs.opencv.org/3.4.1/d5/d38/group__core__cluster.html#ga2037c989e69b499c1aa271419f3a9b34

**Comment by GuanRainy** [comment]
Thank you@skvark, your answer is always very timely
