### ISSUE TITLE
Add support for Python 3.7

### ISSUE THREAD

**Issue by b4stien** [skvark/opencv-python#106]
Hi there, we've noticed trying to upgrade our Python version to 3.7 that there is no way to install `opencv-python` with it. Would you consider adding it to the build matrice? Would you like a PR for that?

Thanks for the great work 👌

**Comment by skvark** [comment]
Yes, I will definetely add support for 3.7. However, there are a few things which need to be checked or updated before it is possible:

- [ ] Python 3.7 wheel release of Numpy is needed. Not yet available: https://pypi.org/project/numpy/ Also, as there won't be old numpy releases available for 3.7 this logic needs to be changed: https://github.com/skvark/opencv-python/blob/449366dd9b0659f5877d9ced0a1a70882d4d8368/setup.py#L25
- [ ] Check manylinux image support for the latest 3.7 release (not rc/alpha/beta release).
- [ ] Check that Travis / multibuild has support for 3.7 (macOS related). Update multibuild if needed.
- [ ] Python 3.7 on Appveyor. Not yet available. https://www.appveyor.com/docs/build-environment/#python

I can make the changes but the timetable for a new ``opencv-python`` depends mostly on the issues listed above (if there are no other surprises).

**Comment by yonip** [comment]
Just a few notes:
 - Numpy (1.14.5) has been released for Python 3.7 (on 6/29)
 - While Travis does not currently publicly show Python 3.7 as supported [some people have found workarounds](https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-401846610), if you want to use it for now.
 - multibuild claims to have Python 3.7 support for Manylinux1 and macOS in its [readme on the devel branch](https://github.com/matthew-brett/multibuild/blob/devel/README.rst) (assuming that is the multibuild you were referring to).

**Comment by skvark** [comment]
Thanks. Numpy's 3.7 wheels were released a bit after I wrote that message. Travis doesn't need to support 3.7 on Linux, the builds run in manylinux Docker containers which will have support for 3.7 after I rebuild them. macOS is ok if multibuild README says so.

I'll make the required changes after Appeyor has added Python 3.7.

**Comment by rose-maria** [comment]
On running : **python setup.py install**

I get :
```
Usage:
  H:\PYTHON\python.exe -m pip list [options]

no such option: --format
Traceback (most recent call last):
  File "setup.py", line 370, in <module>
    main()
  File "setup.py", line 25, in main
    numpy_version = get_or_install("numpy", "1.11.3" if sys.version_info[:2] >=
(3, 6) else "1.11.1")
  File "setup.py", line 352, in get_or_install
    subprocess.check_output([sys.executable, "-m", "pip", "list", "--format", "j
son"]).decode('ascii'))  # valid names & versions are ASCII as per PEP 440
  File "H:\PYTHON\lib\subprocess.py", line 618, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['H:\\PYTHON\\python.exe', '-m', 'pip',
'list', '--format', 'json']' returned non-zero exit status 2
```

**Comment by yonip** [comment]
Update/bump: Appveyor now includes Python 3.7.0

@rose-maria I don't think this is the place for your own bug report (you might want to make a separate issue for that), but I could not reproduce that error. 

Does `python -m pip list --format json` also not work?

**Comment by skvark** [comment]
@yonip Thanks, I'll add support for 3.7 during this week, probably tomorrow.

@rose-maria As suggested above, open a new issue if you think that the error is related to this repository (note: building this package locally has not been tested but it might work on Windows).

**Comment by skvark** [comment]
Windows and Linux builds work fine but there's compiler compatibility issue on macOS due to upgrade to OpenCV 3.4.2:

```
/Users/travis/build/[secure]/opencv-python/opencv/3rdparty/protobuf/src/google/protobuf/arena_impl.h:182:10: error: thread-local storage is not supported for the current target

  static GOOGLE_THREAD_LOCAL ThreadCache thread_cache_;
```

Based on googling Xcode 8 should have support for thread-local storage but unfortunately the error persist with Xcode 8 and Xcode 9 environments in Travis. This is something which needs to be solved before I can make a new release.

**Comment by scivision** [comment]
Thanks for your continued excellent work on this. For those wanting to see the Xcode errors, here are the [opencv-python Travis-CI build logs](https://travis-ci.org/skvark/opencv-python/builds)

**Comment by toplinuxsir** [comment]
@skvark  
Any plan for  python 3.7 support ?  Thanks.

**Comment by skvark** [comment]
Good news: after multiple failed builds with different parameters and with awesome help from @yonip the macOS builds are now working. After the current builds are done, I'll release a new version. It will be available on PyPI at the latest on monday.

**Comment by skvark** [comment]
Release builds are now running and new packages will available during the next 24 hours.

**Comment by kvalev** [comment]
I am having some issues fetching the latest version when using Python3.7 - `No matching distribution found for opencv-python`,

I can reproduce it with the following Dockerfile:
```
FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && \
    apt install -y python3.7 python3-pip
# set python3.7 as default for pip3
RUN ln -s -f /usr/bin/python3.7 /usr/bin/python3
RUN pip3 install opencv-python
```

Looking at the [wheel files](https://pypi.org/project/opencv-python/#files), it seems that the x86_64 wheel for py37 is missing.

**Comment by skvark** [comment]
Looks like I have made some mistakes in the build matrix... only i686 entries are there for Linux :/ I'll have to make a new release. It will take couple of days because I'm simply running out of hours.

It would help if someone could add the entries to the build matrix and submit a PR. I'll then make the release.

**Comment by NotSoSuper** [comment]
Hey, are the x86_64 PyPI wheels going to be up soon?
Just making sure they aren't forgotten 😃

**Comment by skvark** [comment]
Just tagged a new version, they will be slowly appearing to PyPI. Thanks for the patience.

**Comment by scivision** [comment]
The Linux x86_64 wheels for Python 3.7 are now of PyPi
https://pypi.org/project/opencv-python/#files
