### ISSUE TITLE
OpenCV 3.4.2 has been released

### ISSUE THREAD

**Issue by fabito** [skvark/opencv-python#107]
https://github.com/opencv/opencv/releases/tag/3.4.2

**Comment by skvark** [comment]
Submodules have been already updated. There were other blocking issues caused by that update (https://github.com/skvark/opencv-python/issues/106#issuecomment-405104449), new release matching 3.4.2 will be available during the next few days.

**Comment by radomsak** [comment]
Thanks a lot!

**Comment by skvark** [comment]
Release builds are now running and new packages will be available during the next 24 hours.
