### ISSUE TITLE
setting parameters of openCV tracking API in python

### ISSUE THREAD

**Issue by Borda** [skvark/opencv-python#109]
I'm trying to use openCV tracking API in Python for object tracking. I tried the code in this [link](https://www.learnopencv.com/object-tracking-using-opencv-cpp-python/) and don't have any problem running the code. But, looking at the openCV documentation [here](http://docs.opencv.org/trunk/d9/df8/group__tracking.html), I realized there are parameters for each of the tracking algorithms. How can I set these parameters in python? 
Note, this question was asked on [StackOverflow](https://stackoverflow.com/questions/45677651)

**Comment by skvark** [comment]
This is a issue tracker, not a support forum. StackOverflow is the correct place for this kind of questions (or http://answers.opencv.org/questions/), no need to duplicate the same question here. If there's a bug related to OpenCV python bindings, report it to the upstream OpenCV repository https://github.com/opencv/opencv/issues.

**Comment by Borda** [comment]
So you say that this repo is not OpenCV - python binding? Then the name is confusing...

**Comment by skvark** [comment]
There's no OpenCV source code in this repo. This repository simply generates pre-built packages with OpenCV binding generators (https://docs.opencv.org/ref/master/da/d49/tutorial_py_bindings_basics.html).

The only Python code which ships with this package is in this file: https://github.com/skvark/opencv-python/blob/master/cv2/__init__.py

**Comment by Borda** [comment]
well, I was using this and install it throw pip so it was natural for me ask first here...
