### ISSUE TITLE
Structured Light "unwrapPhaseMap"

### ISSUE THREAD

**Issue by brook-seaton** [skvark/opencv-python#112]
### Expected behaviour
I've tried this on my Mac and Windows and I just get a crash.  The attached file contains the python code to produce the crash (it prints "before", but not "after"):
[sinusoidal.txt](https://github.com/skvark/opencv-python/files/2238465/sinusoidal.txt)

I don't know how python modules are created,  but I'd guess it's a problem with the  phase_unwrapping module and how it doesn't have a "create" function, and is instead added as a "structured_light_PhaseUnwrapping" module.

### Actual behaviour

On the Mac it prints("before") and crashes with "Segmentation fault: 11'
On Windows it prints("before") and then crashes 

### Steps to reproduce
1) download [sinusoidal.txt](https://github.com/skvark/opencv-python/files/2238465/sinusoidal.txt)
2) convert it from.txt to .py
3) in the command line call "python sinusoidal.py"

**Comment by skvark** [comment]
This sounds like a bug but I'm not sure because I don't know how the Structured Light module should be used. You should probably ask this question at http://answers.opencv.org/questions/.

If it turns out that there's a bug, you can report it to the OpenCV issue tracker: https://github.com/opencv/opencv/issues

This repository is simply a collection of continuous integration scripts which generate precompiled Python packages using OpenCV's binding generators (https://docs.opencv.org/master/da/d49/tutorial_py_bindings_basics.html).

**Comment by brook-seaton** [comment]
I don't mind the closing of the issue, I'm probably the only person trying to use this function.  I'll just have to use a language other than Python.

here's the code from the tutorial at https://docs.opencv.org/3.4.1/d0/de8/tutorial_capture_sinusoidal_pattern.html:
'''
                sinus->computePhaseMap(captures, wrappedPhaseMap, shadowMask);
                if( camSize.height == -1 )
                {
                    camSize.height = img[i].rows;
                    camSize.width = img[i].cols;
                    paramsUnwrapping.height = camSize.height;
                    paramsUnwrapping.width = camSize.width;
                    phaseUnwrapping =
                    phase_unwrapping::HistogramPhaseUnwrapping::create(paramsUnwrapping);
                }
                sinus->unwrapPhaseMap(wrappedPhaseMap, unwrappedPhaseMap, camSize, shadowMask);
'''

here's my code, which is just trying to duplicate the tutorial:
'''
wrapped_phase_map, shadow_mask = sinus.computePhaseMap(captures)
cam_size = (img[0].shape[0], img[0].shape[1])
print("before")
unwrapped_phase_map = sinus.unwrapPhaseMap(wrapped_phase_map, cam_size, shadow_mask)
print("after")
'''
