### ISSUE TITLE
haveOpenCL return False

### ISSUE THREAD

**Issue by PinkFloyded** [skvark/opencv-python#113]
### Expected behaviour
Should return `True` if the the prebuilt binaries are compiled with OpenCL support. I've seen many [examples](https://www.learnopencv.com/opencv-transparent-api/) where it just works out of the box. So my assumption is that the binaries are built with OpenCL support. So why might it not be working for me?

Also it works from C++ for OpenCV installed from source. So my computer has OpenCV runtime installed:

> [ INFO:0] Initialize OpenCL runtime...

### Steps to reproduce

- example code: `cv2.ocl.haveOpenCL()`
- operating system: `MacOS High Sierra 10.13`
- architecture (e.g. x86):`x86`
- opencv-python version: `3.4.2`

**Comment by skvark** [comment]
Based on CMake output in the build logs macOS builds have OpenCL support. Could you post the output of ``cv2.getBuildInformation()`` here? Unfortunately I do not own macOS devices but I'll try to do my best to debug the issue.

**Comment by VeneetReddyK** [comment]
You're right.

Turns out I've been using the cv2 from anaconda. There I get:

> Use Cuda:                    NO
> Use OpenCL:                  NO

When using cv2 from `opencv-python` I get:

>   OpenCL:                        YES (no extra features)
>     Include path:                NO
>     Link libraries:              -framework OpenCL

Sorry for opening such a silly issue.

**Comment by PinkFloyded** [comment]
You're right.

Turns out I've been using the cv2 from anaconda. There I get:

> Use Cuda:                    NO
> Use OpenCL:                  NO

When using cv2 from `opencv-python` I get:

>   OpenCL:                        YES (no extra features)
>     Include path:                NO
>     Link libraries:              -framework OpenCL

Sorry for opening such a silly issue.

**Comment by skvark** [comment]
No problem :)
