### ISSUE TITLE
DLL load failed on 3.4.2.1.16 and 3.4.2.17 versions (windows 7 x64)

### ISSUE THREAD

**Issue by eggnot** [skvark/opencv-python#114]
after:
`import cv2`

error:
`ImportError: DLL load failed: The specified module could not be found.`

but if:
`pip install opencv-python==3.4.1.15`

everything works just fine.

--
tested on
windows 7 x64, all updates, vs_redist++ 15, 17
python 3.6.5, 3.6.6, both x32 and x64 - error and behavior the same
opencv 3.4.1.15 and below seems working(tested on 3.4.0.12)

**Comment by skvark** [comment]
I don't have Windows 7 available right now but on Windows 10 everything seems to be working properly. You can check the `cv2.cp36-win_amd64.pyd` file with http://www.dependencywalker.com/ to see which dependency is missing (note: there will be many false positives in Dependecy Walker output).

**Comment by eggnot** [comment]
![2018-08-08 22-55-34](https://user-images.githubusercontent.com/5466961/43848950-57a76364-9b5e-11e8-9cf7-15a5dfff0bca.PNG)

do you need text logs?

**Comment by skvark** [comment]
There is something odd going on with Windows. I don't know why the earlier versions work fine... maybe some new dependency was introduced in the new versions of OpenCV. However, as this issue suggests, API-MS-WIN-DOWNLEVEL-SHLWAPI-L1-1-0.DLL is probably missing: https://github.com/skvark/opencv-python/issues/116

Downloading arbitrary DLL files from the internet is not recommended. Instead, you should at least run ``sfc /scannow`` as an Administrator to see if there are issues with the system files (https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system). If that doesn't help, we need to figure out some other solution to this problem.

**Comment by hglee** [comment]
Install platform update (KB2670838) for API-MS-WIN-DOWNLEVEL-SHLWAPI-L1-1-0.DLL

See opencv issue [#12010](https://github.com/opencv/opencv/issues/12010).

**Comment by skvark** [comment]
Thank you. I guess this issue can be closed.

**Comment by azhaoaigaga** [comment]
@eggnot Is this problem solved? I encountered the same problem in Windows server 2008 r2, but I had a lot fewer DLL and tried many methods. How did you solve it?

**Comment by eggnot** [comment]
> @eggnot Is this problem solved? I encountered the same problem in Windows server 2008 r2, but I had a lot fewer DLL and tried many methods. How did you solve it?

was on old machine, can't check. i used depwalker to trace missing dll. can't remember exactly which  are, sorry.
