### ISSUE TITLE
Words from devanagari script are not working

### ISSUE THREAD

**Issue by pankajsinghal** [skvark/opencv-python#118]
### Expected behaviour

I'm trying to make an image of text with the following devnagri content: 

`कामकाजी महिलाओं के लिए देश में दिल्ली असुरक्षित, सिक्किम सबसे बेहतर: रिपोर्ट`

### Actual behaviour

The text `कामकाजी महिलाओं के लिए देश में दिल्ली असुरक्षित, सिक्किम सबसे बेहतर: रिपोर्ट` produces the following incorrect output
<img width="636" alt="screen shot 2018-08-12 at 11 43 35 pm" src="https://user-images.githubusercontent.com/7523102/44005000-96851044-9e89-11e8-95f1-2ba08770a99c.png">

Was trying to produce a solution for https://stackoverflow.com/questions/39630916/how-can-i-print-hindi-sentencesunicode-on-image-in-python

### Steps to reproduce

- example code
```
import numpy as np
import cv2
from PIL import ImageFont, ImageDraw, Image

from PIL import Image

image = np.zeros((1512,1512,3), np.uint8)

b,g,r,a = 0,255,0,0
fontpath = "/Library/Fonts/Arial Unicode.ttf"
font = ImageFont.truetype(fontpath, 32)
img_pil = Image.fromarray(image)
draw = ImageDraw.Draw(img_pil)
draw.text((50, 100),  "कामकाजी महिलाओं के लिए देश में दिल्ली असुरक्षित, सिक्किम सबसे बेहतर: रिपोर्ट", font = font, fill = (b, g, r, a))
img = np.array(img_pil)

## Display
# cv2.imshow("res", img);cv2.waitKey();cv2.destroyAllWindows()
cv2.imwrite("res.png", img)
```

- operating system
macOS High Sierra - 10.13.6

- architecture (e.g. x86)
64 bit
- opencv-python version
```
$ pip freeze | grep -i open
opencv-python==3.4.2.17
```

**Comment by skvark** [comment]
I'm sorry, how is this is related to this repository or OpenCV? To me it seems that you're using PIL to draw text to an image and just trying to display/write the image with OpenCV. Please report the bug to PIL repository.
