### ISSUE TITLE
Error with computing shape context distance

### ISSUE THREAD

**Issue by hoskhosh** [skvark/opencv-python#119]
not sure if this is a problem with opencv-python or opencv in general

```
import cv2
import numpy as np


im1 = cv2.imread("first.bmp", 0)
im2 = cv2.imread("second.bmp", 0)

_, im1 = cv2.threshold(im1, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
_, im2 = cv2.threshold(im2, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

_, cntr1, _ = cv2.findContours(im1, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
_, cntr2, _ = cv2.findContours(im2, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

scde = cv2.createShapeContextDistanceExtractor()
distance = scde.computeDistance(cntr1, cntr2)
print(distance)
```
this works fine for images that are fairly similar. but sometimes it gives the following error:

> cv2.error: OpenCV(3.4.2) C:\projects\opencv-python\opencv\modules\core\src\matmul.cpp:1218: error: (-215:Assertion failed) type == (((6) & ((1 << 3) - 1)) + (((2)-1) << 3)) in function 'cv::gemmImpl'

for example for ![first](https://user-images.githubusercontent.com/40786051/44305416-eb675700-a38b-11e8-878e-823e1879f55e.png) and ![second](https://user-images.githubusercontent.com/40786051/44305421-04700800-a38c-11e8-8709-d314e8dbc6a7.png) which are the same image, only flipped the error above occurs.

- windows 8.1
- x64
- opencv-python version: 3.4.2.17

**Comment by skvark** [comment]
The problem is in OpenCV. Open an issue to the OpenCV repo: https://github.com/opencv/opencv/issues
