### ISSUE TITLE
Enable build for Python 3.3, 3.4 / Windows

### ISSUE THREAD

**Issue by skvark** [skvark/opencv-python#12]
The build time is fast enough on Appveyor so support for py33 and py34 can be added. Also the Appveyor build scripts could be refactored.

**Comment by glitchassassin** [comment]
Forking this to try to implement. Looks like `numpy` doesn't want to play nicely with `pip` in Python33 or Python34. Luckily it sounds like AppVeyor can [include `numpy` through `conda` instead](http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/).

I'll try refactoring the build script and see what I can come up with.

**Comment by skvark** [comment]
Thanks. It seems that numpy has wheels for 3.4 but not for 3.3 (https://pypi.python.org/pypi/numpy/1.11.1).

**Comment by glitchassassin** [comment]
Added pull request, #19.
