### ISSUE TITLE
Webcam light still on after cam.release()

### ISSUE THREAD

**Issue by gabycperezdias** [skvark/opencv-python#120]
### Expected behaviour

When releasing webcam, not only the webcam should be released but also the webcam light indicator should be turned off.

### Actual behaviour

The webcam light keeps on even though the webcam is, in fact, released.

I am doing:

    webcam = cv2.VideoCapture(0)
    webcam.release()

After the release command, if I try to read the cam I get: (False, None) but the webcam itself is still <VideoCapture 0EE62DC0>. I don't know if this is the issue, but the light keeps on until I kill all python script or python terminal responsible to turn it on.

I am on a Windows 10, python 3.5, opencv 4.0.1. According to comments on my stackoverflow question (https://stackoverflow.com/questions/51974632/webcam-light-still-on-after-cam-release) other version also shows the issue (python 3.6 and opencv 3.4.2)

It seems that it was introduced in an earlier version because version 3.4.0.14 works fine.

**Comment by skvark** [comment]
Please report OpenCV bugs to the official OpenCV repository: https://github.com/opencv/opencv/issues

This repository is just an unofficial wrapper which generates python bindings automatically from OpenCV sources.

**Comment by gabycperezdias** [comment]
If anyone has the same issue... the issue was open in the official repo (https://github.com/opencv/opencv/issues/12301)

**Comment by gabycperezdias** [comment]
@skvark Hi, very sorry to disturb again... but I am more of an user. 
I've opened the issue in the oficial repo, but it was suggested for me to "Attach logs with OPENCV_VIDEOIO_DEBUG=1 environment variable.
Also try OPENCV_VIDEOIO_PRIORITY_MSMF=0 to disable MSMF." since the opencv-python is a wrapper, how can I do this? Could you help me? 

Thanks in advance...

**Comment by skvark** [comment]
I believe that you can just set those environment variables in the command line before you run your Python script. For example:

```
setx OPENCV_VIDEOIO_DEBUG 1
python yourscript.py
```
