### ISSUE TITLE
imread() didn't close the image file properly sometime

### ISSUE THREAD

**Issue by akmalhakimi1991** [skvark/opencv-python#122]
I have a program where I read an image file (e.g. from a webcam), crop a face (if any) and save the cropped face into a new image file. The program will then delete the original image file. Here's the code: 
  
    import cv2
    import os
    import datetime

    cam = cv2.VideoCapture(0)
    while True:
        imagenames = []
        imagename = 'face'+str(datetime.datetime.now().strftime('%Y%m%d_%H%M%S'))+'.jpg'
        ret, frame = cam.read()
        cv2.imwrite(imagename, frame)
        
        img = cv2.imread(imagename)
        face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(gray, 1.3, 5)
        
        n = 0
        for (x,y,w,h) in faces:
            img = cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
            crop_img = img[y:y+h, x:x+w]

            try:
                imagenames.append(str(n)+'_'+imagename)
                cv2.imwrite("img"+str(n)+'_'+imagename,crop_img)
                n=n+1
            except Exception, e:
                print e
                pass

        os.remove(imagename)  
  
  
Problem is, sometime the image is not properly closed. This cause the program to throw this error:
`The process cannot access the file because it is being used by another process`  
  
opencv-contrib-python version: 3.4.2.17
OS: Windows 7
Python version: 2.7.15

**Comment by skvark** [comment]
Similar error report from official OpenCV repository: https://github.com/opencv/opencv/issues/10162

There might be a bug in OpenCV, but please report the bug to the official OpenCV repository.

As an additional note, try to avoid writing files to disk in a while loop. You already have the image in the ``frame`` variable, why not just use it directly? Disk I/O is slow and likely you can avoid that permission error altogether if you don't write the original image to the disk.
