### ISSUE TITLE
cap.get(cv2.CAP_PROP_POS_MSEC) return wrong result 

### ISSUE THREAD

**Issue by chenjiacun35** [skvark/opencv-python#123]
### Expected behaviour

the frame interval of video are difference，but the result of function `cap.get(cv2.CAP_PROP_POS_MSEC)`  have the same frame interval.

### Actual behaviour

the frame interval of video are difference，the result of function `cap.get(cv2.CAP_PROP_POS_MSEC)`  have the same frame interval.

### Steps to reproduce

- example code:
```
cap = cv2.VideoCapture(r'd:\tmp\test2.mp4')

while True:
    timestamp = cap.get(cv2.CAP_PROP_POS_MSEC)
    print 'time:%f;num:%f'% (timestamp,cap.get(cv2.CAP_PROP_POS_FRAMES))
    ret, frame = cap.read()
    if ret == True:
        pass
    else:
        break
```
- operating system: windows 7 x64
- architecture (e.g. x86)
- opencv-python version:3.4.2.17

**Comment by skvark** [comment]
Please report OpenCV bugs to the official upstream repository: https://github.com/opencv/opencv
