### ISSUE TITLE
VIDEOIO ERROR: V4L: can't open camera by index 0

### ISSUE THREAD

**Issue by chtsngn** [skvark/opencv-python#124]
Hello,

I'm triggering a Python file with PHP.

```php
$return = shell_exec("/usr/bin/python3.6 create.py 2>&1")
```
**Python File**

```python
import numpy as np
import cv2

cap = cv2.VideoCapture(0)

while(True):

    ret, frame = cap.read()

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```
Return this value

> VIDEOIO ERROR: V4L: can't open camera by index 0

What is the problem?

OS: Ubuntu 18.04 x64
Python: 3.6.6
OpenCV: 3.4.2

**Comment by skvark** [comment]
Try with ``cv2.VideoCapture(-1)``. Please ask this kind of questions at http://answers.opencv.org/questions/ in the future.

**Comment by chtsngn** [comment]
http://answers.opencv.org/question/199105/videoio-error-v4l-cant-open-camera-by-index-0/

**Comment by adarsh1927** [comment]
thanks for solving my problem
