### ISSUE TITLE
Suppress, hide or disable the error/warning messages 

### ISSUE THREAD

**Issue by Michael-Yee** [skvark/opencv-python#128]
I was wondering if there was a way to suppress, hide or disable the error or warning messages outputted to the screen? 

I think they come from FFMpeg and they either show up as follows:

CASE 1:
[mpeg2video @ 0x3430c00] Invalid frame dimensions 0x0.
[mpeg2video @ 0x3430c00] Invalid frame dimensions 0x0.
[mpeg2video @ 0x3430c00] Invalid frame dimensions 0x0.
[mpeg2video @ 0x3430c00] Invalid frame dimensions 0x0.
[mpeg2video @ 0x3430c00] Invalid frame dimensions 0x0.
[mpeg2video @ 0x3430c00] Invalid frame dimensions 0x0.
[mpeg2video @ 0x3430c00] Invalid frame dimensions 0x0.
[mpeg2video @ 0x3430c00] Invalid frame dimensions 0x0.
[mpeg2video @ 0x3430c00] Invalid frame dimensions 0x0.
[mpeg2video @ 0x3430c00] Invalid frame dimensions 0x0.

or 

CASE 2:
...
[h264 @ 0x29e5a40] co located POCs unavailable
[h264 @ 0x2a6c3c0] co located POCs unavailable
[h264 @ 0x29d7b80] reference picture missing during reorder
[h264 @ 0x29d7b80] Missing reference picture, default is 65656
[h264 @ 0x298da80] mmco: unref short failure
[h264 @ 0x298da80] number of reference frames (0+6) exceeds max (5; probably corrupt input), discarding one
[h264 @ 0x29dc700] reference picture missing during reorder
[h264 @ 0x29dc700] Missing reference picture, default is 65672
[h264 @ 0x2a27180] mmco: unref short failure
[h264 @ 0x2af7680] co located POCs unavailable
[h264 @ 0x29e5a40] mmco: unref short failure
[h264 @ 0x29e5a40] number of reference frames (0+6) exceeds max (5; probably corrupt input), discarding one
[h264 @ 0x2af9040] mmco: unref short failure

To my understanding CASE 1, is a known issue, as it is looking for a PES header.  There are only a few o these messages until it finds the header.

I do not understand CASE 2, I do not know what is happening, but it seems to read the frame in the end.  There are many of these messages and adds minutes to the processing time.

**Comment by skvark** [comment]
Yes, the messages come from FFmpeg. You could try setting the FFREPORT environment variable before running your script. I have no idea if this works but you can try:

``export FFREPORT=level=info``

Source: https://ffmpeg.org/ffmpeg.html#Generic-options

**Comment by Michael-Yee** [comment]
Thanks for the suggestion, but it does not suppress the messages.  I see comments about rebuilding FFMpeg and/or OpenCV, but was hoping for a easier answer.

**Comment by skvark** [comment]
Closing because this is not directly related to this repository. Most likely the only solution is to rebuild OpenCV and FFmpeg and disable all error reporting.
