### ISSUE TITLE
imread(*.tiff) is broken

### ISSUE THREAD

**Issue by fepeter** [skvark/opencv-python#130]
### Expected behaviour

cv2.imread('TIFFimage.tiff') should read the image to an array

### Actual behaviour

return is a none 

### Steps to reproduce

- example code

import cv2
a = cv2.imread('TIFFimage.tiff')
a

- operating system suse 
- architecture x64
- opencv-python 3.4.3.18 
- numpy 1.15.2
- installed by pip

the version opencv-python 3.4.3.17 works fine

**Comment by skvark** [comment]
Both versions of the pre-built wheels produced by this repository have been built with the same version of the TIFF library shipped along OpenCV (ver 42 - 4.0.9). 

If there's a bug, it's most likely in OpenCV and should be reported to the upstream repository which contains the actual OpenCV source code: https://github.com/opencv/opencv

**Comment by indepndnt** [comment]
Hey, just in case anyone else ends up here: I had this same problem and it is resolved in the version 3.4.5.20.

**Comment by skvark** [comment]
Yeah, there was some regression in OpenCV which has been now fixed: https://github.com/opencv/opencv/pull/12989
