### ISSUE TITLE
freezing GUI in Win10 64

### ISSUE THREAD

**Issue by mluerig** [skvark/opencv-python#153]
### Expected behaviour

call GUI, e.g. with imshow

### Actual behaviour

image shows, and I can close it, but then the kernel freezes. 

NO error msg

### Steps to reproduce

    img = cv2.imread(path)

    cv2.namedWindow('window' ,cv2.WINDOW_NORMAL)
    cv2.imshow('window',  img)
    cv2.waitKey(0)
    cv2.destroyAllWindows() 

happens in both `spyder` and command line 

Specs:

Windows 10 64
Python 3.7.1

C:\WINDOWS\system32>activate p37

(p37) C:\WINDOWS\system32>pip freeze

alabaster==0.7.12
asn1crypto==0.24.0
astroid==2.0.3
attrs==18.2.0
Babel==2.6.0
backcall==0.1.0
bleach==3.0.2
certifi==2018.10.15
cffi==1.11.5
chardet==3.0.4
cloudpickle==0.6.1
colorama==0.4.0
cryptography==2.3
cryptography-vectors==2.3.1
cycler==0.10.0
decorator==4.3.0
docutils==0.14
entrypoints==0.2.3
ExifRead==2.1.2
idna==2.7
imagesize==1.1.0
ipykernel==5.1.0
ipython==7.1.1
ipython-genutils==0.2.0
isort==4.3.4
jedi==0.13.1
Jinja2==2.10
jsonschema==3.0.0a3
jupyter-client==5.2.3
jupyter-core==4.4.0
keyring==16.1.0
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
MarkupSafe==1.1.0
matplotlib==2.2.3
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.6
mkl-random==1.0.1
nbconvert==5.3.1
nbformat==4.4.0
numpy==1.15.4
numpydoc==0.8.0
opencv-contrib-python==3.4.3.18
packaging==18.0
pandas==0.23.4
pandocfilters==1.4.2
parso==0.3.1
pickleshare==0.7.5
prompt-toolkit==2.0.7
psutil==5.4.8
pycodestyle==2.4.0
pycparser==2.19
pyflakes==2.0.0
Pygments==2.2.0
pylint==2.1.1
pyOpenSSL==18.0.0
pyparsing==2.3.0
pyrsistent==0.14.7
PySocks==1.6.8
python-dateutil==2.7.5
pytz==2018.7
pywin32-ctypes==0.2.0
PyYAML==3.13
pyzmq==17.1.2
QtAwesome==0.5.3
qtconsole==4.4.3
QtPy==1.5.2
requests==2.20.1
rope==0.10.7
scipy==1.1.0
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.8.2
sphinxcontrib-websupport==1.1.0
spyder==3.3.2
spyder-kernels==0.2.6
testpath==0.4.2
tornado==5.1.1
trackpy==0.4.1
traitlets==4.3.2
urllib3==1.23
wcwidth==0.1.7
webencodings==0.5.1
win-inet-pton==1.0.1
wincertstore==0.2
wrapt==1.10.11

**Comment by mluerig** [comment]
as a sidenote: 3.4.4 from this repo (https://www.lfd.uci.edu/~gohlke/pythonlibs/#opencv) works

**Comment by skvark** [comment]
There is a bug in OpenCV and it has been fixed in 3.4.4 in the upstream: https://github.com/opencv/opencv/issues/13049

I cannot fix OpenCV bugs here, but I will release 3.4.4 builds during this week and after that 4.0.0. The releases have been delayed due to multiple issues with macOS builds.

**Comment by skvark** [comment]
The 3.4.4 builds are now in progress and should be available at PyPI during the next 24 hours.

**Comment by mluerig** [comment]
oh wow, thanks for the update
