### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Yajan** [skvark/opencv-python#154]
I have installed opencv using `pip install opencv-contrib-python` in **ActivePython 3.5.4** in ** Windows 10**. When I import cv2 module it is throwing error as 
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Yajana\Documents\Python\mechine_learning\env\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: The specified module could not be found.
`

1. I have Microsoft Visual C++ 2015 Redistributable Installed
2. I have tried with downloading `api-ms-win-downlevel-shlwapi-l1-1-0.dll` and placing it in system32 and SysWOW64

What else can be done to resolve the issue?

**Comment by skvark** [comment]
These packages support only official CPython implementation: https://www.python.org/

Please do not download arbitrary DLL files from the internet. They might contain malware.

First, install all Windows updates to your system. If that does not work, you can try to check the missing dependencies with Dependency Walker.

**Comment by skvark** [comment]
Could you try with https://github.com/lucasg/Dependencies. Its output is easier to read as it does not contain so many false positives.
