### ISSUE TITLE
OpenCV 4.0.0 has been released

### ISSUE THREAD

**Issue by zdenop** [skvark/opencv-python#156]
OpenCV 4.0.0 was releases 14 day ago: https://github.com/opencv/opencv/releases/tag/4.0.0
It there plan to release opencv-python 4.0.0?

**Comment by zdenop** [comment]
related to https://github.com/skvark/opencv-python/issues/137

**Comment by skvark** [comment]
Yes. I'll have to check first that it builds fine. However, the builds take tens of hours of time so I can't just release them without being able to monitor the build process closely. I might be able to do the release during this week.

**Comment by skvark** [comment]
Linux builds are failing (and macOS too, but that might be fixed when the builds are rebuilt a few times). I have to check what's going on on Linux.

**Comment by zdenop** [comment]
https://www.learnopencv.com/install-opencv-4-on-centos-7/ does not help?

**Comment by skvark** [comment]
Unfortunately basic compilation guides don't help in this case. The error is related to custom CentOS 5 i686 images and to some type error. However, macOS images and 64-bit Linux builds are fine.

**Comment by LaurentBerger** [comment]
How can we help you ? Can you post full error message ?

**Comment by skvark** [comment]
You can see the full error messages if you have a look the failed builds for example here: https://travis-ci.org/skvark/opencv-python/builds/470937189

First one:
```
In file included from /io/opencv/modules/videoio/src/cap_v4l.cpp:232:0:
/usr/include/linux/videodev2.h:1112:9: error: ‘__u64’ does not name a type
 typedef __u64 v4l2_std_id;
```
For some reason (maybe because of an ancient kernel) the type ``__u64`` is not recognized. I just bumped the OpenCV version to 4.0.1 to see if the error is`caused just by some bug in 4.0.0 or is it related to the build environment.

**Comment by skvark** [comment]
Builds are passing now. I will create a release tomorrow after the current CI jobs are done.

**Comment by skvark** [comment]
The builds are now in progress. Please note that it takes about 16 hours before all the packages are available to install from PyPI.
