### ISSUE TITLE
how to set cv2.VideoCapture connection timeout

### ISSUE THREAD

**Issue by beruhan** [skvark/opencv-python#157]
I used opencv-python to capture snapshot from hundreds of thousands rtsp urls,I used gevent coroutine to 
accelerate capturing snapshot,But It seemed no use. and I found there no way to set rtsp connection timeout argument,Can anyone help me or give some way to faster capturing snapshot from massive rtsp urls?

**Comment by skvark** [comment]
Please ask usage questions at http://answers.opencv.org/questions/.
