### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_cv2)

### ISSUE THREAD

**Issue by NarcissusInMirror** [skvark/opencv-python#159]
I'm running a code on deep learning on the server of our lab, which uses the opencv module, by running `python main.py` (contains `import cv2` statement), but always get the error `ImportError: dynamic module does not define module export function (PyInit_cv2)`.

I've tried to reinstall my anaconda and create new virtual environments, but all got the same result. This problem really confuses me a lot and I've googled for many related problems, none of them works. I think the problem is something related to the environment and has nothing to do with the code, because I got the same result by simply run `import cv2` in python prompt. The more confusing thing is that, even after I remove the opencv module, I also get the same problem, but not a `ModuleNotFoundError`.

I've tried several ways to install this package, includes `conda install opencv`, `pip install opencv-python`, `pip install opencv-python-headless`

 Does anyone can give me some advice? Thanks a lot!

**Comment by skvark** [comment]
First of all, ``conda install opencv`` does not install this package. It installs the conda package: https://github.com/conda-forge/opencv-feedstock

The error suggests that your environment is badly broken. My recommendation is to remove all OpenCV installations. This means also global installations obtained via some package manager or by manual compilation. I guess that there is some old ``cv2.so`` somewhere in the system (probably in the root of site-packages) which conflicts with all other installations. This conflicting shared library is probably also being copied to your virtual environments whenever you create one.

After cleaning the system you should run ``pip install opencv-python`` preferably in a new Python virtual environment.

**Comment by skvark** [comment]
Closing as this is not related to this package.

**Comment by NarcissusInMirror** [comment]
Sorry for replying you so late, but thank you very much for your help!
