### ISSUE TITLE
cv2.imshow() window appears to have trackbar displaying mouse x,y and RGB values

### ISSUE THREAD

**Issue by wb666greene** [skvark/opencv-python#163]
### Expected behaviour
Open a window and display the image without a trackbar.

### Actual behaviour
Window opens and image displays with trackbar on the bottom (only partially visible) showing the mouse x,y location and RGB values at that point, not completely legible as the trackbar seems clipped at the bottom.

### Steps to reproduce
Ubuntu 18.04
sudo -H pip3 install opencv-contrib-python (as part of Movidius SDK install)

pip3 -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

cap=cv2.VideoCapture("rtsp://admin:xyzzy@192.168.2.164:554/cam/realmonitorchannel=6&subtype=0")
ret, frame = cap.read()
cv2.imshow('RTSP VIDEO', frame)
waitkey(0)

- opencv-python version 3.4.5 (installed today) 

I have also observed this behavior with Windows, opencv-contrib-python installed a few months ago, I ignored it thinking it might be "normal" for Windows.

**Comment by skvark** [comment]
Maybe there has been some change in OpenCV which causes this. It's better to open an issue to the actual OpenCV repository https://github.com/opencv/opencv/issues. 

I cannot fix OpenCV bugs here, this repository just compiles and uploads binary packages to PyPI.

**Comment by wb666greene** [comment]
The solution, in case anyone else is inconvenienced by this issue, is you first have to create your window with these flags:

`# Removes status bar, and perhaps a toolbar if your default imshow() window  has one

cv2.namedWindow(WindowName', flags=cv2.WINDOW_GUI_NORMAL + cv2.WINDOW_AUTOSIZE) `

After doing this to create the window you can do your normal imshow() function and not have the statusbar -- sorry I was incorrect in calling it a trackbar.

The actual flags values may depend on the version of OpenCV  and some of the compile options.  I have verified it works on Python 3.6.7 and OpenCV 3.4.5 installed with pip opencv-python-contrib.
