### ISSUE TITLE
want to detect rectangle in a image using opencv-python?

### ISSUE THREAD

**Issue by ganeshsingamaneni** [skvark/opencv-python#166]
### Expected behaviour

want to detect rectangular shape line from image and save it as another image with text init
### Actual behaviour

Write here what went wrong.
if there is two rectangular shapes in a image i want the bigger one

**Comment by skvark** [comment]
This is not a help / QA forum. Ask your question at http://answers.opencv.org/questions/ or at https://stackoverflow.com/.
