### ISSUE TITLE
Architecture of CNNs

### ISSUE THREAD

**Issue by armmin009** [skvark/opencv-python#171]
I heard the convolution and pooling operations happens in hidden layers but I see the opposite in the picture below....So which one is correct?
![screen shot 2019-02-04 at 4 04 54 pm](https://user-images.githubusercontent.com/43352032/52209789-3a516c00-289a-11e9-8a7c-489ef5456c57.png)

**Comment by skvark** [comment]
This is a issue tracker, not a Q&A site. Please ask your question at http://answers.opencv.org/questions/ or at https://stackoverflow.com/. 

If you are reporting a bug, report it to the upstream repository at https://github.com/opencv/opencv.
