### ISSUE TITLE
Error: cv2.error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\highgui\src\window_w32.cpp:1230: error: (-215:Assertion failed) dst.data == (uchar*)dst_ptr in function 'cvShowImage'

### ISSUE THREAD

**Issue by BhautikDonga** [skvark/opencv-python#172]
### Expected behaviour

to show the image .

### Actual behaviour

give this error:
cv2.error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\highgui\src\window_w32.cpp:1230: error: (-215:Assertion failed) dst.data == (uchar*)dst_ptr in function 'cvShowImage'

### Steps to reproduce

- example code:

    import cv2
    import numpy as np

    cap = cv2.VideoCapture(0)
    while True:
        _, frame = cap.read()
        laplacian = cv2.Laplacian(frame, cv2.CV_64F)
        sobelx = cv2.Sobel(frame, cv2.CV_64F, 1, 0, ksize=5)
        sobely = cv2.Sobel(frame, cv2.CV_64F, 0, 1, ksize=5)
        cv2.imshow('Original', frame)
        cv2.imshow('Laplacian', laplacian)
        cv2.imshow('Sobelx', sobelx)
        cv2.imshow('Sobely', sobely)
        k = cv2.waitKey(5) & 0xFF
        if (k==27):
            break

    cv2.destroyAllWindows()
    cap.release()

- operating system: Windows 10 
- architecture (e.g. x86):    x86
- opencv-python version:    4.0.0.21

**Comment by HiteshSangwan0567** [comment]
Use the other versions of opencv like 3.4.4. There is a bug in 4.0.0.21.

**Comment by HiteshSangwan0567** [comment]
Use a different version of OpenCV.  3.4.4 would be equally good. The 4.0.0.21 has a bug which is not yet resolved.

**Comment by skvark** [comment]
Yes, OpenCV version 4.0.0 has a bug which causes this behaviour. I haven't been able to solve macOS build issues in this repository so I can't release 4.0.1 yet to PyPi.

**Comment by skvark** [comment]
For reference: https://github.com/opencv/opencv/issues/13216

**Comment by parthi2929** [comment]
Hi @skvark any update? Me too badly need 4.0.1.

**Comment by skvark** [comment]
I haven't been able to fix the macOS builds yet. I'll have a look again during this week if I have some spare time. You can see the build status at Travis: https://travis-ci.org/skvark/opencv-python

**Comment by skvark** [comment]
Build issues have been solved and I will publish soon 4.0.1.
