### ISSUE TITLE
Support for mingw

### ISSUE THREAD

**Issue by chromezh** [skvark/opencv-python#175]
## Steps

* Install [msys2](https://www.msys2.org/) on Windows 10
* Install `mingw-w64-x86_64-python3` and `mingw-w64-x86_64-python3-pip` by pacman in msys2
* Upgrade pip by `python3 -m pip install --upgrade pip`
* Run `python3 -m pip install opencv-python`, gives the following error
  ```
  Collecting opencv-python
    Could not find a version that satisfies the requirement opencv-python (from versions: )
  No matching distribution found for opencv-python
  ```
* Run `python3 -m pip install opencv-python==4.0.0.21 -v`, gives the following error
  ```
  ...
      Skipping link https://files.pythonhosted.org/packages/a1/45/69946e94e511171b6956f683cc905642fe8271ca8a637bb0d828764d9051/opencv_python-4.0.0.21-cp37-cp37m-macosx_10_6_x86_64.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=a72224ba58c7704ce8fc260ca65cfe7444d165362179f97d713234adc7f52b0e (from https://pypi.org/simple/opencv-python/); it is not compatible with this Python
      Skipping link https://files.pythonhosted.org/packages/2e/a7/750fcba266a72b4f512a4cf4d6ed37758d2e89fec49a1deab8ab192b63df/opencv_python-4.0.0.21-cp37-cp37m-manylinux1_i686.whl#sha256=ae6f1aaa64d3b9a82792669e5be04d2544ce8c2e4a71ecfac09e0a4ed7b60908 (from https://pypi.org/simple/opencv-python/); it is not compatible with this Python
      Skipping link https://files.pythonhosted.org/packages/45/bd/e0a4391ac105ecf73a6e14372174b05774634c7c6454e49c38750d516eee/opencv_python-4.0.0.21-cp37-cp37m-manylinux1_x86_64.whl#sha256=9acea43d03440e7a0bd9a9ad599394382a529d49ec6995414797645acfc3e629 (from https://pypi.org/simple/opencv-python/); it is not compatible with this Python
      Skipping link https://files.pythonhosted.org/packages/e8/3e/6d7da89f963ae3d98592a3842ca9f11296a5b31a1c534bf83a4e2bb68866/opencv_python-4.0.0.21-cp37-cp37m-win32.whl#sha256=d477594c956dfbe6688323a9a06d5b3c6d3940c4b15bef7ce4f30d25f7837f1a (from https://pypi.org/simple/opencv-python/); it is not compatible with this Python
      Skipping link https://files.pythonhosted.org/packages/cc/3c/e9b46d4ff65d4dfcca1789e32113f38d5fc1804840a4aa0bc2437ecef860/opencv_python-4.0.0.21-cp37-cp37m-win_amd64.whl#sha256=edbdded658021747a4235f178b91361d17b82031859db20731a963b8dafcab67 (from https://pypi.org/simple/opencv-python/); it is not compatible with this Python
    Could not find a version that satisfies the requirement opencv-python==4.0.0.21 (from versions: )
  ...
   ```
* Run `python3 --version`
  ```
  Python 3.7.2
  ```
* In Python REPL
  ```
  >>> import pip._internal
  >>> print(pip._internal.pep425tags.get_supported())
  [('cp37', 'cp37m', 'mingw'), ('cp37', 'none', 'mingw'), ('py3', 'none', 'mingw'), ('cp37', 'none', 'any'), ('cp3', 'none', 'any'), ('py37', 'none', 'any'), ('py3', 'none', 'any'), ('py36', 'none', 'any'), ('py35', 'none', 'any'), ('py34', 'none', 'any'), ('py33', 'none', 'any'), ('py32', 'none', 'any'), ('py31', 'none', 'any'), ('py30', 'none', 'any')]
  ```

## Question

From the above output, it seems that python3 in msys2 on Windows expects `cp37-cp37m-mingw` wheel, but there is only `cp37-cp37m-win_amd64` available.

So, is it possible to add support for mingw?

Thanks in advance!

**Comment by skvark** [comment]
There's already enough work to keep the current three major build targets up to date. Therefore I will not add mingw support to this repository. In fact, I'm not even sure if "mingw" tagged wheels can be distributed via PyPI. If you wish to use OpenCV python bindings in mingw, you will need to compile OpenCV manually with mingw.

**Comment by chromezh** [comment]
I have successfully compiled OpenCV manually with mingw. Thank you all the same!

**Comment by 3togo** [comment]
@sgalal, 
which version of python , thats supports opencv,  are you referring to ?  Is it Python 3.7.3 (default, May 28 2019, 08:37:07)  [GCC 8.3.0 64 bit (AMD64)] on win32?

**Comment by sgalal** [comment]
> 
> 
> @sgalal,
> which version of python , thats supports opencv, are you referring to ? Is it Python 3.7.3 (default, May 28 2019, 08:37:07) [GCC 8.3.0 64 bit (AMD64)] on win32?

This issue was opened on _Feb 21, 2019_, when the Python version _May 28, 2019_ was not published yet. However, as Python in msys2 has been updated to this version, I believe both version should work.

**Comment by 3togo** [comment]
in msys2 shell, I did the following. It can compile and install without any error but when try to  
import cv2

it won't work

```
pacman -S mingw-w64-x86_64-ninja mingw-w64-x86_64-python2-numpy mingw-w64-x86_64-python3-numpy 
cd /c/Users/Dreli/Downloads/opencv-4.1.0/
mkdir temp
cd temp
cmake -G Ninja -DCMAKE_INSTALL_PREFIX:PATH= /mingw64 -DWITH_DIRECTX=OFF -DWITH_DSHOW=OFF ..
ninja
ninja install
```

**Comment by 3togo** [comment]
@sgalal,
thank you very much. 
It turns out that 
pacman -S mingw-w64-x86_64-opencv
will install cv2-cpython-37m.dll into  /mingw64/lib/python3.7/site-packages

but to make it work, it is better to install the following as well
pacman -S --needed mingw-w64-i686-{ceres-solver,hdf5,python2-numpy,python3-numpy,ogre3d,tesseract-ocr}
