### ISSUE TITLE
setup.py: scikit-build 0.9.0 CMAKE_INSTALL_DIR is a function

### ISSUE THREAD

**Issue by freddy34** [skvark/opencv-python#178]
### Expected behaviour

generation of the whl file on ARMv7 architecture with Python 3.6.8 (installed by source)

### Actual behaviour

Write here what went wrong.
<img width="812" alt="opencv-python build error" src="https://user-images.githubusercontent.com/1572890/54035435-a2f17880-41b9-11e9-9c7c-8e8f71ce3cea.png">

### temporary solution

modified line [286](https://github.com/skvark/opencv-python/blob/master/setup.py#L266) to cls._setuptools_wrap.**CMAKE_INSTALL_DIR()**

**Comment by skvark** [comment]
I have the issue in https://github.com/skvark/opencv-python/tree/feat/macos_build_fix. Will be merged to master once the macOS builds work again.
