### ISSUE TITLE
opencv-python-headless asking for GTK-3

### ISSUE THREAD

**Issue by josubg** [skvark/opencv-python#179]
### Expected behaviour

Not to install Interface libraries in my server for  opencv-python-headless  version.

### Actual behaviour
I installed the opencv-python-headless  version but it appears to require GTK 3 installed in the system

### Steps to reproduce
- example code

Install all libraries dependencies except GTK:
```
pip3 install opencv-python-headless libwebp6
sudo  apt-get install liblapack3 libcblas3 libatlas3-base libwebp6 libtiff5 libjasper1 libilmbase12 
    libopenexr22 libgstreamer1.0-0 libavcodev57 libavformat57 libswscale4 
```
Try to import :
```
Import cv2
```
Error:
```
Import Error: libgtk-3.so.0: cannot  open shared object file  No such file or directory
```

- operating system
**Raspbian Stretch Lite Minimal image based on Debian Stretch**
Version:November 2018
Release date:2018-11-13
**Kernel version:4.14**
- architecture (e.g. x86)
**arm**
- opencv-python version
**opencv-python-headless**

**Comment by skvark** [comment]
This repository does not generate ARM wheels. Please report the issue to the piwheels repository (I assume that you are using Rasbperry Pi): https://github.com/bennuttall/piwheels
