### ISSUE TITLE
which opencv version is best for python 3.7.1(anaconda)

### ISSUE THREAD

**Issue by ravikanth076** [skvark/opencv-python#183]
I want to know which opencv version is best for python 3.7.1.?
and also tell me how to link the opencv to the python of anaconda?
I have an idea that we can link opencv python by copying the cv2.pyd file.
so please tell me so that it will be very helpfull for me

**Comment by skvark** [comment]
Please stop spamming issues to this repository. This is not a help forum. All the instructions on how to install ``opencv-python`` are in the README of this repository.
