### ISSUE TITLE
is it possible to link python 3.7.1(anaconda) to  opencv-3.4.5-vc14_vc15

### ISSUE THREAD

**Issue by ravikanth076** [skvark/opencv-python#184]
i have installed anaconda python of 3.7.1 on my system.
can i install  opencv-3.4.5-vc14_vc15 in my system?
if it is possible, then tell me the way i should  install open cv opencv-3.4.5-vc14_vc15.
so that an error should not come.like import cv2 error.

**Comment by skvark** [comment]
I don't understand what you mean, opencv-3.4.5-vc14_vc15 has nothing to do with this repository. Please follow the instructions in the README or ask your question at http://answers.opencv.org/questions/.
