### ISSUE TITLE
ImportError: DLL load fails on Windows10 install. MFPlat.dll MF.dll

### ISSUE THREAD

**Issue by nzjrs** [skvark/opencv-python#185]
Please close (or add a note to the README).

I encountered a missing DLL error and the root cause was missing MFPlat.dll and friends. Exactly like https://github.com/skvark/opencv-python/issues/181#issuecomment-476319876

FYI / For Google.

The page to visit to determine "which version of the media features pack should I download" is

https://support.microsoft.com/en-us/help/3145500/media-feature-pack-list-for-windows-n-editions

It would be cool if you offered / built without the MSMF (media features). `-D WITH_MSMF=no` as this seems to be / was recently bugged https://github.com/opencv/opencv/issues/11696 and https://github.com/opencv/opencv/issues/11810 in 3.4 and above. 

According to https://github.com/opencv/opencv/pull/11882 the priority is MSMF, DSHOW, VFW. Of those I think DSHOW has the least dependencies so maybe building with only that backend is sufficient on windows - but that might actually work worse for people where they have MF installed and an opecv version without a buggy MSMF backend.

In all cases it would be worth mentioning "Please install https://github.com/lucasg/Dependencies and open `cv2.pyd` to debug missing DLL issues."

**Comment by skvark** [comment]
I will have a look at those MSMF issues and add a note to the README.

**Comment by nzjrs** [comment]
Thanks. I learned that their is an entire version of Windows that misses these DLLs

https://www.google.com/amp/s/www.howtogeek.com/322112/what-is-an-n-or-kn-edition-of-windows/amp/

The current builds which require MSMF Will therefore always fail on this "Windows N"

**Comment by multiOTP** [comment]
I had the same issue. You can freely download the Media Pack for Windows 10 here : [https://www.microsoft.com/en-us/software-download/mediafeaturepack](https://www.microsoft.com/en-us/software-download/mediafeaturepack)

**Comment by skvark** [comment]
There is now a note in the README about this.

DSHOW can be forced via environment variable: `OPENCV_VIDEOIO_PRIORITY_LIST=DSHOW`

I'm keeping the builds as is to avoid any further issues.
