### ISSUE TITLE
Opencv nonfree modules with Python in VS Code

### ISSUE THREAD

**Issue by Gergo4** [skvark/opencv-python#188]
I would like to use OpenCV nonfree modules (like SIFT and SURF) with Python in VS Code.
I built the OpenCV package with CMake according to the following youtube videos:
https://www.youtube.com/watch?v=By-PKbWDZNk
https://www.youtube.com/watch?v=fIpTks0G2m0
https://www.youtube.com/watch?v=MMDABTypnZg

I have Windows 7 and use the last version of VS Code (1.33).
The directory of compiled (built) OpenCV package let be: D:\OpenCV\opencvbuild

What settings do I need to do in VS Code? I set the path of the directory, but still not working.

**Comment by skvark** [comment]
This is not a QA forum. Please ask your question at http://answers.opencv.org/questions/.
