### ISSUE TITLE
cv2.dnn.blobFromImages gives shape error

### ISSUE THREAD

**Issue by himmetozcan** [skvark/opencv-python#189]
Thanks for the amazing prebuilt opencv library. I have a problem though. I have been using the  "cv2.dnn.blobFromImage" flawlessly. However when I use  "cv2.dnn.blobFromImages" it always gives shape error: 

" cv2.error: OpenCV(4.0.0) /io/opencv/modules/dnn/include/opencv2/dnn/shape_utils.hpp:161: error: (-215:Assertion failed) start <= (int)shape.size() && end <= (int)shape.size() && start <= end in function 'total' ". 

Here is how I use it:

blob = cv2.dnn.blobFromImages(imagesAll, 1, (227, 227), (0,0,0))
net.setInput(blob)
preds = net.forward()

The shape of blob is:

(145, 3, 227, 227)

Should I change the shape of the blob? Why do you think it is not working? Thanks.

**Comment by skvark** [comment]
Please ask your question at http://answers.opencv.org/questions/ or at https://stackoverflow.com/. This is a issue tracker, not a QA forum.
