### ISSUE TITLE
function resizeWindow

### ISSUE THREAD

**Issue by ziqiangxu** [skvark/opencv-python#192]
### Expected behaviour

accept parameters: image, width, height

### Actual behaviour

image, (width, height)

### Steps to reproduce

- example code
``` python3
    cv.namedWindow(name, 0)
    w, h = img.shape[0:2]
    width = 800
    height = 800 * h / w
    size = (width, int(height))
    cv.resizeWindow(name, size)
    cv.imshow(name, img)
```
- os
deepin(linux base on debian)
-  arch
x86
-  python-opencv version
4.1.0

**Comment by skvark** [comment]
If you think there's is a bug in OpenCV, report it to the OpenCV issue tracker: https://github.com/opencv/opencv/issues
