### ISSUE TITLE
pip install opencv-python gives error on Raspbian

### ISSUE THREAD

**Issue by Jorge1701** [skvark/opencv-python#194]
### Expected behaviour

`pip install opencv-python` followed by a successful installation
### Actual behaviour
Gives the following error message
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting opencv-python
ERROR: Could not find a version that satisfies the requirement opencv-python (from version: none)
ERROR: No matching distribution found for opencv-python
```

I've tried `pip install opencv-contrib-python`, `python3 -m pip install opencv-python` and that gives me the same error.

And `pip install --upgrade pip` before trying to install opencv, but it says I already have the latest version.
### Steps to reproduce
I run the commands described above in a Raspberry Pi 3 B+ with Raspbian installed.

The versions are:
```
 $ python --version
Python 2.7.13

 $ python3 --version
Python 3.6.3

 $ pip --version
pip 19.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
```

**Comment by waveform80** [comment]
That's definitely not stock Raspbian with Python 3.6 (stretch has 3.5). At the moment we only provide support for the versions of Python in stock Raspbian, i.e. 3.4 for Jessie and 3.5 for Stretch. When Buster is released, we'll provide support for 3.7 (after a period of rebuilding that which needs rebuilding, although we're behind on OpenCV at the moment while I tinker with various bits of piwheels, sorry!).
