### ISSUE TITLE
VideoCapture(0) Incredibly slow in 4.1.0.24 vs 3.4.0.25

### ISSUE THREAD

**Issue by idiotslayer** [skvark/opencv-python#196]
VideoCapture(0) takes a second or 2 to find and activate my webcam on Win10 on opencv-python V3.4.0.25 but in python-opencv V4.1.0.25 it is terribly slow to the point of breaking my app.  15 sec (approx) opening time.

any ideas?

**Comment by native-api** [comment]
http://idownvotedbecau.se/nomcve/

**Comment by native-api** [comment]
That said, usage questions should be asked at https://stackoverflow.com and such unless you have reasons to believe that the specific packaging of this project is at fault.

**Comment by idiotslayer** [comment]
I have reason to believe a regression was made between the versions identified.  That is not a usage question so please don't refer me to stackoverflow that is inappropriate.

**Comment by skvark** [comment]
There hasn't been any compilation related changes on Windows in this repo between those versions. It is likely that the video capture related code in OpenCV has changed between those versions. This means that you should open an issue to upstream https://github.com/opencv/opencv. You should try to build OpenCV by yourself to see if the issue can be replicated between manual builds of those versions.

Keep in mind that this repository has little to do with the OpenCV project itself. It merely exists to build and provide the pre-compiled wheels of OpenCV autogenerated Python bindings for a few popular operating systems.
