### ISSUE TITLE
[ WARN:0] terminating async callback

### ISSUE THREAD

**Issue by nerdfever** [skvark/opencv-python#198]
### Expected behaviour

Assuming 2 cameras (also gives the error if only one camera):

```
C:\Users\Dave\data\Code\Python\VideoCapture>python3 test.py
Found camera 0
Found camera 1
```

### Actual behaviour

```
C:\Users\Dave\data\Code\Python\VideoCapture>python3 test.py
Found camera 0
[ WARN:0] terminating async callback
Found camera 1
[ WARN:0] terminating async callback
```

### Steps to reproduce

```
import cv2

def countCameras():
    """Returns count of found cameras (not opened yet).
    Brute force - just tries them all till it fails."""

    camCount = 0

    while True:
        cam = cv2.VideoCapture(camCount)

        if cam.isOpened():
            print("Found camera", camCount)
            cam.release()
            camCount += 1

        else:
            return camCount

countCameras()
```

- operating system

Windows 10 Pro

- architecture (e.g. x86)

x64

- opencv-python version

cv2.__version__ == '4.1.0'

**Comment by skvark** [comment]
This is a bug in OpenCV in MSMF backend: https://github.com/opencv/opencv/issues/13255

You could try ``setx OPENCV_VIDEOIO_PRIORITY_MSMF 0``. However, there's nothing I can do in this repo to fix the issue.

**Comment by linchiyu** [comment]
Had this issue on opencv4*, 3.4.4
When installed opencv 3.4.2.16 the warning disappeared

**Comment by nikhilmathewfrancis98** [comment]
![image](https://user-images.githubusercontent.com/62801039/165041564-05353b26-a5a3-4910-9782-5e1e5b77989b.png)
![image](https://user-images.githubusercontent.com/62801039/165041643-f6e9d52f-5841-4605-b8bb-d6095986fb57.png)
