### ISSUE TITLE
No builds for Python 3.6

### ISSUE THREAD

**Issue by SamCarlberg** [skvark/opencv-python#20]

**Comment by skvark** [comment]
Python 3.6 builds will be added when Numpy has releases for 3.6.

**Comment by virtuald** [comment]
Looks like they are up on pypi now.

**Comment by skvark** [comment]
I'll add Python 3.6 to the build matrix.

**Comment by skvark** [comment]
3.1.0.5 release includes now also Python 3.6 compatible wheels.
