### ISSUE TITLE
opencv-contrib-python (from versions: none)

### ISSUE THREAD

**Issue by Ruandv** [skvark/opencv-python#200]
### Expected behaviour

`pip install opencv-python` followed by a successful installation

### Actual behaviour

The installation fails with the following message : 
```
(cv) pi@raspberrypi:~ $ pip install opencv-contrib-python
Collecting opencv-contrib-python
  ERROR: Could not find a version that satisfies the requirement opencv-contrib-python (from versions: none)
ERROR: No matching distribution found for opencv-contrib-python 
```

### Steps to reproduce
- I wrote the 2017-09-07-raspbian-stretch.img to the SD Card
- Created a ssh file on the boot section to enable ssh when it start up
- Made sure all the files are up to date using `sudo apt-get update`
- Updated pip to the latest version
- Followed the installation steps **How to pip install OpenCV on Raspberry Pi** as explained in [pyimagesearch](https://www.pyimagesearch.com/2018/09/19/pip-install-opencv/)

- installed prerequisites (No Problems)
```
$ sudo apt-get install libhdf5-dev libhdf5-serial-dev libhdf5-100
$ sudo apt-get install libqtgui4 libqtwebkit4 libqt4-test python3-pyqt5
$ sudo apt-get install libatlas-base-dev
$ sudo apt-get install libjasper-dev
```
- Install pip on your Raspberry Pi (No Problems)

Then opted for the *Install OpenCV into a virtual environment on your Raspberry Pi* and i followed all the commands and steps successfully up untill the point where i have to execute this step 
```
pip install opencv-contrib-python
```
### My current versions info :
Raspbian
```
(cv) pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
Python 
``` 
(cv) pi@raspberrypi:~ $ python --version
Python 3.5.3
```
pip
``` 
(cv) pi@raspberrypi:~ $ pip --version
pip 19.1.1 from /home/pi/.virtualenvs/cv/lib/python3.5/site-packages/pip (python 3.5)
```

**Comment by skvark** [comment]
This repository does not provide wheels for ARM platforms (e.g. for Raspberry Pi). See: https://github.com/bennuttall/piwheels

**Comment by jakeggoz** [comment]
Have you resolved this issue? I have the same problem and do not know what steps to take in order to resolve it.

**Comment by skvark** [comment]
Please use the correct issue tracker for Raspberry Pi related issues:

### **https://github.com/piwheels/packages/**
