### ISSUE TITLE
CUDA support

### ISSUE THREAD

**Issue by jrobble** [skvark/opencv-python#201]
Thanks for the great work on this project. It saves us a lot of time and effort.

What needs to be done to add GPU support (specifically, CUDA)? I'm looking at the steps described [here](https://www.pyimagesearch.com/2016/07/11/compiling-opencv-with-cuda-support/) and considering trying to configure this repo's build process accordingly.

I'm wondering if anyone has already attempted to add CUDA support to this build. For example, maybe there is a fork I don't know about.

I don't think it's realistic to ask you to add CUDA support to all of the builds. Minimally, some documentation to point people in the right direction would be useful.

**Comment by jrobble** [comment]
I just realized that this has already been discussed in https://github.com/skvark/opencv-python/issues/71. Closing this issue.

**Comment by skvark** [comment]
One possible solution (I don't know if this applicable in your case): build custom wheels locally in CUDA enabled enviroment and host them for example in a private / custom PyPi index.
