### ISSUE TITLE
Can cv2.putText support Chinese output? ?such as“人”，“狗” ,THX!

### ISSUE THREAD

**Issue by QQ2737499951** [skvark/opencv-python#202]
Can cv2.putText support Chinese output? ?such as“人”，“狗” ,THX!

cv2.putText(img, text=‘中文显示’, (123,456)), font, 2, (0,255,0), 3)

各参数依次是：图片，添加的文字，左上角坐标，字体，字体大小，颜色，字体粗细

**Comment by QQ2737499951** [comment]
![222222](https://user-images.githubusercontent.com/33048209/57979159-2c3fe980-7a4c-11e9-838b-039e7cfa8d65.png)

**Comment by skvark** [comment]
OpenCV does not support Chinese characters. OpenCV supports only a small subset of ASCII characters: https://answers.opencv.org/question/86997/how-can-i-put-text-on-image-using-opencv-puttext-function/
