### ISSUE TITLE
Feature: with statement for videocapture

### ISSUE THREAD

**Issue by FruityWelsh** [skvark/opencv-python#205]
###Expected behaviour
```
with cv2.VideoCapture(VIDEOCARDNUM) as VideoObj:
    VideoObj.read()
```
### Actual behaviour
```
VideoObj = cv2.VideoCapture(VIDEOCARDNUM)
VideoObj.read()
VideoObj.release()
```

Code to reproduce:
#this works externally, I am not sure where to put in internally
```
class VideoCapture(object):
    def __init__(self, device_num):
        self.VideoObj = cv2.VideoCapture(device_num)
    def __enter__(self):
        return self.VideoObj
    def __exit__(self, type, value, traceback):
        self.VideoObj.release()
```

**Comment by skvark** [comment]
I'm not going to add any additional wrapper code to this repo. It would be of course nice to be able to use ``with`` statement but the main purpose of this repository is to provide pre-built OpenCV wheels. Extending or abstracting OpenCV behaviour further is not in the scope.
