### ISSUE TITLE
Bug in open specified image

### ISSUE THREAD

**Issue by chenshen03** [skvark/opencv-python#209]
### Expected behaviour

Read the specified image using CV2

![24831_2545048982_3b384d0444_m](https://user-images.githubusercontent.com/20432947/59415273-b71ac680-8df5-11e9-8cff-b34a137deeb0.jpg)

### Actual behaviour

Failed to read the image using CV2.
However, the specified image can be read normally using PIL and skimage.

![image](https://user-images.githubusercontent.com/20432947/59415673-838c6c00-8df6-11e9-9ba1-1617f822bd73.png)

### Steps to reproduce

- example code
```python
import cv2
path = '24831_2545048982_3b384d0444_m'
image = cv2.read(path)
```

- operating system
Linux
- architecture (e.g. x86)
x86
- opencv-python version
4.0.0.0.21

**Comment by skvark** [comment]
There's something wrong with the file. When I opened it in GIMP and saved it again it could be read just fine. OpenCV is using libjpeg-turbo under the hood and it might be more sensitive to corrupted files than for example default libjpeg. I'll update the libjepg-turbo version for the Linux builds in the next release but other than that there's really nothing I can do in this repo to fix this.

**Comment by native-api** [comment]
This image is a GIF (right-click the image, select "view image info" (Firefox)) but the file erroneouly has a `.jpg` extension. [OpenCV doesn't support GIF](https://docs.opencv.org/3.1.0/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56).

So, this is not a bug.

**Comment by chenshen03** [comment]
@skvark @native-api Thank you for your patient answers, which probably solved my question. Thank you.
