### ISSUE TITLE
pip install opencv-python gives error on Raspbian

### ISSUE THREAD

**Issue by bwanaaa** [skvark/opencv-python#212]
Expected behaviour
pip install opencv-python followed by a successful installation

Actual behaviour
Gives the following error message

Collecting opencv-python
ERROR: Could not find a version that satisfies the requirement opencv-python (from version: none)
ERROR: No matching distribution found for opencv-python

I've tried pip install opencv-contrib-python, python3 -m pip install opencv-python and that gives me the same error.
And pip install --upgrade pip before trying to install opencv, but it says I already have the latest version.

Steps to reproduce
I run the commands described above in a Raspberry Pi 3 B+ with Raspbian installed.

The versions are:
Raspbian stretch lite image dated April 2019 from official website.
https://www.raspberrypi.org/downloads/raspbian/

$uname -a
Linux raspberrypi 4.14.98-v7+ 

$cat /etc/os-release
"Raspbian GNU/Linux 9 (stretch)"

 $ python --version
Python 2.7.13

 $ python3 --version
Python 3.5.3

 $ pip --version
pip 19.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

$pip search opencv-contrib-python
opencv-contrib-python (4.1.0.25)

**Comment by native-api** [comment]
Raspberry Pi wheels are maintained by the https://www.piwheels.org/ project.
