### ISSUE TITLE
Installation Failure in Raspberry Pi 4

### ISSUE THREAD

**Issue by avishek-rc1** [skvark/opencv-python#217]
### Expected behaviour

pip install opencv-python was expected to install seamlessly

### Actual behaviour

Could not find a version that satisfies the requirement ... 

The FAQ steps was followed but still getting the same error. The OS installed (tried to) in Raspberry Buster

**Comment by waveform80** [comment]
We're currently working on building things for buster but there's a *big* backlog; no outlook when opencv specifically will be ready but we'll get there. May be a couple of weeks though.

**Comment by avishek-rc1** [comment]
Appreciate it. Thank You.

**Comment by waveform80** [comment]
Ticket in the piwheels repo: bennuttall/piwheels#172
