### ISSUE TITLE
Bug: cv2.VideoCapture(index) freezes the program if the camera is busy

### ISSUE THREAD

**Issue by manusaurio** [skvark/opencv-python#223]
### Expected behaviour

If I tried to initialize a capture from a busy camera (`cv2.VideoCapture(0)`), the program should either raise an exception, or print an error (or not) and keep running. That's how the behaviour of the C++ version of OpenCV is (it prints `libv4l2: error setting pixformat: Device or resource busy`, then the program keeps running)

### Actual behaviour

If a camera is busy, trying to start a capture from it will freeze the script. Nothing is printed or raised (that's not the problem, though, but the fact that it freezes.)

### Steps to reproduce
- example code:
```python
import cv2

cam_a = cv2.VideoCapture(0)
print("Done with cam_a")

cam_b = cv2.VideoCapture(0)
print("Done with cam_b. This message won't be printed")
```

- Operating system: Arch Linux 64 bit

- opencv-python version: 4.1.0

**Comment by manusaurio** [comment]
Wrong repository.

**Comment by skvark** [comment]
I don't think I can help with this in this repository. You should try to reproduce the issue with manually compiled OpenCV Python bindings. If the issue can be reproduced also without these precompiled packages then open an issue to the upstream https://github.com/opencv/opencv.

**Comment by manusaurio** [comment]
Mmm, I tried to reproduce this on other systems and this doesn't always happen anyway. I'll try to see what's up and report it where I should. Thanks, I'll close the issue.
