### ISSUE TITLE
How are USER and PASS set in .travis.yml?

### ISSUE THREAD

**Issue by Erotemic** [skvark/opencv-python#224]
This is more of a question than an issue, but its so specific to this repo I felt it was better to ask here rather than stackoverflow. 

How are the USER and PASS environment variables set in the .travis.yml script? I see them defined as secure encrypted string in the appveyor config, but the travis config doesn't seem to have a corresponding entry. 

I've been following this repo to figure out how to deploy my own binary wheels, and I've got everything working except for the automatic pypi deployment. Understanding what you are doing would help me a lot.

**Comment by skvark** [comment]
You can define secure variables via Travis web UI settings:

![travis_settings](https://user-images.githubusercontent.com/695340/61405614-ea63e000-a8e2-11e9-85b4-25bc95abc4ad.PNG)

Afaik this can't be done in Appveyor so the secret variables have been generated separately and added manually to appveyor.yml.

**Comment by Erotemic** [comment]
Beautiful, thank you.
