### ISSUE TITLE
Can't load openCV when not in install dir with Windows 10

### ISSUE THREAD

**Issue by bebertii** [skvark/opencv-python#225]
### Expected behaviour

I have installed opencv-python with `pip install opencv-python`. with python 3.7.4 on an up-to-date Win10 64b.
**openCV does work when the shell is on the install dir** ('C:\\Users\\Gros\\AppData\\Local\\Programs\\Python\\Python37')

### Actual behaviour

But if I try to run a script outside of the install dir without having previously imported cv2 from the install dir, I'll have an error :
`=========== RESTART: d:\Dropbox\2020\cours\2nde\pointage_video.py ===========
Traceback (most recent call last):
  File "d:\Dropbox\2020\cours\2nde\pointage_video.py", line 15, in <module>
    import cv2
ImportError: DLL load failed: Le module spécifié est introuvable.`

I added some folders to path :
`C:\Users\Gros\AppData\Local\Programs\Python\Python37\Lib\site-packages\cv2
C:\Users\Gros\AppData\Local\Programs\Python\Python37\Lib
C:\Users\Gros\AppData\Local\Programs\Python\Python37\Lib\site-packages
C:\Users\Gros\AppData\Local\Programs\Python\Python37\Scripts
C:\Users\Gros\AppData\Local\Programs\Python\Python37`

No change.

**Comment by skvark** [comment]
There's no need to add anything to the PATH. You should create a fresh virtual environment and install ``opencv-python`` there. If it works in the virtual environment then your global Python installation has probably some conflicting ``cv2`` installation.

If that doesn't work, then you have some dependency missing. Please read the FAQ and check that you have all the dependencies installed: https://github.com/skvark/opencv-python#frequently-asked-questions

**Comment by bebertii** [comment]
I'm sorry but I don't understand why ther would be a dependancy problem which prevent open-cv from working outside the install dir : it does work, but nor from anywhere.
And I still have the problem with a new virtual env. Below, I pasted what appened just after creating my new virtualenv :
`(python_env) C:\Users\Gros\python_env\Scripts>pip install opencv-python matplotlib pygame
Collecting opencv-python
  Downloading https://files.pythonhosted.org/packages/a3/50/04d0669afe884f137c2f490642756e8c4a658254300a9eaf253d1e643085/opencv_python-4.1.0.25-cp37-cp37m-win_amd64.whl (37.3MB)
     |████████████████████████████████| 37.4MB 6.8MB/s
Collecting matplotlib
  Using cached https://files.pythonhosted.org/packages/1a/c0/69e3f695d7384012e90be1e16570c08953baae00fd98094179ef87c7d5a2/matplotlib-3.1.1-cp37-cp37m-win_amd64.whl
Collecting pygame
  Using cached https://files.pythonhosted.org/packages/ed/56/b63ab3724acff69f4080e54c4bc5f55d1fbdeeb19b92b70acf45e88a5908/pygame-1.9.6-cp37-cp37m-win_amd64.whl
Collecting numpy>=1.14.5 (from opencv-python)
  Downloading https://files.pythonhosted.org/packages/26/26/73ba03b2206371cdef62afebb877e9ba90a1f0dc3d9de22680a3970f5a50/numpy-1.17.0-cp37-cp37m-win_amd64.whl (12.8MB)
     |████████████████████████████████| 12.8MB 3.2MB/s
Collecting python-dateutil>=2.1 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/c6/ea/e5474014a13ab2dcb5056608e0716c600c3d8a8bcffb10ed55ccd6a42eb0/kiwisolver-1.1.0-cp37-none-win_amd64.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl (65kB)
     |████████████████████████████████| 71kB 4.5MB/s
Collecting six>=1.5 (from python-dateutil>=2.1->matplotlib)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in c:\users\gros\python_env\lib\site-packages (from kiwisolver>=1.0.1->matplotlib) (41.0.1)
Installing collected packages: numpy, opencv-python, six, python-dateutil, cycler, kiwisolver, pyparsing, matplotlib, pygame
Successfully installed cycler-0.10.0 kiwisolver-1.1.0 matplotlib-3.1.1 numpy-1.17.0 opencv-python-4.1.0.25 pygame-1.9.6 pyparsing-2.4.2 python-dateutil-2.8.0 six-1.12.0

(python_env) C:\Users\Gros\python_env\Scripts>python3 "

(python_env) C:\Users\Gros\python_env\Scripts>python3 "d:\Dropbox\2020\cours\2nde\pointage_video.py"
'python3' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

(python_env) C:\Users\Gros\python_env\Scripts>python "d:\Dropbox\2020\cours\2nde\pointage_video.py"
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "d:\Dropbox\2020\cours\2nde\pointage_video.py", line 15, in <module>
    import cv2
ImportError: DLL load failed: Le module spécifié est introuvable.

(python_env) C:\Users\Gros\python_env\Scripts>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> import os
>>> os.getcwd()
'C:\\Users\\Gros\\python_env\\Scripts'
>>> ^Z


(python_env) C:\Users\Gros\python_env\Scripts>`
The script I tried to load uses opencv, pygame and matplotlib. Only opencv can't be loaded. However, just after I'm able to load it, because I'm on the virtualenv dir.

**Comment by skvark** [comment]
Check the cv2.so with dependency walker (see README). Your environment is somehow broken.

**Comment by bebertii** [comment]
You are right, problem solved after reinstalling Win10, everything went fine.
Thanks !
