### ISSUE TITLE
Hashes mismatch on piwheels.org file

### ISSUE THREAD

**Issue by DarthVi** [skvark/opencv-python#230]
I tried installing opencv-python on a raspberry pi zero w with the command `pip3 install --user opencv-python`. As a result I obtained the following error message

```
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    opencv-python from https://www.piwheels.org/simple/opencv-python/opencv_python-3.4.4.19-cp35-cp35m-linux_armv6l.whl#sha256=329d9d9fdd62b93d44a485aeaab4602c6f5b8555ea8bcc7dbcdc62c90cfe2c3f:
        Expected sha256 329d9d9fdd62b93d44a485aeaab4602c6f5b8555ea8bcc7dbcdc62c90cfe2c3f
             Got        3a32f926e1b319f5813ef8574b7dd3ac427768786ef0efc4a5256eb1a9b8bbe5
```

**Comment by skvark** [comment]
Please report the issue to the PiWheels repo: https://github.com/piwheels/packages

**Comment by DarthVi** [comment]
Ok, I've done that right after reading your answer. Thanks anyway.

If anyone is interested in this issue and comes across it in this page, please refer to this page: [https://github.com/piwheels/piwheels/issues/195](url)
