### ISSUE TITLE
Cannot install opencv-contrib-python

### ISSUE THREAD

**Issue by christofschroeter** [skvark/opencv-python#232]
### Expected behaviour

I am trying to use the aruco module from OpenCV.
Got a requirements.txt from a partner which includes both opencv-contrib-python and opencv-python. Installing that using pip install -r requirements.txt did not work.

Then I followed the documentation, uninstalled both opencv-python and opencv-contrib-python and reinstalled only opencv-contrib-python.

### Actual behaviour

No extra modules are provided by opencv-contrib-python. Whether I install opencv-python or opencv-contrib-python, the content of site-packages/cv2 is exactly the same.

import cv2 succeeds
from cv2 import aruco fails

I tested this on 2 computers with Linux Mint 18 and Mint 19.2 respectively. I also tried versions 3.4.3.18 (required version) and the latest version (by not requiring a specific version, resulting in 4.1.0.25). Same result.

### Steps to reproduce

pip install -r requirements.txt
where requirements.txt contains:
opencv-contrib-python==3.4.3.18
opencv-python==3.4.3.18

pip uninstall opencv-python
pip uninstall opencv-contrib-python

pip install opencv-contrib-python

(I am not even sure if the previous install and uninstall makes any difference, but that is what I did).

**Comment by abhiTronix** [comment]
@christofschroeter It's a wrong way to import aruco. Try  `import cv2.aruco as aruco` instead with the latest OpenCV.

**Comment by skvark** [comment]
> where requirements.txt contains:
> opencv-contrib-python==3.4.3.18
> opencv-python==3.4.3.18

This is wrong. Only one of the packages gets installed (depends on the order, last one overwrites the one which was installed first) and you'll end up with a mess. You should report an issue to the project that you are using. 

Additionally, if someone else is having this problem, the correct import is ``import cv2.aruco as aruco``.
