### ISSUE TITLE
No matching distribution found for opencv-python on ppc64le by pip

### ISSUE THREAD

**Issue by xauthulei** [skvark/opencv-python#234]
### Expected behaviour
I want to install `opencv-python` on ppc64le successfully.  

Write here how did you expect the library to function.
`tensor2tensor` will depend it and fetch its dependency from ` /opt/conda/lib/python3.7/site-packages`
### Actual behaviou

No matching distribution found for opencv-python

Write here what went wrong.

### Steps to reproduce
/opt/conda/lib/python3.7/site-packages# pip3 install opencv-python
Collecting opencv-python
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement opencv-python (from versions: )
No matching distribution found for opencv-python
- example code
- operating system   ppc64le 
- architecture (e.g. x86) x64
- opencv-python version : python 3.7

**Comment by xauthulei** [comment]
Hi, I a newer here, Is there a steps to create the whl on special platform, such as ppc64le.  or other solution to  create the opencv-python package .
Note, I can install the python-opencv by `apt-get`: 
/opt/conda/lib/python3.7/site-packages# ll cv2.cpython-37m-powerpc64le-linux-gnu.so
-rwxrwxr-x 2 root root 6170648 Jul  4  2018 cv2.cpython-37m-powerpc64le-linux-gnu.so*

**Comment by skvark** [comment]
See my answer to similar question here: https://github.com/skvark/opencv-python/issues/173

**Comment by xauthulei** [comment]
@skvark Thanks for your great support, that is works for me.
