### ISSUE TITLE
why cv2.rectangle does not work meeting a numpy slice or flip?

### ISSUE THREAD

**Issue by yanlongbinluck** [skvark/opencv-python#238]
```
import cv2
import numpy as np
image = np.random.rand(512,512,3)
image = image[:,:,::-1]
cv2.rectangle(image,(10,10),(100,100),(0,0,255))
cv2.imshow('',image)
cv2.waitKey(0)

```
when  I change `image = image[:,:,::-1]` to `image = np.array(image[:,:,::-1])`, it's ok

**Comment by skvark** [comment]
This is a issue tracker, not a generic Q&A forum. Please ask your question at https://answers.opencv.org/questions/ or at https://stackoverflow.com/.
