### ISSUE TITLE
Why does installing opencv-python 3.1.0.5 no longer work ?

### ISSUE THREAD

**Issue by samfux84** [skvark/opencv-python#239]
Current environment:

[sfux@eu-c7-065-01 ~]$ module list
Currently Loaded Modulefiles:
  1) modules                            3) gcc/4.8.2(default:4.8)             5) python/3.7.1
  2) new                                4) openblas/0.2.13_seq(default:seq)   6) opencv/3.1
[sfux@eu-c7-065-01 ~]$ module load eth_proxy

[sfux@eu-c7-065-01 ~]$ python -V
Python 3.7.1
[sfux@eu-c7-065-01 ~]$ pip --version
pip 19.0.3 from /cluster/apps/python/3.7.1/x86_64/lib64/python3.7/site-packages/pip (python 3.7)

[sfux@eu-c7-065-01 ~]$ cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
[sfux@eu-c7-065-01 ~]$ uname -a
Linux eu-c7-065-01 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[sfux@eu-c7-065-01 ~]$ 

Trying to install it as wheel via pip:

[sfux@eu-c7-065-01 ~]$ pip install --user opencv-python==3.1.0.5
Collecting opencv-python==3.1.0.5
  Could not find a version that satisfies the requirement opencv-python==3.1.0.5 (from versions: 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.5.20, 4.0.0.21, 4.0.1.23, 4.0.1.24, 4.1.0.25)
No matching distribution found for opencv-python==3.1.0.5

Trying to install it from source code via pip

[sfux@eu-c7-065-01 ~]$ pip install --no-binary :all: --user opencv-python==3.1.0.5
Collecting opencv-python==3.1.0.5
  Could not find a version that satisfies the requirement opencv-python==3.1.0.5 (from versions: )
No matching distribution found for opencv-python==3.1.0.5

Trying to download the source code for 3.1.0.5 from the github repository and to install it with local source code via pip:

[sfux@eu-c7-065-01 ~]$ wget https://github.com/skvark/opencv-python/archive/5.tar.gz
--2019-08-21 14:32:24--  https://github.com/skvark/opencv-python/archive/5.tar.gz
Resolving proxy.ethz.ch (proxy.ethz.ch)... 129.132.202.155
Connecting to proxy.ethz.ch (proxy.ethz.ch)|129.132.202.155|:3128... connected.
Proxy request sent, awaiting response... 302 Found
Location: https://codeload.github.com/skvark/opencv-python/tar.gz/5 [following]
--2019-08-21 14:32:25--  https://codeload.github.com/skvark/opencv-python/tar.gz/5
Connecting to proxy.ethz.ch (proxy.ethz.ch)|129.132.202.155|:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘5.tar.gz’

    [      <=>                                                                                           ] 1,075,680   1010KB/s   in 1.0s   

2019-08-21 14:32:27 (1010 KB/s) - ‘5.tar.gz’ saved [1075680]

[sfux@eu-c7-065-01 ~]$ pip install --no-binary :all: --user ./5.tar.gz 
Processing ./5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/scratch/98607568.tmpdir/pip-req-build-bd2upvkq/setup.py", line 14, in <module>
        from cv_version import opencv_version
    ModuleNotFoundError: No module named 'cv_version'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /scratch/98607568.tmpdir/pip-req-build-bd2upvkq/
[sfux@eu-c7-065-01 ~]$

Is there no way to install Python bindings for OpenCV 3.1 any more ?

**Comment by skvark** [comment]
When I released 3.1.0.5 wheels to PyPI Python 3.7 wasn't yet available so there are no wheels for Python 3.7 as you can see from here: https://pypi.org/project/opencv-python/3.1.0.5/#files

This repository did not support local builds at that time. If you wish to use old OpenCV version, compile it manually according to official OpenCV instructions.
