### ISSUE TITLE
findContours returns different results on same image

### ISSUE THREAD

**Issue by invernie** [skvark/opencv-python#240]
I have run into [the following issue](https://stackoverflow.com/questions/57660409/findcontours-approach-in-open-cv-returns-different-results-on-the-same-image-dep) when working with open-cv python library 4.1, on python 3.7 . It might be a bug related to open-cv in general rather than the python library only.

**Comment by skvark** [comment]
Please report the issue to the upstream OpenCV repository: https://github.com/opencv/opencv/issues

There might be a bug somewhere but it cannot be fixed here since the Python bindings are autogenerated from the C++ code.
