### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'freetype' with opencv-contrib-python

### ISSUE THREAD

**Issue by SIRHAMY** [skvark/opencv-python#243]
### Expected behaviour

I'm trying to use cv2 with freetype and all the documentation basically says that you just need to `pip install opencv-contrib-python` in order to get this to work. But it throws an AttributeError on this line: `free_type = cv2.freetype.createFreeType2()`

### Actual behaviour

AttributeError when trying to access freetype

### Steps to reproduce

- Create a new python file
- create a new conda env
- `pip install opencv-contrib-python`

```
import cv2

free_type = cv2.freetype.createFreeType2()
```
- operating system: Ubuntu
- opencv-python version: opencv-contrib-python==4.1.1.26

**Comment by skvark** [comment]
The pre-built wheels provided by this repository have not been compiled with Freetype. You can check the supported 3rd party dependencies by running ``cv2.getBuildInformation()``.
