### ISSUE TITLE
Install Fails on Raspberry Pi 3B+ python 3.7.3 with arch. armv7l

### ISSUE THREAD

**Issue by hirenmistry** [skvark/opencv-python#245]
### Expected behaviour

```
pip3 install opencv-python
```

### Actual behaviour

I have tried this on Raspberry Pi B3+ with python 3.7.3 with NOOB OS (Buster version).

It shows the following issue.

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting opencv-python
  Could not find a version that satisfies the requirement opencv-python (from versions:  )
No matching distribution found for opencv-python
```

I have also tried to build lib for this **buster** version 
It still generates an error and refuses to build.

```
...
...
[ 51%] Built target opencv_reg
[ 52%] Built target opencv_xphoto
make: *** [Makefile:163: all] Error 2
```

### Steps to reproduce

- Raspberry Pi 3B+ 1GB Ram
- operating system: NOOB - Raspbian (Buster version)
- architecture: armv7l
- opencv-python : 4.1.1

**Comment by skvark** [comment]
As the README states, this repository does not provide Raspberry Pi wheels. PiWheels has an issue about this: https://github.com/piwheels/packages/issues/28
