### ISSUE TITLE
Segmentation fault  11

### ISSUE THREAD

**Issue by ccworld1000** [skvark/opencv-python#252]
### Expected behaviour
clear "Segmentation fault && alert "， fix error

### Actual behaviour
![Uploading 743722F3-5714-4661-B194-138CABBB9817.png…]()

### Steps to reproduce
![Uploading 743722F3-5714-4661-B194-138CABBB9817.png…]()

- example code
print("1-----")
output = net.forward()
print("2-----")

- operating system 
macos 10.14.6
- architecture (e.g. x86)
i386
- opencv-python version 
4.1.1

**Comment by ccworld1000** [comment]
<img width="770" alt="FE1CF96F3163491B0A05F0B80996A967" src="https://user-images.githubusercontent.com/22360168/66250973-ab745680-e77c-11e9-9102-5bbea0f9b575.png">

**Comment by ccworld1000** [comment]
CC # python --version
Python 2.7.10

**Comment by skvark** [comment]
Please ask usage questions at https://answers.opencv.org/questions/. If you think that there is a bug in OpenCV, report the bug to OpenCV repository: https://github.com/opencv/opencv

I can't fix OpenCV bugs here. This repository just builds OpenCV Python bindings and publishes them to PyPI.
