### ISSUE TITLE
cv2.VideoCapture() importing file seq. with numbers on the name.

### ISSUE THREAD

**Issue by Psygoo** [skvark/opencv-python#255]
### Expected behaviour

cv2.VideoCapture() should open any sequence of files regardless of the base filename, (before the number padding).

### Actual behaviour
If the filename as numbers on the base name ( eg: test123a.000001.tif)  it ignores the sequence, and reads 1st frame only.

### Steps to reproduce

Create a file sequence (eg: test123a.000001.tif, test123a.000002.tif, test123a.000003.tif, etc)
or download from my share [here](https://drive.google.com/open?id=1D3rmykCBYYJMjn11V5eG-aPZ_Y9UKjBg) 
```
import cv2
import numpy

cap = cv2.VideoCapture('C:/images/5frames/test123a.' + '{:06d}'.format(1, ) + '.jpg', cv2.CAP_IMAGES)
cap.set(1, 2)# 2nd number is the frame to show
ret, frame = cap.read()

cv2.imshow("", frame)
cv2.waitKey(0)
```

- Windows 10 pro 64bit
-x86 64bit
-Python 3.7.4
- opencv-python 4.1.1.26

**Comment by skvark** [comment]
Please report the issue to the OpenCV repository: https://github.com/opencv/opencv/issues

This repository is just an automated tool to build OpenCV Python bindings. I cannot fix OpenCV bugs here.

**Comment by Psygoo** [comment]
It works if legacy formatting is used (eg:'%06d'.format(1, )).  This is not a binding issue?

**Comment by skvark** [comment]
The bindings are automatically generated from C++ code (https://docs.opencv.org/master/da/d49/tutorial_py_bindings_basics.html). If there's is a bug, it must be fixed at the C++ side.
