### ISSUE TITLE
Support for Gstreamer module

### ISSUE THREAD

**Issue by Tristels** [skvark/opencv-python#259]
As I understand from cv2.getBuildInformation() opencv-python and opencv-contrib-python isnt compiled with Cmake flag WITH_GSTREAMER. 

With gstreamer it is possible to make RTSP streams and VideoCapture stream augmentations/improvements with gstreamer pipes.

Is there any plan to support the Gstreamer module in the future?

**Comment by skvark** [comment]
I have to think about this. It requires quite a lot of work to get GStreamer working on all platforms.

**Comment by ozett** [comment]
it should be possible to pass cmake args to enable gstreamer (see readme.md).
but is opcencv than build in pip with gstreamer support ?
if yes:  how to pass this enviornment-variable correctly?
CMAKE-ARGS=-D WITH_GSTREAMER=ON 
CMAKE-ARGS=WITH_GSTREAMER=ON 

??
thkx for repy
...gestreamer now commonly used, would be great to get support easy with env-vars..

**Comment by ozett** [comment]
some hints for features and vars are here:  https://github.com/skvark/opencv-python/issues/345#issuecomment-644675123

`sudo pip install opencv-contrib-python`  ([from here](https://www.pyimagesearch.com/2018/09/19/pip-install-opencv/))

already done. who to do it again with gstreamer support? uninstall, set env-var, re-install? 
any hints appreciated

**Comment by Red-Eyed** [comment]
Oh, using `sudo` for `pip` is not very good idea.
your command above just downloads already built package from the `pypi` repo
To enable `gstreamer` you need to build `opencv` first.

**Comment by ozett** [comment]
ok, thankx, no sudo.

but i hoped to use only simple pip-command  with environment variable to get gstreame r support.
thats not possible?

i habe to build opencv complete as stand-alone? 
than it have the ease of pip install anymore?

grateful for any clarification. searching the most eassiest way..

**Comment by Red-Eyed** [comment]
Yes, you need to build it. `pip install` downloads packages that are on pypi.  
Currently, opencv is built w/o gstreamer, so sure, you need to build it.

**Comment by ozett** [comment]
i read the readme.md again. 

https://github.com/skvark/opencv-python#documentation-for-opencv-python
the lower part is irritating as it says i can build the pip-package myself?
clone the rep, build with gestreamer support?

and than install with pip again? (to have only one cli-cmd?)

**Comment by Red-Eyed** [comment]
yes, you can build wheel and install it via pip 
but I usually install it via ninja or make `ninja install`

**Comment by skvark** [comment]
GStreamer is not supported in the pre-build wheels found in PyPI. However, as @Red-Eyed wrote, you can build the package locally with any of the OpenCV Cmake flags and after that install it locally. There is no source distribution currently in PyPI so you'll have to clone the repository and call ``setup.py`` manually. A wheel file will be generated to ``dist`` folder which can be then installed ``pip install path/to/wheel_file.whl``.

**Comment by ozett** [comment]
hi svark, that sounds great. and clear in detail.
i will give that a try, because i already have that opencv-version from pip and its running smooth.
only gstreamer support missing.

i will report my findings here. thx.

**Comment by skvark** [comment]
Not going add GStreamer to the pre-built wheels. There is enough maintenance burden with FFmpeg already.
