### ISSUE TITLE
Document workaround for Windows Server 2012 install troubles?

### ISSUE THREAD

**Issue by pakal** [skvark/opencv-python#261]
After installing opencv-contrib-python on Windows server 2012, I had the famous error evocated in "Q: Import fails on Windows: ImportError: DLL load failed: The specified module could not be found.?"

However, trying to install "Windows Server Essentials Media Pack" required the "Windows Server Essentials Experience" role, and installing this role via Server Manager changed a lot the config of the machine (installing active directory management for local accounts etc.).

It turned out I only needed to install the "**Media Foundation**" feature in the Server Manager, which didn't touch the rest of the server config. 
I didn't find info about this on the Web, maybe it's worth adding this specific workaround to the FAQ ?

**Comment by skvark** [comment]
Could you create a pull request for this? I could write an entry to the FAQ but it's better if it's done by someone who has first hand experience about the issue.

**Comment by pakal** [comment]
Indeed, here you have: https://github.com/skvark/opencv-python/pull/264
