### ISSUE TITLE
setting exposure not working for Logitech cameras

### ISSUE THREAD

**Issue by ramymagdy-rm** [skvark/opencv-python#262]
**### Expected behaviour**
since version 3.2.0.7, setting exposure was not possible anymore, I had to use other cameras and they worked! but not for Logitech C930 or C270 along with opencv-python, using different platforms macOS, Linux and windows 

Write here how did you expect the library to function.
to set the exposure using the function, I've used before
cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_EXPOSURE, -11)
 
**### Actual behaviour**
now setting the exposure has no effect
even cap.get(cv2.CAP_PROP_EXPOSURE)
returns 0.0

**Write here what went wrong.**

**### Steps to reproduce**
use any of the mentioned cameras

for the code use a simple video acquisition

**- example code**

import cv2

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_EXPOSURE, -11)
print(cap.get(cv2.CAP_PROP_EXPOSURE))

while True:
    #cap.set(cv2.CAP_PROP_FPS, 30)
    _, frame = cap.read()
    #cv2.imshow('frame', frame)
    cv2.imwrite('image.png', frame)

    key = cv2.waitKey(1)
    if key & 0xFF == ord('s'):
        cv2.imwrite('image.png', frame)
    if key & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
______________________
**- operating system**
macOS Catalina, linux ubuntu 18.04, windows 10
______________________
**- architecture (e.g. x86)**
64-bit
______________________
**- opencv-python version**
opencv-python -> 4.1.1(26)

macOS Catalina, python 3.7.5
linux ubuntu 18.04, python 3.6.8
windows 10, python 3.7.5

**Comment by skvark** [comment]
Please report the issue to the OpenCV repository: https://github.com/opencv/opencv. I cannot fix OpenCV bugs here.

**Comment by ramymagdy-rm** [comment]
@skvark it came out that it uses this backend

CODE
import cv2
print(cv2.getBuildInformation())
cap = cv2.VideoCapture(0, cv2.CAP_PROP_BACKEND)
#if not cap.isOpened():
#raise SystemError("could not open")
retval = cv2.videoio_registry.getBackendName(cv2.CAP_PROP_EXPOSUREPROGRAM)

print(retval, cap) #getBackendName(cap))
cap.set(cv2.CAP_PROP_EXPOSURE, -11)
print(cap.get(cv2.CAP_PROP_BACKEND))

cap.release()
cv2.destroyAllWindows()

returned value

General configuration for OpenCV 4.1.1 =====================================
Version control: 4.1.1

Platform:
Timestamp: 2019-09-02T14:54:43Z
Host: Darwin 16.7.0 x86_64
CMake: 3.9.4
CMake generator: Unix Makefiles
CMake build tool: /usr/bin/make
Configuration: Release

CPU/HW features:
Baseline: SSE SSE2 SSE3 SSSE3
requested: DETECT
Dispatched code generation: SSE4_1 SSE4_2 FP16 AVX AVX2
requested: SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
SSE4_1 (13 files): + SSE4_1
SSE4_2 (1 files): + SSE4_1 POPCNT SSE4_2
FP16 (0 files): + SSE4_1 POPCNT SSE4_2 FP16 AVX
AVX (4 files): + SSE4_1 POPCNT SSE4_2 AVX
AVX2 (27 files): + SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

C/C++:
Built as dynamic libs?: NO
C++ Compiler: /usr/local/opt/ccache/libexec/clang++ (ver 8.1.0.8020042)
C++ flags (Release): -stdlib=libc++ -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -DNDEBUG
C++ flags (Debug): -stdlib=libc++ -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections -fvisibility=hidden -fvisibility-inlines-hidden -g -O0 -DDEBUG -D_DEBUG
C Compiler: /usr/local/opt/ccache/libexec/clang
C flags (Release): -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -DNDEBUG
C flags (Debug): -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections -fvisibility=hidden -fvisibility-inlines-hidden -g -O0 -DDEBUG -D_DEBUG
Linker flags (Release): -Wl,-dead_strip
Linker flags (Debug): -Wl,-dead_strip
ccache: YES
Precompiled headers: NO
Extra dependencies: -framework OpenCL ade /usr/local/lib/QtGui.framework /usr/local/lib/QtTest.framework /usr/local/lib/QtCore.framework
3rdparty dependencies: ittnotify libprotobuf zlib libjpeg-turbo libwebp libpng libtiff libjasper IlmImf quirc ippiw ippicv

OpenCV modules:
To be built: calib3d core dnn features2d flann gapi highgui imgcodecs imgproc ml objdetect photo python3 stitching video videoio
Disabled: world
Disabled by dependency: -
Unavailable: java js python2 ts
Applications: -
Documentation: NO
Non-free algorithms: NO

GUI:
QT: YES (ver 4.8.7 EDITION = OpenSource)
QT OpenGL support: NO
Cocoa: YES
VTK support: NO

Media I/O:
ZLib: build (ver 1.2.11)
JPEG: build-libjpeg-turbo (ver 2.0.2-62)
WEBP: build (ver encoder: 0x020e)
PNG: build (ver 1.6.37)
TIFF: build (ver 42 - 4.0.10)
JPEG 2000: build (ver 1.900.1)
OpenEXR: build (ver 2.3.0)
HDR: YES
SUNRASTER: YES
PXM: YES
PFM: YES

Video I/O:
DC1394: NO
FFMPEG: YES
avcodec: YES (58.35.100)
avformat: YES (58.20.100)
avutil: YES (56.22.100)
swscale: YES (5.3.100)
avresample: YES (4.0.0)
GStreamer: NO
AVFoundation: YES

Parallel framework: GCD

Trace: YES (with Intel ITT)

Other third-party libraries:
Intel IPP: 2019.0.0 Gold [2019.0.0]
**at: /Users/travis/build/skvark/opencv-python/_skbuild/macosx-10.8-x86_64-3.7/cmake-build/3rdparty/ippicv/ippicv_mac/icv**
Intel IPP IW: sources (2019.0.0)
**at: /Users/travis/build/skvark/opencv-python/_skbuild/macosx-10.8-x86_64-3.7/cmake-build/3rdparty/ippicv/ippicv_mac/iw**
Eigen: NO
Custom HAL: NO
Protobuf: build (3.5.1)

OpenCL: YES (no extra features)
Include path: NO
Link libraries: -framework OpenCL

Python 3:
Interpreter: /Users/travis/build/**skvark/opencv-python/**venv/bin/python (ver 3.7)
Libraries: /Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib (ver 3.7.0)
numpy: /Users/travis/build/**skvark/opencv-python**/venv/lib/python3.7/site-packages/numpy/core/include (ver 1.14.5)
install path: python

Python (for build): /Users/travis/build/skvark/opencv-python/venv/bin/python

Java:
ant: NO
JNI: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers
Java wrappers: NO
Java tests: NO
Install to:/Users/travis/build/skvark/opencv-python/_skbuild/macosx-10.8-x86_64-3.7/cmake-install-----------------------------------------------------------------

UnknownVideoAPI(17009)

**Comment by skvark** [comment]
I have no idea what's the issue. This indicates that you are out of luck, some cameras just won't work:

https://answers.opencv.org/question/175793/why-am-i-not-able-to-change-all-settings-of-logitech-c920-camera-using-opencv-python/

**Comment by skvark** [comment]
Also, this doesn't look right:

``cap = cv2.VideoCapture(0, cv2.CAP_PROP_BACKEND)``

try for example:

``cap = cv2.VideoCapture(-1)``

**Comment by abhiTronix** [comment]
Also from [official docs](https://docs.opencv.org/3.4/d4/d15/group__videoio__flags__base.html#ggaeb8dd9c89c10a5c63c139bf7c4f5704da0bdf71aedd96f43adf1dc007cc2cff85):

`cv.CAP_PROP_BACKEND` : Current backend (enum VideoCaptureAPIs). Read-only property.

It is not a valid backend but a readonly property. The valid backends can be found here: https://docs.opencv.org/3.4/dc/dfc/group__videoio__flags__others.html

**Comment by ramymagdy-rm** [comment]
tried the same code and camera on windows 10, I was able to adjust exposure!
so I guess I need to build a valid release from opencv.org, would that guarantee, valid or official backend, whatever the OS is? please correct me if I'm wrong... I'm new to this -backend- expression

**Comment by abhiTronix** [comment]
> tried the same code and camera on windows 10, I was able to adjust exposure!

It depends whats type of API bindings does on windows 10 OpenCV is using, it may default to correct backend automatically. So you must always use correct code to access valid backend.

>  I need to build a valid release from opencv.org

To test official version, You first need to completely remove the `opencv-python` pypi version and then install official OpenCV from scratch. You can follow [this tutorial](https://www.pyimagesearch.com/2018/05/28/ubuntu-18-04-how-to-install-opencv/) for installing official OpenCV.

> would that guarantee, valid or official backend, whatever the OS is?

Nope, you first have to use correct code and a valid backend to ensure everything is ok. But still you cannot guarantee anything as it depends upon your camera hardware.
