### ISSUE TITLE
use SIFT & SURF with python3.8

### ISSUE THREAD

**Issue by williamfzc** [skvark/opencv-python#265]
hi, i have a question:

- maybe 3.4.2.17 is the latest version which supports SIFT and SURF.
- but this version support python 3.7 only.
- which means we can not use these methods with python 3.8

any way to solve this? 
thanks

**Comment by waveform80** [comment]
Duplicate of #126 ?

**Comment by williamfzc** [comment]
> Duplicate of #126 ?

I see. thanks :)
