### ISSUE TITLE
Alpine Docker Container Installation 

### ISSUE THREAD

**Issue by joequint** [skvark/opencv-python#268]
### Expected behaviour

Expected that pip install opencv-python should work

### Actual behaviour

ERROR: Could not find a version that satisfies the requirement opencv-python (from versions: none)
ERROR: No matching distribution found for opencv-python

### Steps to reproduce

DOCKERFILE: 
FROM python:3.7-alpine
RUN pip install opencv-python

## My suggestion is to add the following example to the readthedocs https://pypi.org/project/opencv-python/   
I figured this out from https://github.com/pypa/pip/issues/3969

DOCKERFILE
FROM python:3.7-alpine
RUN pip install opencv-python
RUN echo 'manylinux1_compatible = True' > /usr/local/bin/_manylinux.py
RUN python -c 'import sys; sys.path.append(r"/_manylinux.py")'

**Comment by skvark** [comment]
This is not related to ``opencv-python``. Alpine is based on musl libc, not on glibc. Manylinux wheels are officially compatible only with glibc. I'm not going to add any hacks to the readme. As the linked issue suggests, many libraries will break badly if that flag is enabled.

**Comment by zhanghuanhao** [comment]
Thanks a lot. But I think you wrote it in the wrong order. @joequint 
DOCKERFILE
FROM python:3.7-alpine
RUN echo 'manylinux1_compatible = True' > /usr/local/bin/_manylinux.py
RUN python -c 'import sys; sys.path.append(r"/_manylinux.py")'
RUN pip install opencv-python

**Comment by joequint** [comment]
Makes sense.  I haven't given this a shot for a little bit since it didn't work for me.
