### ISSUE TITLE
Generalize the standard image processing function to the case where the number of channels is greater than 4

### ISSUE THREAD

**Issue by mathfinder** [skvark/opencv-python#273]
In my case, I need to process all frames in a video in the same way, where processing the frames step by step is too slow. I plan to concat the frames in batch and input to the standard image processing functions. For example, I concat the frames on the channel axis as a generalized "image", e.g., we have t frames: [hxwxc, ]xt  -> hxwx(c*t).  In this case, some of standard image processing functions work well (e.g., resize), while some do not work well (e.g., copyMakeBorder) 

`import cv2`
`import numpy as np`
`img = np.zeros((100, 100, 300))`

When I use cv2.copyMakeBorder and do not use "value" param, It works:
`img_border = cv2.copyMakeBorder(img, 1, 1, 1, 1, cv2.BORDER_CONSTANT) `

When I use cv2.copyMakeBorder and  use "value" param, It does not work:
`color = (128,)*300`
`img_border = cv2.copyMakeBorder(img, 1, 1, 1, 1, cv2.BORDER_CONSTANT, value=color)
`

Error: 

> TypeError: Scalar value for argument 'value' is longer than 4

**Comment by skvark** [comment]
This sounds like a usage question or a feature request. You should open an issue to the actual OpenCV repository https://github.com/opencv/opencv or ask the question at https://answers.opencv.org/questions/.
