### ISSUE TITLE
`cv2.fillPoly()` crashes application when passed 0-length vertex array

### ISSUE THREAD

**Issue by ntjess** [skvark/opencv-python#278]
### Expected behaviour
`cv2.fillPoly()` should be able to handle 0-length vertex lists, like

`np.ones((0,2))`

and leave the original image unchanged.

### Actual behaviour

On running

```
img = np.ones((256,256))
cv2.fillpoly(img, [np.ones((0,2), dtype=int)], 0)
```

The python shell aborts and disconnects.
- Windows 10 build 1909
- i7 7th Gen, 64 bit, 12 GB memory
- opencv version 4.1.0

**Comment by skvark** [comment]
This is a issue tracker related to opencv-python packaging. Please report the issue to the actual OpenCV repository: https://github.com/opencv/opencv/issues

**Comment by ntjess** [comment]
Sorry, I wasn't sure if the bug was related to the python port or opencv itself. I will do that.

Thanks!
