### ISSUE TITLE
Linux raspberrypi 4.19.75: undefined symbol: __atomic_fetch_add_8

### ISSUE THREAD

**Issue by sangnguyen7** [skvark/opencv-python#279]
### Expected behaviour

Write here how did you expect the library to function.

Successfully import opencv on RPi 4.x

### Actual behaviour

Write here what went wrong.

opencv only works on version opencv-python==3.4.6.27. However, it does not work on the later version i.e opencv-python==3.4.7.28, opencv-python==4.1.1.26

```
Traceback (most recent call last):
  File "hello.py", line 1, in <module>
    import cv2
  File "/home/pi/.pyenv/versions/3.7.6/lib/python3.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: /home/pi/.pyenv/versions/3.7.6/lib/python3.7/site-packages/cv2/cv2.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_fetch_add_8
```

### Steps to reproduce

- example code
```
pip install opencv-python==3.4.7.28
```

or 

```
pip install opencv-python
```

then run

```
>>> import cv2
>>> print(cv2.__version__)
```
- operating system
uname -a
Linux raspberrypi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
- architecture (e.g. x86)
armv7l
- opencv-python version
afftected versions from 3.4.7.28 --> latest

I have not tested all versions yet but only some of them.

Please let me know if you need anything from me. Thanks.

**Comment by skvark** [comment]
This repository does not provide wheels for Raspberry Pi. Open an issue to PiWheels issue tracker: https://github.com/piwheels/packages/issues

**Comment by jnaulty** [comment]
This will work if you have `LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0` in the env

**Comment by jnaulty** [comment]
For those interested in following the upstream developments, check
https://github.com/piwheels/packages/issues/59
