### ISSUE TITLE
Failed install opencv in travis

### ISSUE THREAD

**Issue by codeskyblue** [skvark/opencv-python#28]
I got the message

```
$ pip install opencv_python
Collecting opencv-python
  Could not find any downloads that satisfy the requirement opencv-python
  No distributions at all found for opencv-python
```

Details: <https://travis-ci.org/NetEaseGame/AutomatorX/jobs/214158885>

**Comment by skvark** [comment]
Your pip version is too old for manylinux wheels. Upgrade it: ``pip install --upgrade pip``

**Comment by codeskyblue** [comment]
It works, thank you very much
