### ISSUE TITLE
Support for tensor data.

### ISSUE THREAD

**Issue by ebegen** [skvark/opencv-python#282]
I want to use tensor data with opencv methods such as cv2.threshold() or cv2.connectedComponentsWithStats() etc. But when I try to give tensor data to these methods then I get an error like `TypeError: Expected Ptr<cv::UMat> for argument '%s'`

How to use tensor data with opencv methods?

**Comment by dkurt** [comment]
What is tensor data? Please provide a minimal working example

**Comment by skvark** [comment]
Please open an issue to the OpenCV repository if you have feature requests: https://github.com/opencv/opencv/issues
