### ISSUE TITLE
Changing camera source on a MacBook

### ISSUE THREAD

**Issue by PatrickHennessey** [skvark/opencv-python#286]
I'm trying to use this script, https://github.com/kevinam99/capturing-images-from-webcam-using-opencv-python/blob/master/webcam-capture-v1.01.py, on my MacBook with an extra, USB webcam attached to it to take a quick picture for a demo. But, I'm unable to access the USB cam, only the built-in iSight or whatever camera.

I know the script is from another person, but he hasn't been answering any questions, so I thought I would try here.

I had hoped that changing **webcam = cv2.VideoCapture(0)** to **webcam = cv2.VideoCapture(1)** would allow me to use the USB camera, but it still uses the built-in camera. The USB camera does work with Photo Booth and other applications, but not via this py file. Any ideas on what I need to do?

Thanks for any help!

**Comment by HiteshSangwan0567** [comment]
Maybe, It is due to macOS Mojave new privacy protections when an app is requiring access to the webcam or microphone if you are using the same.
