### ISSUE TITLE
Relax numpy version requirements

### ISSUE THREAD

**Issue by adrianmoisey** [skvark/opencv-python#29]
Hi
Currently opencv-python requires numpy >=1.11.3 to be installed despite requirements.txt and .travis.yml specifying >= 1.11.1.

We want to use this with Anaconda 4.1.1, which installs numpy 1.11.1. 
Would it be possible to relax these dependencies, and install/test/publish with version 1.11.1?

**Comment by skvark** [comment]
There are no numpy 1.11.1 builds for Python 3.6. If you are using older Python version than 3.6 it is possible to relax the version requirement.

A proper fix for the numpy requirement is to parameterize the numpy version for each build separately in the matrices to lowest possible version to maintain ABI compatibility. For Travis it should be implemented like this: https://github.com/MacPython/astropy-wheels/blob/master/.travis.yml and for Appveyor in similar way. This means also that the numpy requirement has to be removed from requirements.txt.

**Comment by adrianmoisey** [comment]
I did a test here: https://github.com/skvark/opencv-python/pull/30
And saw that it breaks on Windows. 

If I made a patch, like what you describe above, would you merge it?

**Comment by skvark** [comment]
Yes, I would merge it. I'm finishing currently contrib modules support in another branch so if it's done within a week or the fix be available in the next release.

**Comment by adrianmoisey** [comment]
I'll give it a try, thanks
