### ISSUE TITLE
Python 3.8.1 virtualenv installation problem

### ISSUE THREAD

**Issue by hOPFEN1** [skvark/opencv-python#292]
### Expected behaviour
In an virtualenv the pip install is not working neither the precompiled wheel installation
1. create a virtualenv venv
2. run
```python
pip install opencv-python
```
I did expect the library to install successfully.

### Actual behaviour
Error with:
```
Collecting opencv-python
  Could not find a version that satisfies the requirement opencv-python (from versions: )
No matching distribution found for opencv-python
```
I did expect the library to install. In a virtualenv with Python 3.7.4 it works. 

### Steps to reproduce

- Create a virtual environment
try to execute pip install in that environment:
- example code:
pip install opencv-python
- operating system: Windows 10
- architecture: x64
- opencv-python version: 4.2.0

### Further infos:
To see the supported wheel tags inside my Python 3.8.1 virtualenv i ran:
```python
<path_to_my_repository>\venv\Scripts> .\python.exe
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from setuptools.pep425tags import get_supported
>>>
>>> for t in get_supported():
...     print(str(t))
...
('cp38', 'cp38m', 'win_amd64')
('cp38', 'none', 'win_amd64')
('py3', 'none', 'win_amd64')
('cp38', 'none', 'any')
('cp3', 'none', 'any')
('py38', 'none', 'any')
('py3', 'none', 'any')
('py37', 'none', 'any')
('py36', 'none', 'any')
('py35', 'none', 'any')
('py34', 'none', 'any')
('py33', 'none', 'any')
('py32', 'none', 'any')
('py31', 'none', 'any')
('py30', 'none', 'any')
```

I noticed that the naming of the wheel file changed:
 - opencv_python-4.2.0-cp37-cp37m-win_amd64.whl
compared to:
 - opencv_python-4.2.0-cp38-cp38-win_amd64.whl

But i am not sure how this correlates to the supported wheel tags.

Anyway i am using python 3.7.4 for now. I just wanted to let u guys know.

**Comment by skvark** [comment]
I cannot replicate this. Just downloaded Python 3.8.1 official installer and tested:

```powershell
PS C:\Users\> py -3.8
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
PS C:\Users\> py -3.8 -m venv test
PS C:\Users\> cd .\test\
PS C:\Users\\test> .\Scripts\Activate.ps1
(test) PS C:\Users\\test> pip install opencv-python
Collecting opencv-python
  Downloading https://files.pythonhosted.org/packages/4a/58/58513225ca637292ae5aada194e5c641f891218145e94f3a59b15c823e75/opencv_python-4.2.0.32-cp38-cp38-win_amd64.whl (33.1MB)
     |████████████████████████████████| 33.1MB 6.4MB/s
Collecting numpy>=1.17.3 (from opencv-python)
  Downloading https://files.pythonhosted.org/packages/95/47/ea0ae5a778aae07ede486f3dc7cd4b788dc53e11b01a17251b020f76a01d/numpy-1.18.1-cp38-cp38-win_amd64.whl (12.8MB)
     |████████████████████████████████| 12.8MB 3.2MB/s
Installing collected packages: numpy, opencv-python
Successfully installed numpy-1.18.1 opencv-python-4.2.0.32
```

**Comment by Mattwmaster58** [comment]
@hOPFEN1 Make sure that your version of `pip` is updated. I encountered this exact same issue, but it was resolved upon upgrading `pip` in my venv.
