### ISSUE TITLE
FeatureRequest: Any plans to implement the QR Multi functions - detectAndDecodeMulti?

### ISSUE THREAD

**Issue by benmcnciol** [skvark/opencv-python#294]
### Expected behaviour

I'd like to be able to use the detectAndDecodeMulti function defined here https://docs.opencv.org/3.4/de/dc3/classcv_1_1QRCodeDetector.html

### Actual behaviour

I don't believe this function has been exposed in the python implementation of opencv.

### Steps to reproduce

- example code

import cv2
def video_reader():
    cam = cv2.VideoCapture(0)
    detector = cv2.QRCodeDetector()
    while True:
        _, img = cam.read()
        data, bbox, _ = detector.detectAndDecodeMulti(img)
        if data:
            print("QR Code detected-->", data)
        cv2.imshow("img", img)    
        if cv2.waitKey(1) == ord("Q"):
            break
    cam.release()
    cv2.destroyAllWindows()
video_reader()

- operating system
Win10

- architecture (e.g. x86)
x64

- opencv-python version

 opencv-python version 4.2.0.32

**Comment by skvark** [comment]
If the function has not been exposed, please open an issue to the actual OpenCV repository: https://github.com/opencv/opencv/issues

This repository is just a build toolchain and has no control over OpenCV code level features.
