### ISSUE TITLE
pypy3 compile exception

### ISSUE THREAD

**Issue by TensorTom** [skvark/opencv-python#296]
ubuntu 18.04
pypy3 in virtualenv
```
git clone https://github.com/skvark/opencv-python.git
python setup.py install
```
and getting:

`Exception: Not found: 'python/cv2[^/]*\.pypy36\-pp73\-x86_64\-linux\-gnu\.so'`

Related stack q with more details: https://stackoverflow.com/questions/60386499/exception-not-found-python-cv2-pypy36-pp73-x86-64-linux-gnu-so-co

**Comment by extraymond** [comment]
You might wanna try:

1. pip install numpy first, which avoids the cmake error if your stackoverflow post.
2. point libpypy to the one under your venv/bin. 

I've tried with the snap version and it build. I've comment on your stackoverflow post, hope that helps.

**Comment by native-api** [comment]
PyPy is not officially supported by this project, so you are on your own.

Check what name the `.so` that OpenCV build produces has and where it is.

It looks like PyPy sets `sysconfig.get_config_var('SO')` to this long suffix ([everything after asterisk](https://github.com/skvark/opencv-python/blob/1ca69aaa7dbacfc72dbb7a03a0cb5556a693420b/setup.py#L85)), but the `.so` that OpenCV build produces doesn't actually conform to it.

**Comment by extraymond** [comment]
@TensorTom From your so question, seems like you are using the snap version of pypy3, can you try again with pyenv or venv and report? I got opencv build on pypy from pyenv just fine.
