### ISSUE TITLE
Phase Unwrapping Bindings 

### ISSUE THREAD

**Issue by samjett247** [skvark/opencv-python#298]
I believe OpenCV has a phase unwrapping algorithm implemented, based on the documentation [here](https://docs.opencv.org/4.2.0/d5/d7d/classcv_1_1phase__unwrapping_1_1HistogramPhaseUnwrapping.html), but I've been unable to find it to use it within the Python bindings. Does anyone know anything about this or has used this function?

- opencv-python version: 4.1.0.25

**Comment by skvark** [comment]
Those are available in the ``opencv-contrib-python`` package. Uninstall ``opencv-python`` and install ``opencv-contrib-python``. In the future, please read the documentation: 

1. Open the OpenCV documentation root for your version of OpenCV (link can be also found from the README of this repository): https://docs.opencv.org/4.1.0/index.html
2. Open your browser search (ctrl+f) and search for the module name
3. Check if the module is in the stable core package (**main modules**) or in the contrib side (**extra modules**) and install either ``opencv-python`` or ``opencv-contrib-python`` according to your needs (do not install both):

![phase_unwrapping](https://user-images.githubusercontent.com/695340/86350281-1cdd2900-bc6b-11ea-8d30-e04af171e311.PNG)
