### ISSUE TITLE
Cannot destroy high GUI windows on Mac OS

### ISSUE THREAD

**Issue by mluerig** [skvark/opencv-python#300]
##### System information (version)

- OpenCV == 4.1.2 (4.2 has 
- Operating System / Platform => mac os catalina (10.15.3)
- Compiler => bash / Spyder (4.0.1)
- Python 3.7

##### Detailed description

I am devloping a python package that makes heavy use of opencv. While I have no problems on Windows and Linux, I cannot close high GUI windows on Mac OS that I evoke with imshow. I have tried every possible combination of waitKey / destroyAllWindows / windowThread etc. (e.g. as suggested [here](https://stackoverflow.com/questions/6116564/destroywindow-does-not-close-window-on-mac-using-python-and-opencv
)). It's as if the command is issued (see error msg if I attemp to close a window twice), but the window is still there, and frozen.

I am grateful for any advice as to where the error could be, because I am not a mac user and don't know where the os-specific opencv builds differ. I am guessing it's got to do with the QT backend that mac and linux appear to use?

##### Steps to reproduce

```
import cv2
import numpy as np

image = np.zeros((512,512))

cv2.namedWindow("window", cv2.WINDOW_NORMAL)
cv2.startWindowThread() 
cv2.imshow("window", image)
if cv2.waitKey() == 13:
    cv2.waitKey(1)
    cv2.destroyWindow("window")
    cv2.waitKey(1)
cv2.destroyWindow("window")

error: OpenCV(4.1.2) /Users/travis/build/skvark/opencv-python/opencv/modules/highgui/src/window_QT.cpp:539: error: (-27:Null pointer) NULL guiReceiver (please create a window) in function 'cvDestroyWindow'

cv2.getBuildInformation()
```
'\nGeneral configuration for OpenCV 4.1.2 =====================================\n  Version control:               4.1.2\n\n  Extra modules:\n    Location (extra):            /Users/travis/build/skvark/opencv-python/opencv_contrib/modules\n    Version control (extra):     4.1.2\n\n  Platform:\n    Timestamp:                   2019-11-22T00:52:28Z\n    Host:                        Darwin 16.7.0 x86_64\n    CMake:                       3.9.4\n    CMake generator:             Unix Makefiles\n    CMake build tool:            /usr/bin/make\n    Configuration:               Release\n\n  CPU/HW features:\n    Baseline:                    SSE SSE2 SSE3 SSSE3\n      requested:                 DETECT\n    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2\n      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX\n      SSE4_1 (14 files):         + SSE4_1\n      SSE4_2 (1 files):          + SSE4_1 POPCNT SSE4_2\n      FP16 (0 files):            + SSE4_1 POPCNT SSE4_2 FP16 AVX\n      AVX (4 files):             + SSE4_1 POPCNT SSE4_2 AVX\n      AVX2 (27 files):           + SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2\n\n  C/C++:\n    Built as dynamic libs?:      NO\n    C++ Compiler:                /usr/local/opt/ccache/libexec/clang++  (ver 8.1.0.8020042)\n    C++ flags (Release):         -stdlib=libc++   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG\n    C++ flags (Debug):           -stdlib=libc++   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG\n    C Compiler:                  /usr/local/opt/ccache/libexec/clang\n    C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG\n    C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG\n    Linker flags (Release):      -Wl,-dead_strip  \n    Linker flags (Debug):        -Wl,-dead_strip  \n    ccache:                      YES\n    Precompiled headers:         NO\n    Extra dependencies:          -framework OpenCL ade /usr/local/lib/QtGui.framework /usr/local/lib/QtTest.framework /usr/local/lib/QtCore.framework /usr/local/opt/freetype/lib/libfreetype.dylib /usr/local/Cellar/harfbuzz/2.6.4/lib/libharfbuzz.dylib\n    3rdparty dependencies:       ittnotify libprotobuf zlib libjpeg-turbo libwebp libpng libtiff libjasper IlmImf quirc ippiw ippicv\n\n  OpenCV modules:\n    To be built:                 aruco bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dnn_superres dpm face features2d flann freetype fuzzy gapi hfs highgui img_hash imgcodecs imgproc line_descriptor ml objdetect optflow phase_unwrapping photo plot python3 quality reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab xfeatures2d ximgproc xobjdetect xphoto\n    Disabled:                    world\n    Disabled by dependency:      -\n    Unavailable:                 cnn_3dobj cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv hdf java js matlab ovis python2 sfm ts viz\n    Applications:                -\n    Documentation:               NO\n    Non-free algorithms:         NO\n\n  GUI: \n    QT:                          YES (ver 4.8.7 EDITION = OpenSource)\n      QT OpenGL support:         NO\n    Cocoa:                       YES\n    VTK support:                 NO\n\n  Media I/O: \n    ZLib:                        build (ver 1.2.11)\n    JPEG:                        build-libjpeg-turbo (ver 2.0.2-62)\n    WEBP:                        build (ver encoder: 0x020e)\n    PNG:                         build (ver 1.6.37)\n    TIFF:                        build (ver 42 - 4.0.10)\n    JPEG 2000:                   build (ver 1.900.1)\n    OpenEXR:                     build (ver 2.3.0)\n    HDR:                         YES\n    SUNRASTER:                   YES\n    PXM:                         YES\n    PFM:                         YES\n\n  Video I/O:\n    DC1394:                      NO\n    FFMPEG:                      YES\n      avcodec:                   YES (58.54.100)\n      avformat:                  YES (58.29.100)\n      avutil:                    YES (56.31.100)\n      swscale:                   YES (5.5.100)\n      avresample:                YES (4.0.0)\n    GStreamer:                   NO\n    AVFoundation:                YES\n\n  Parallel framework:            GCD\n\n  Trace:                         YES (with Intel ITT)\n\n  Other third-party libraries:\n    Intel IPP:                   2019.0.0 Gold [2019.0.0]\n           at:                   /Users/travis/build/skvark/opencv-python/_skbuild/macosx-10.9-x86_64-3.7/cmake-build/3rdparty/ippicv/ippicv_mac/icv\n    Intel IPP IW:                sources (2019.0.0)\n              at:                /Users/travis/build/skvark/opencv-python/_skbuild/macosx-10.9-x86_64-3.7/cmake-build/3rdparty/ippicv/ippicv_mac/iw\n    Eigen:                       NO\n    Custom HAL:                  NO\n    Protobuf:                    build (3.5.1)\n\n  OpenCL:                        YES (no extra features)\n    Include path:                NO\n    Link libraries:              -framework OpenCL\n\n  Python 3:\n    Interpreter:                 /Users/travis/build/skvark/opencv-python/venv/bin/python (ver 3.7.5)\n    Libraries:                   /Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib (ver 3.7.5)\n    numpy:                       /Users/travis/build/skvark/opencv-python/venv/lib/python3.7/site-packages/numpy/core/include (ver 1.14.5)\n    install path:                python\n\n  Python (for build):            /Users/travis/build/skvark/opencv-python/venv/bin/python\n\n  Java:                          \n    ant:                         NO\n    JNI:                         /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/JavaVM.framework/Headers\n    Java wrappers:               NO\n    Java tests:                  NO\n\n  Install to:                    /Users/travis/build/skvark/opencv-python/_skbuild/macosx-10.9-x86_64-3.7/cmake-install\n-----------------------------------------------------------------\n\n'

**Comment by skvark** [comment]
This is probably related to OpenCV internal implementation. Please open an issue to the OpenCV repository if you think that this is a bug, this repository is just a build toolchain.
