### ISSUE TITLE
mkl==2020.0 breaks loading openH264 library

### ISSUE THREAD

**Issue by JackCaster** [skvark/opencv-python#308]
### Expected behaviour
OpenCV can load `openh264-1.8.0-win64.dll`

### Actual bejaviour
OpenCV cannot load `openh264-1.8.0-win64.dll`

### Steps to reproduce
Create a new conda environment with the following
```
name: test_opencv

channels:
 - defaults

dependencies:
- python
- mkl==2020.0
- numpy
- pip
- pip:
   - opencv-contrib-python
```

and run the following code:

```
import cv2

fourcc = cv2.VideoWriter_fourcc(*'X264')
out = cv2.VideoWriter('output.avi',fourcc, 20.0, (640,480))
```
By conda installing `mkl==2020.0` opencv cannot load `openh264-1.8.0-win64.dll`. The following error appears:
```
...
Failed to load OpenH264 library: openh264-1.8.0-win64.dll
        Please check environment and/or download library: https://github.com/cisco/openh264/releases
...
```
Instead, installing `mkl==2019.*` via conda the openH264 is loaded successfully:
```
...
OpenH264 Video Codec provided by Cisco Systems, Inc.
...
```

- operating system: Windows 10
- architecture (e.g. x86): amd64
- opencv-python version: pip install opencv-contrib-python-4.2.0.34

**Comment by skvark** [comment]
I can't provide support for additional external dependencies which you have installed via conda. By the looks of it this seems to be some packaging / versioning problem related to the ``mkl`` library since the earlier version works.

**Comment by JackCaster** [comment]
I see. I will open the issue in the mkl repository. Thanks anyway!
