### ISSUE TITLE
Problem when installing inside docker image ubuntu:14.04

### ISSUE THREAD

**Issue by cimenx** [skvark/opencv-python#31]
Hi,  I have problem when installing inside docker image
```
root@6296a40bde67:~/SDC2017Round1/src/object_awareness# pip3 install opencv-python
Downloading/unpacking opencv-python
  Could not find any downloads that satisfy the requirement opencv-python
Cleaning up...
No distributions at all found for opencv-python
Storing debug log for failure in /root/.pip/pip.log
```
is it the issue of manylinux or something?

Thanks

**Comment by skvark** [comment]
Your pip version is too old for manylinux wheels. Also you are probably missing ``wheel`` package. 

``pip3 install --upgrade pip``
``pip3 install wheel``

**Comment by cimenx** [comment]
still error
```
pip3 install --upgrade pip && \
        pip3 install --upgrade wheel && \
        pip3 install opencv-python
```
```
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0
e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.4
    Not uninstalling pip at /usr/lib/python3/dist-packages, owned by OS
Successfully installed pip
Cleaning up...
Requirement already up-to-date: wheel in /usr/local/lib/python3.4/dist-packages
Cleaning up...
Downloading/unpacking opencv-python
  Could not find any downloads that satisfy the requirement opencv-python
Cleaning up...
No distributions at all found for opencv-python
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by cachitas** [comment]
Try to `pip install -U setuptools` before also. Recently, I've obersevd that sometimes setuptools and distutils conflict with each other. I believe I saw this with docker...

I got to the point where for every new virtual environement I create, first thing I do is `pip install -U pip setuptools wheel`.

**Comment by skvark** [comment]
Pip 1.5.4 is over 3 years old. Please consider using Python virtual envs. 

This issue is not related to opencv-python. Please ask general Python (package management) questions via Stackoverflow or some other programming community.
