### ISSUE TITLE
Version 4.3.0 not available on pypi

### ISSUE THREAD

**Issue by petoknm** [skvark/opencv-python#316]
When can we expect version 4.3.0 to hit pypi?

![Screenshot_2020-04-09 opencv-python](https://user-images.githubusercontent.com/5087675/78922529-f73eea00-7a96-11ea-8ea4-195be8afa07c.png)

**Comment by skvark** [comment]
There is no official timeline. 4.3.0 cannot be compiled with the current toolchain on Linux because the ``manylinux1`` compiler is too old. 4.3.0 and 3.4.10 will be released once I have completed testing new ``manylinux2014`` builds (builds are working, but they require some testing and checks for dependencies): https://github.com/skvark/opencv-python/issues/309

**Comment by luiscosio** [comment]
Hello @skvark, pretty interested in this as well.

**Comment by GaborSari** [comment]
Same excited, especially for non-patent SIFT.

**Comment by skvark** [comment]
Yeah, it just takes some time since I'm doing this on my free time which is rather limited. I'll have to port the 3.4 branch to ``manylinux2014`` before any releases can be made.

**Comment by smpurkis** [comment]
How update on 4.3.0 release? Has some juicy things in it

**Comment by johnthagen** [comment]
@skvark Anything we can do to help? Testing, etc?

**Comment by skvark** [comment]
Qt5 which has been installed via CentOS package manager does not work properly or there's some config wrong somewhere. Next thing is to try custom Qt5 build to see if the error can be avoided that way. Details are at https://github.com/skvark/opencv-python/issues/309

**Comment by Red-Eyed** [comment]
Regarding manual build, have u look at C++ package managers?
this one is actively contributed https://github.com/microsoft/vcpkg

**Comment by elbruno** [comment]
> 
> 
> Yeah, it just takes some time since I'm doing this on my free time which is rather limited. I'll have to port the 3.4 branch to `manylinux2014` before any releases can be made.

thank you very much for your work !

**Comment by skvark** [comment]
3.4.10 release builds are now in progress. 4.3.0 will come after they are done.

**Comment by johnthagen** [comment]
[4.3.0 released](https://pypi.org/project/opencv-python/4.3.0.36/)!

Thanks @skvark for all of your hard work!

**Comment by skvark** [comment]
macOS builds for Python 3.5 were not uploaded to PyPI due to SSL error. I'll have to check if that can be fixed somehow. However, I think it's not a big issue since 3.5 will be EOL in couple of month anyways.

**Comment by johnthagen** [comment]
> macOS builds for Python 3.5 were not uploaded to PyPI due to SSL error.

My personal opinion is that it would be fine to drop 3.5 at this point. Many packages already dropped lower than 3.6 so that they could use f-strings and variable type annotations (needed for `dataclasses`, etc).
