### ISSUE TITLE
DLL load failed while importing cv2: The specified module could not be found.

### ISSUE THREAD

**Issue by Awais-Ashiq** [skvark/opencv-python#317]
### Expected behaviour

When i install opencv-python using pip it installs succesfully after that

### Actual behaviour

i open jupyter notebook and imported cv2 and it shows this error 
IMPORT ERROR: DLL load failed while importing cv2: The specified module could not be found.

### Steps to reproduce

opencv_python-4.2.0.34-PYTHON38-64 is the version of open cv in python 3.8 64 bit version
![Capture0](https://user-images.githubusercontent.com/62096752/79132260-70a24980-7dc3-11ea-9f5a-a9ee6542c0ea.png)

**Comment by skvark** [comment]
Please read the README: https://github.com/skvark/opencv-python#frequently-asked-questions

**Comment by Awais-Ashiq** [comment]
Thanks i found solution It highly appreciated that your article is 100% help full i am closind this issue thanks again
