### ISSUE TITLE
imshow displagin image RGB order

### ISSUE THREAD

**Issue by azizkazdal** [skvark/opencv-python#324]
hello,
below code showing image on the screen or of RGB. should it be order of BGR ? because imread methods reads the image order of BGR and I expect to see it as BGR order on the screen.

```
import cv2 as cv

image_file = "image/512-1-1000-10-RGB.jpg"
image = cv.imread(image_file)

cv.imshow('sda', image)
cv.waitKey(0)
cv.destroyAllWindows()
```

![image](https://user-images.githubusercontent.com/4470595/80680519-991a8b00-8ac7-11ea-8812-57eb2bcc11c5.png)

original image 

![image](https://user-images.githubusercontent.com/4470595/80680546-a9326a80-8ac7-11ea-94d2-e681e841c0ba.png)

- Windows 10 Pro v64
- opencv-python 4.2.0.34

**Comment by skvark** [comment]
This is ``opencv-python`` build toolchain issue tracker, not a generic Q&A forum. Please ask usage questions in a place which is designed for Q&A, for example: https://answers.opencv.org/questions/
