### ISSUE TITLE
support aarch64 architecture

### ISSUE THREAD

**Issue by xunfeng1980** [skvark/opencv-python#328]
### Expected behaviour

Support aarch64 architecture

### Actual behaviour
Don't support aarch64/arm64  architecture

- operating system 
Linux arm-builder 4.14.105-19-beta3 #1 SMP Wed May 8 11:19:15 CST 2019 aarch64 aarch64 aarch64 GNU/Linux
- architecture 
aarch64
- opencv-python version
4.x

**Comment by skvark** [comment]
ARM support is tracked here: https://github.com/skvark/opencv-python/issues/13

Currently there is no plans to provide aarch64/arm64 packages due to the Python packaging ecosystem's incomplete support for those architectures.

**Comment by AshokBhat** [comment]
Python now supports manylinux2014 standard, which makes it possible to provide AArch64 wheels. For example, the latest version of NumPy now provides the AArch64 wheel (https://pypi.org/project/numpy/1.19.0/#files).  Is there anything specific that you need anything beyond manylinux2014 support?

**Comment by Red-Eyed** [comment]
@AshokBhat wow, it's really cool, didn't know about that.
I think that it needs to configure cross compilation toolchains (compilers).
AFAIK, currently, there is only docker container that uses default CentOS toolchain (which is x86 or amd64)

**Comment by AshokBhat** [comment]
@Red-Eyed There are docker images available for AArch64 (aarch64 image: quay.io/pypa/manylinux2014_aarch64) in addition to x86_64 to build manylinux2014 images.  https://github.com/pypa/manylinux has the details. Are you looking to build the images on a x86_64 host?

**Comment by skvark** [comment]
Docker images are not enough. ARM based hardware is needed to build ARM wheels (or cross compiling, which is something I would not like to implement... also auditwheel works only on ARM HW: https://github.com/pypa/auditwheel/issues/244#issuecomment-640878061). The only CI system which has currently ARM support is https://www.shippable.com/ and so it's a major effort to start supplying ARM wheels for opencv-python and further increases my workload. Please continue discussing about this in the issue which is reserved for ARM based wheels: https://github.com/skvark/opencv-python/issues/13
