### ISSUE TITLE
opencv 3.4.10/ efficientnet/ Yolo v3

### ISSUE THREAD

**Issue by weiwei-liu** [skvark/opencv-python#332]
I am trying to interpret a model with EfficientNet as backbone for Yolo v3 Detector. 

I got this error:
cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:686: error: (-212:Parsing error) Unsupported activation: smish in function 'ReadDarknetFromCfgStream'

The activations and functions like `add grouped convolutions`, `sigmoid`, `swish`, `scale_channels` are also added to opencv and [These feature merged to opencv:3.4](https://github.com/opencv/opencv/pull/16436).

**My Question is:**

How can I `pip install opencv-python` with opencv 3.4.10 instead of opencv 4.2.0?

**Comment by skvark** [comment]
3.4.10 and 4.3.0 releases are currently blocked, for more info:

- https://github.com/skvark/opencv-python/issues/316
- https://github.com/skvark/opencv-python/issues/309
