### ISSUE TITLE
Image file name bug while resizing

### ISSUE THREAD

**Issue by AndrewCalm** [skvark/opencv-python#333]
### Expected behaviour

I'm creating an application that converts images to ASCII characters and at some point in my algorithm, an input image have to be simply resized.

### Actual behaviour

Unfortunately, when I try to scale an image whose file name consists of characters that are not in the English alphabet (such as ą, ż, ć, â), the application crashes and the following message appears in the console:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:/Dokumenty/Projekty Python/artif/main.py", line 183, in convert_to_ascii
    img = cv.resize(self.img, (self.reducedWidth, self.reducedHeight))
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

```

### Steps to reproduce

 #Example code:
```
img = cv.resize(self.img, (self.reducedWidth, self.reducedHeight))

```

#Operating system:
Windows 10 Home version 1809

#Architecture:
x64

#OpenCv version:
4.2.0.34

**Comment by skvark** [comment]
OpenCV supports only a subset of ASCII characters. There's nothing I can do in this repository to fix that "feature". Please open an issue to the actual OpenCV repository: https://github.com/opencv/opencv

**Comment by AndrewCalm** [comment]
All right. Thank you!
