### ISSUE TITLE
Issue using cv2.getStructuringElement

### ISSUE THREAD

**Issue by straumboi** [skvark/opencv-python#337]
### Expected behaviour

Return array of given dimensions

### Actual behaviour

TypeError: an integer is required (got type _NoValueType)

### Steps to reproduce

- cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
- Windows 10
- architecture (e.g. x86)
- opencv-python version

**Comment by skvark** [comment]
Cannot reproduce, please provide full code. This looks like a generic usage question, not an actual issue.

```
>>> import cv2
>>> cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)
```
