### ISSUE TITLE
Headless verion linked against GUI library

### ISSUE THREAD

**Issue by walchko** [skvark/opencv-python#340]
### Expected behaviour

I installed the headless version on a Raspberry Pi and `cv2` crashes because it was linked to a GUI library, libgtk-3 ... seems like an error. I am using the `lite` version with no desktop installed ... doing embedded work.

version: opencv-python-headless 4.1.1.26

```
uname -a
Linux mote 5.4.44-v7+ #1320 SMP Wed Jun 3 16:07:06 BST 2020 armv7l GNU/Linux
```

```
cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

```
python --version
Python 3.7.3
```

### Actual behaviour

Crashed:

```
Traceback (most recent call last):
  File "./cam.py", line 4, in <module>
    import cv2
  File "/home/pi/venv/lib/python3.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libgtk-3.so.0: cannot open shared object file: No such file or directory
```

### Steps to reproduce

Install headless version and try to load `cv2` ... it will crash.

**Comment by skvark** [comment]
This repository does not provide or support ARM based wheels. Report the issue to the PiWheels issue tracker: https://github.com/piwheels/packages/issues
