### ISSUE TITLE
Do the python wheel files from this project include the full functionalities which official OpenCV supplied?

### ISSUE THREAD

**Issue by hongyi-zhao** [skvark/opencv-python#345]
Hi,

[Python wheel of OpenCV is not supported officially for now.](https://github.com/opencv/opencv/issues/17550#issuecomment-643805731) I want to know whether the wheel from this project includes the full functionalities which official OpenCV supplied?

Regards,
HY

**Comment by skvark** [comment]
What do you mean by full functionalities? This project provides 4 different pre-built packages which have been configured with certain settings (have a look at the ``setup.py``, build output or install some of the packages and run ``cv2.getBuildInformation()``). They do not have all functionalities of OpenCV enabled (that would pretty much impossible). If you wish to enable some functionality which is not supported by these packages (such as CUDA), you'll have to compile OpenCV manually.

**Comment by hongyi-zhao** [comment]
Thanks for your explanation. 
In fact, I try to compile OpenCV by myself and find it really has so many optional modules/functionalities which user can customize. Say, for this [problem](https://github.com/KitwareMedical/VTKPythonPackage/issues/48) which I still not figure out.

**Comment by skvark** [comment]
If you need VTK I'm afraid that that VTK wheel won't help you. OpenCV needs VTK development headers / library during build time. With this repository you can do that by adding additional ``WITH_VTK`` flag to the ``python setup.py bdist_wheel`` command. You have install of course for example ``libvtk7-dev`` before that. The resulting wheel will work only on the computer where you built it unless you use ``auditwheel`` to embed the external binary dependencies to it.

**Comment by hongyi-zhao** [comment]
I feel some complicated for the case I'm encountered.

1. According to your above note, the python wheel distribution doesn't include VTK development headers / library which are always needed by the command `python setup.py build_ext`.

2. The non-wheel building method of VTK python wrapper will not be listed out, hence not known by pip, which will may some tools which rely on it failed to initiation/startup, say, mayavi. See [here](https://github.com/enthought/mayavi/issues/927#issuecomment-640605145) for more discussions on this problem. This is why I try to build the VTK python wheel.

3. According to the notes [here](https://github.com/opencv/opencv/issues/17552#issuecomment-643921283), it seems the `CMake's find_package()` method can help the whl file for finding external dependencies.

**Comment by skvark** [comment]
You should first explain what exactly you are trying to do before I can provide better answers.

1. If you mean this package https://github.com/KitwareMedical/VTKPythonPackage, I believe it doesn't include development or other headers. Even if it did, binaries embedded to Python packages (such as ``cv2`` binary in this ``opencv-python`` package) cannot depend on binaries in other Python packages. This is why ``manylinux`` wheels contain always all third party shared library dependencies.

2. If you need ``mayavi``, then you need to build the VTK wheel, because it seems to depend on it. This project, however, can't depend on that package because this package is not a pure Python package but a binary package with direct binary shared library dependencies. You need to install the VTK development package via your distribution tools, and compile this project against it if you need to use VTK through OpenCV (which is a bit of confusing to me if you already have the VTK bindings in use via the VTK wheel package).

3. Yes, you can create a ``CMakelists`` file, execute it during ``setup.py`` build script and search for the required VTK dependencies from the location where the VTK wheel was installed. However, that won't work because of 1.

**Comment by hongyi-zhao** [comment]
>     2\. If you need `mayavi`, then you need to build the VTK wheel, because it seems to depend on it. This project, however, can't depend on that package because this package is not a pure Python package but a binary package with direct binary shared library dependencies. You need to install the VTK development package via your distribution tools, and compile this project against it if you need to use VTK through OpenCV 

To be simple, I want to create a virtualenv based on python 3.8.3 (managed by pyenv) which including the latest git master versions of VTK, OpenCV, mayivi, and so on. 

> (which is a bit of confusing to me if you already have the VTK bindings in use via the VTK wheel package).

I've built the VTK wheel package and installed it into the virtualenv, but as you have seen and pointed out, this method can work for mayavi, but not for OpenCV.

**Comment by skvark** [comment]
So you wish to use these features of OpenCV? https://docs.opencv.org/master/d1/d19/group__viz.html

If so, build the ``opencv-wheel`` like this:

1. Install VTK development packages via your distribution tools (probably apt-get)
2. Clone this repository
3. Set ENABLE_CONTRIB environment variable to 1
4. Add additional Cmake arguments to CMAKE_ARGS environment variable, in this case CMAKE_ARGS="WITH_VTK=ON"
5. Run ``python setup.py bdist_wheel``
6. VTK enabled OpenCV wheels is generated to ``dist`` folder if the build succeeds

If you need the wheel to be portable (installable to any GNU/Linux system), you will need to use ``manylinux`` based Docker image and do the build there and run ``auditwheel repair`` for the wheel.

But if you do not use the OpenCV ``viz`` module, then this issue irrelevant and you can just proceed with ``pip install opencv-python``.

**Comment by hongyi-zhao** [comment]
> So you wish to use these features of OpenCV? https://docs.opencv.org/master/d1/d19/group__viz.html

Yes.

> 
> If so, build the `opencv-python` wheel like this:
> 
>     1. Install VTK development packages via your distribution tools (probably apt-get)

I want to use the VTK git master version compiled for and installed into the python virtualenv environment with the following cmake options:

`$ cmake -DCMAKE_INSTALL_PREFIX=$VIRTUAL_ENV -DCMAKE_INSTALL_RPATH=$VIRTUAL_ENV/lib -DVTK_WRAP_PYTHON=ON ..`
  

> 
>     2. Clone this repository
> 
>     3. Set ENABLE_CONTRIB environment variable to 1
Does this have the equivalent `cmake` arg?
> 
>     4. Add additional Cmake arguments to CMAKE_ARGS environment variable, in this case CMAKE_ARGS="WITH_VTK=ON"

Is this equivalent to `-DWITH_VTK=ON`?

> 
>     5. Run `python setup.py bdist_wheel`
> 
>     6. VTK enabled OpenCV wheels is generated to `dist` folder if the build succeeds
> 
> 
> If you need the wheel to be portable (installable to any GNU/Linux system), you will need to use `manylinux` based Docker image and do the build there and run `auditwheel repair` for the wheel.
> 
> But if you do not use the OpenCV `viz` module, then this issue irrelevant and you can just proceed with `pip install opencv-contrib-python`.

**Comment by skvark** [comment]
> I want to use the VTK git master version compiled for and installed into the python virtualenv environment managed by pyenv with the following cmake options:
> 
> ```
> $ cmake -DCMAKE_INSTALL_PREFIX=$VIRTUAL_ENV -DCMAKE_INSTALL_RPATH=$VIRTUAL_ENV/lib -DVTK_WRAP_PYTHON=ON ..
> $ make -j48
> $ make install
> ```
> 
> Can the above steps ensure the VTK development headers / libraries picked up from the self-comipled VTK instead of the system's one even they have been installed?

No, you'll have to use also ``-DVTK_DIR`` which points to the location of that custom build.

> > ```
> > 2. Clone this repository
> > 
> > 3. Set ENABLE_CONTRIB environment variable to 1
> > ```
> 
> Does this have the equivalent `cmake` arg?

No, it's specific to this repo and how it builds different wheel variants.

> > ```
> > 4. Add additional Cmake arguments to CMAKE_ARGS environment variable, in this case CMAKE_ARGS="WITH_VTK=ON"
> > ```
> 
> Is this equivalent to `-DWITH_VTK=ON`?

Yes it is. And there was a typo in my previous message, `-D` was missing. Full example:

`export ENABLE_CONTRIB=1`
`export CMAKE_ARGS="-DWITH_VTK=ON -DVTK_DIR=path/to/your/custom/location"`

``setup.py`` will pick that up and append to the other Cmake args which are defined in ``setup.py``.

**Comment by hongyi-zhao** [comment]
> export CMAKE_ARGS="-DWITH_VTK=ON -DVTK_DIR=path/to/your/custom/location"

Is `path/to/your/custom/location` the value of `CMAKE_INSTALL_PREFIX`?

Another issue: can I combine the following option into your above options:

`-DOPENCV_EXTRA_MODULES_PATH=path/to/opencv_contrib.git/modules`

where, `path/to/opencv_contrib.git` is the local repo's path for `https://github.com/opencv/opencv_contrib.git`.

**Comment by skvark** [comment]
I don't know what the exact path should be because I have never compiled OpenCV with VTK enabled. You'll need to try by yourself or go ask from some Q&A forum. Most of the things you are asking are not really related to this repository. And yes you can combine any Cmake parameters to the options, including that one.
