### ISSUE TITLE
dnn_superres not present in the latest pypi release.

### ISSUE THREAD

**Issue by TahaAnwar** [skvark/opencv-python#346]
### Expected behaviour

Hi, I can see by checking the changelog here:  https://github.com/opencv/opencv/wiki/ChangeLog
that the dnn_superres module was included in the contrib package in version 4.1.2. But when I install the latest 4.2.0.34 version from here https://pypi.org/project/opencv-contrib-python/ ,  then this module can't be imported 

Error:

ImportError: cannot import name 'dnn_superres'

### Actual behaviour

The import should work fine as this module should be included from version 4.1.2 and above.

### Steps to reproduce

pip install opencv-contrib-python
from cv2 import dnn_superres

**Comment by TahaAnwar** [comment]
Solved: The changelog was for the C++ version, this module is available in 4.3 for python. Btw would be glad if skvark can give an approximate month for 4.3 launch, I read the comments that you're facing some compilation issues. All the best for that.

**Comment by TahaAnwar** [comment]
Closing.

**Comment by skvark** [comment]
As this is an open source project with no official timelines, I can't give any estimates. It depends on my free time.
