### ISSUE TITLE
opencv-contrib-python-nonfree not available for Python 3.8

### ISSUE THREAD

**Issue by GuidoBartoli** [skvark/opencv-python#348]
### Actual behaviour
Installing the `nonfree` version of `opencv-contrib-python` package using `pip` on Python 3.8 gives the following error:
```
ERROR: Could not find a version that satisfies the requirement opencv_contrib_python_nonfree (from versions: none)
ERROR: No matching distribution found for opencv_contrib_python_nonfree
```
The standard `opencv_contrib_python` package (version 4.2.0.34) has already been released for Python 3.8 and works without problems, is an updated version of the `nonfree` package (version 4.1.1.1) planned, too?

Thanks,
Cheers

### Steps to reproduce

- `$ pip install opencv_contrib_python_nonfree`
- Operating System: Linux Mint 20 Beta (based on Ubuntu 20.04)
- Architecture: x86_64
- Python version 3.8.2

**Comment by skvark** [comment]
I don't maintain any non-free versions. See the README for the packages that I provide. Someone else has uploaded them to PyPI. Beware, they can contain modules which are commercial or protected by patents. 

https://github.com/skvark/opencv-python/issues/283

**Comment by skvark** [comment]
This is the guy who has uploaded them there:

@qzchenwl

The guy hasn't reacted to my emails earlier, so I'll hope this ping gets his attention. @qzchenwl, please remove my name from the PyPI package https://pypi.org/project/opencv-python-nonfree/ and related packages as well as any link referring to the this repository.

**Comment by GuidoBartoli** [comment]
Ok, that explains everything. Sorry to have bothered you, but I just followed the link to your repository from [PyPI](https://pypi.org/project/opencv-python-nonfree/), so I hope he/she will remove it, because this can easily happen to other people incidentally install that `nonfree` version.

Thanks,
Have a nice day

**Comment by skvark** [comment]
Yeah, no problem. I'll contact PyPI registry maintainers directly to address this issue if @qzchenwl does not react to this.

**Comment by GuidoBartoli** [comment]
However, I saw that the SIFT patent is [recently expired](https://github.com/skvark/opencv-python/issues/126#issuecomment-601249064) and there are [official plans](https://github.com/opencv/opencv/wiki/GSoC_2020#idea-better-sift-in-the-main-repository) to move it from nonfree to the main repository. I hope it will be then embedded in your handy Python wrapper! :)

**Comment by qzchenwl** [comment]
@skvark The packages were removed.

**Comment by skvark** [comment]
Thank you.

**Comment by mnrce** [comment]
@skvark  Hi, I see that OpenCV 4.4.0 released two days ago, containing [the SIFT algorithm and some other interesting stuff like Yolov4 support](https://github.com/opencv/opencv/wiki/ChangeLog#version440), is there any plan to package it here?

**Comment by skvark** [comment]
Yes, that's the purpose of this repository. Note that SIFT is already in 4.3.0 opencv-contrib-python. In 4.4.0 it will be in opencv-python.
