### ISSUE TITLE
Inconsistency in FFmpeg license statements

### ISSUE THREAD

**Issue by johnthagen** [skvark/opencv-python#349]
The [README states](https://github.com/skvark/opencv-python/blob/master/README.md#licensing):

> All wheels ship with FFmpeg licensed under the LGPLv2.1.

But the LICENSE-3RD-PARTY states:

https://github.com/skvark/opencv-python/blob/3073e9ee37f016144893deeceb127766f55083dc/LICENSE-3RD-PARTY.txt#L83

Which one of these is correct? Is FFmpeg shipped with Linux and macOS wheels? Since it's LGPL, this has ramifications for those using PyInstaller or PyOxidizer to create a built executable.

**Comment by skvark** [comment]
All wheels have FFmpeg.

**Comment by johnthagen** [comment]
@skvark 👍 I have fixed this in https://github.com/skvark/opencv-python/pull/350
