### ISSUE TITLE
Clarify Qt license statements

### ISSUE THREAD

**Issue by johnthagen** [skvark/opencv-python#351]
The [README](https://github.com/skvark/opencv-python/blob/master/README.md#licensing) states:

> Linux wheels ship with Qt 4.8.7 licensed under the LGPLv2.1.
> MacOS wheels ship with Qt 5 licensed under the LGPLv3.

And `LICENSE-3RD-PARTY.txt` state:

https://github.com/skvark/opencv-python/blob/3073e9ee37f016144893deeceb127766f55083dc/LICENSE-3RD-PARTY.txt#L84

https://github.com/skvark/opencv-python/blob/3073e9ee37f016144893deeceb127766f55083dc/LICENSE-3RD-PARTY.txt#L591

I was under the impression that the `-headless` wheels didn't have Qt in them. Should these statements be adjusted to something like: 

"Linux non-headless wheels ship with Qt..."

**Comment by skvark** [comment]
Yeah, headless versions do not have Qt.

**Comment by johnthagen** [comment]
@skvark 👍 Fixed in #350
