### ISSUE TITLE
i cant install 4.2

### ISSUE THREAD

**Issue by hdihd9162** [skvark/opencv-python#357]
### Expected behaviour

i cant install
### Actual behaviour

i cant install

### Steps to reproduce

when i use 
-`pip3 install opencv-python==4.2.0.32`
-for install in raspberry 
-show this eror
 ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.32 (from versions: 3.4.2.16, 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.6.27, 3.4.7.28, 4.0.1.24, 4.1.0.25, 4.1.1.26)
ERROR: No matching distribution found for opencv-python==4.2.0.32

**Comment by skvark** [comment]
Please read the readme, this repository does not provide packages for Raspberry Pi. Report your issue to PiWheels.
