### ISSUE TITLE
Segmentation fault when calling string() of FileNode

### ISSUE THREAD

**Issue by Shershebnev** [skvark/opencv-python#358]
### Expected behaviour

I'm reading an xml file using cv2.FileStorage however when I try to get string value of a node I get segmentation fault. Seems like every opencv-python and opencv-python-headless versions after 3.4.9.33 are affected (so 4.0.0.21 and later) by this

### Actual behaviour

Segmentation fault (core dumped)

### Steps to reproduce

- example code
```
>>> import cv2
>>> cv2.__version__
'4.0.0'
>>> cv2.FileStorage("test.xml", cv2.FILE_STORAGE_READ).getNode("cam_model").string()
Segmentation fault (core dumped)
```
This occurs only when calling string method, i.e. this works fine:
```
>>> import cv2
>>> cv2.__version__
'4.0.0'
>>> cv2.FileStorage("test.xml", cv2.FILE_STORAGE_READ).getNode("cam_model")
<FileNode 0x7fdc7e51f440>
```
Behaviour on 3.4.9.33:
```
>>> import cv2
>>> cv2.__version__
'3.4.9'
>>> cv2.FileStorage("test.xml", cv2.FILE_STORAGE_READ).getNode("cam_model").string()
'opencv-pinhole'
```
Example xml file:
```
<?xml version="1.0"?>
<opencv_storage>
<cam_model>opencv-pinhole</cam_model>
</opencv_storage>
```
- operating system
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
- architecture (e.g. x86)
x86
```
$ uname -a
Linux ip-172-31-8-170 5.3.0-1030-aws #32~18.04.1-Ubuntu SMP Tue Jun 30 23:04:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- opencv-python version
4.0.0.21 and onward seems to be affected. 3.4.9.33 is fine.

**Comment by skvark** [comment]
Probably a bug in OpenCV. I would start by opening an issue to the OpenCV repository: https://github.com/opencv/opencv

I cannot fix OpenCV bugs here, this repository contains just a build toolchain.

**Comment by skvark** [comment]
Might be related: https://github.com/opencv/opencv/issues/17412

**Comment by skvark** [comment]
This occurs also on Windows so I'm quite sure there is a bug in OpenCV and not in the build configuration of this repository.
