### ISSUE TITLE
opencv_python-4.1.1.26-cp37-cp37m-linux_armv7l.whl cannot open shared object file

### ISSUE THREAD

**Issue by ranzhendong** [skvark/opencv-python#363]
### Expected behaviour
- Respberrypi arm7
- python3.7

Use command to install
```shell
pip install opencv_python-4.1.1.26-cp37-cp37m-linux_armv7l.whl
```

Check if all shared libraries exist
```shell
# ldd cv2.cpython-37m-arm-linux-gnueabihf.so |grep "not found"
./cv2.cpython-37m-arm-linux-gnueabihf.so: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by ./cv2.cpython-37m-arm-linux-gnueabihf.so)
./cv2.cpython-37m-arm-linux-gnueabihf.so: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by ./cv2.cpython-37m-arm-linux-gnueabihf.so)
        libIlmImf-2_2.so.23 => not found
        libIex-2_2.so.23 => not found
        libHalf.so.23 => not found
        libIlmThread-2_2.so.23 => not found
        libavcodec.so.58 => not found
        libavformat.so.58 => not found
        libavutil.so.56 => not found
        libswscale.so.5 => not found
```

Find the package corresponding to the shared object file
```shell
ldd cv2.cpython-37m-arm-linux-gnueabihf.so |grep "not found"|grep -v "cv2" |awk '{print " apt-file search " $1}' |sh -x
+ apt-file search libIlmImf-2_2.so.23
+ apt-file search libIex-2_2.so.23
+ apt-file search libHalf.so.23
+ apt-file search libIlmThread-2_2.so.23
+ apt-file search libavcodec.so.58
+ apt-file search libavformat.so.58
+ apt-file search libavutil.so.56
+ apt-file search libswscale.so.5
```

### Actual behaviour

The installation package corresponding to the shared object file cannot be found. The loss of these shared libraries causes an error when using cv2. How can I solve this?

### Steps to reproduce

- example code
- respbian
- architecture (e.g. arm7)
- opencv-python 4.1.1.26

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by skvark** [comment]
Please report the issue to https://github.com/piwheels/packages, this repository does not provide ARM wheels or wheels for Raspberry Pi.

**Comment by ranzhendong** [comment]
> Please report the issue to https://github.com/piwheels/packages, this repository does not provide ARM wheels or wheels for Raspberry Pi.

Thank you very much for your time to solve my problem,  and if I build opencv https://github.com/opencv/opencv on Raspberry Pi, so this problem can be solved? I'm sorry I don't know much about this.

**Comment by skvark** [comment]
Yes, but you should check the dedicated PiWheels pages for help (it has the install guide on top): https://www.piwheels.org/project/opencv-python/

You can also use the guide in the README of this repository to do manual build: https://github.com/skvark/opencv-python#manual-builds (NOTE: it will take 2+ hours on Raspberry Pi).

**Comment by ranzhendong** [comment]
> Yes, but you should check the dedicated PiWheels pages for help (it has the install guide on top): https://www.piwheels.org/project/opencv-python/
> 
> You can also use the guide in the README of this repository to do manual build: https://github.com/skvark/opencv-python#manual-builds (NOTE: it will take 2+ hours on Raspberry Pi).

Thank you very much for your answer. I will try it now
