### ISSUE TITLE
Readme.md / Manual build step 3 mistake use CMAKE_ARGS instead of CMAKE_FLAGS

### ISSUE THREAD

**Issue by bdherouville** [skvark/opencv-python#365]
### Expected behaviour

Add custom Cmake flags if needed, for example: export **CMAKE_ARGS**="-DSOME_FLAG=ON -DSOME_OTHER_FLAG=OFF" (in Windows you need to set environment variables differently depending on Command Line or PowerShell)

### Actual behaviour

Add custom Cmake flags if needed, for example: export _**CMAKE_FLAGS**_="-DSOME_FLAG=ON -DSOME_OTHER_FLAG=OFF" (in Windows you need to set environment variables differently depending on Command Line or PowerShell)

**Comment by skvark** [comment]
Thanks, I'll fix that.

**Comment by skvark** [comment]
Fixed in https://github.com/skvark/opencv-python/commit/914404d62efacd8f3f84444c063555339ee7ef4d
