### ISSUE TITLE
Version 4.3.0.38 does not ship with libGL.so

### ISSUE THREAD

**Issue by Domibor** [skvark/opencv-python#373]
### Expected behaviour

Updating from `4.3.0.36` to `4.3.0.38` should miss system libraries.

### Actual behaviour

Write here what went wrong

### Steps to reproduce

- example code
- operating system
- architecture (e.g. x86)
- opencv-python version

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by skvark** [comment]
See: https://github.com/skvark/opencv-python/issues/370#issuecomment-671202529 

``libGL.so`` is whitelisted by ``auditwheel``. It will not be shipped with the wheels.

**Comment by Yamini-DS** [comment]
<img width="715" alt="GCP error" src="https://user-images.githubusercontent.com/59556681/125634397-557dcee5-7fda-4034-b7fc-ea028d9cd9a9.PNG">
I tried to modify the docker file and made some changes in requirements and still couldn't know how to deploy without this error in GCP and locally it is working good. Please let me know if there are any solutions to it. Thanks.

**Comment by sergregory** [comment]
@Yamini-DS I believe you either should depend on opencv-python-headless instead of opencv-python (if your code is the only place where you have a dependency on opencv-python), or ensure that after all python packages installation steps you install opencv-python-headless (to rewrite the package - a hacky option), or install the required GUI stack to the docker image (probably, will take several hundreds of megabytes)

**Comment by tw-yshuang** [comment]
There is someone who solve this problem:
https://stackoverflow.com/questions/63889102/unable-to-run-docker-image-due-to-libgl-error
