### ISSUE TITLE
Had to revert to version 4.2.0.34 to install it.

### ISSUE THREAD

**Issue by ryanp0342** [skvark/opencv-python#377]
Started getting error codes in multiple programs that ran fine the last time I used them a few weeks ago. Uninstalled opencv-python using PyCharm's interpreter. 

Tried reinstalling the most recent versions in both terminal using pip and in Pycharm but received the error below. I had to revert to opencv-python 4.2.0.34 to get it to work again.

$ pip install opencv-python
Collecting opencv-python
  Using cached https://files.pythonhosted.org/packages/e0/6f/237b730227927c15a68ec831a51bc83837bb65d54bf9651c08b474201b9a/opencv-python-4.4.0.40.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.13.3 in ./venv/lib/python3.6/site-packages (from opencv-python) (1.18.0)
Building wheels for collected packages: opencv-python
  Building wheel for opencv-python (PEP 517) ...

### Steps to reproduce
-Python 3.6 using PyCharm
-Ubuntu 18.04.5 LTS
-Intel® Core™ i5-3570K CPU @ 3.40GHz × 4
-GeForce GTX 1080/PCIe/SSE2
-64-bit

- opencv-python 4.4.0.40 = Didn't work
- opencv-python 4.2.0.34 = GOOD

**Comment by skvark** [comment]
You pip is too old. It does not understand the new ``manylinux2014`` wheels and tries to compile from source. Please upgrade with ``pip install --upgrade pip``. 

See for example: https://github.com/skvark/opencv-python/issues/372
This is also noted in the release notes: https://github.com/skvark/opencv-python/releases

**Comment by ryanp0342** [comment]
Yeah, that was it. Thanks. For some reason even though I updated pip successfully via both PyCharm and Terminal it wasn't working so it took a few tries.
