### ISSUE TITLE
cv2.imshow() different from plt.imshow() when reading a png picture

### ISSUE THREAD

**Issue by vba34520** [skvark/opencv-python#378]
### Expected behaviour

Showing a circle picture with alpha channel.

### Actual behaviour

A picture which was showed before.

### Steps to reproduce

1.png

![result.png](https://i.loli.net/2020/08/18/gnytVMChQEYDqlJ.png)

```python
import cv2
import matplotlib.pyplot as plt

image = cv2.imread('1.png', cv2.IMREAD_UNCHANGED)
cv2.imshow('1', image)
temp = cv2.cvtColor(image, cv2.COLOR_BGRA2RGBA)
plt.imshow(temp)
plt.show()
cv2.waitKey(0)
cv2.destroyAllWindows()
```

![20200818101848575.png](https://i.loli.net/2020/08/18/mhWfCYyP2g8wbtH.png)

- operating system: Windows 7
- opencv-python version: 4.3.0.38

**Comment by skvark** [comment]
Cannot reproduce on Windows 10:

![cannot_reproduce](https://user-images.githubusercontent.com/695340/90610814-a2626b80-e20e-11ea-8a60-015587412090.PNG)

**Windows 7 has been discontinued since January, 2020. Please upgrade to Windows 10.**
