### ISSUE TITLE
Opencv 2.4.13.2 for Python 3.5

### ISSUE THREAD

**Issue by anselal** [skvark/opencv-python#38]
Is there any change you could build a wheel of Opencv 2.4.13.2 for Python 3.5 ?

**Comment by skvark** [comment]
It's not possible, only OpenCV 3.0 and above has support for Python 3. Besides that I'm not going to refactor the buildchain for old releases since the build process is not identical between 2.x and 3.x.

**Comment by anselal** [comment]
Actually, OpenCV 2.4 runs with Python 3. I have it built on a linux virtual machine.
Thanx anyways

**Comment by hntuan94** [comment]
Hi anselal,
How to build OpenCV 2.4 run python 3.5? Could you please guide me a little.
Many thanks

**Comment by anselal** [comment]
@hntuan94 haven't done it for a while..
