### ISSUE TITLE
Hardware Acceleration?

### ISSUE THREAD

**Issue by gusarg81** [skvark/opencv-python#380]
Hi,

CPU Only -> means no HW accel I guess? If the case, is there a way to enable HW accel?

Thanks.

**Comment by skvark** [comment]
These are CPU only packages, no GPU support. Check other build information via ``cv2.getBuildInformation()``. 

As the README says: "Check the manual build section if you wish to compile the bindings from source to enable additional modules such as CUDA."

https://github.com/skvark/opencv-python#manual-builds -> Add the CMAKE_ARGS you need. Probably something like this:

``export CMAKE_ARGS="-DWITH_CUDA=ON -DWITH_CUDNN=ON -DOPENCV_DNN_CUDA=ON -DENABLE_FAST_MATH=ON -DCUDA_FAST_MATH=ON -DWITH_CUBLAS=ON -DCUDA_ARCH_BIN={version here}"``

**Comment by skvark** [comment]
Additionally, to enable hardware specific acceleration features you will need to build OpenCV from sources. It's not simply possible to create universal pre-built packages with all kinds of HW specific acceleration enabled. You will always get the best performance when you compile OpenCV and its dependencies from sources on the machine you are using it.

**Comment by perdakovich** [comment]
@skvark When I have compiled OpenCV with CUDA support, how do I set my code to use the GPU? It's still using only my CPU
