### ISSUE TITLE
Bug in python version of imwrite w/ 16bit JPEG2000 

### ISSUE THREAD

**Issue by benlcb** [skvark/opencv-python#384]
### General Info
This is a bug that was fixed in C++ OpenCV (after version 2.4.6.1) about 5 years ago: 
https://github.com/opencv/opencv/pull/6417/files
https://answers.opencv.org/question/92899/writing-jpeg-2000-images-with-16-bit/

Since opencv-python 4.4.0.42 is build on a much newer version of OpenCV, I don't understand why it still exists now in the python verison. 

### Expected behaviour

`cv2.imwrite(dst_file, pixel_array, [cv2.IMWRITE_JPEG2000_COMPRESSION_X1000, 1000])`
`pixel_array` is a uint16 array. 

The image in pixel_array should be written to a 16-bit JPEG2000 file.

### Actual behaviour

The resulting JPEG2000 image has a bit debth of 8 bit and is completely black.

### Steps to reproduce

Create an image represented in a single-channel uint16 array.
Set Environment Variable `OPENCV_IO_ENABLE_JASPER=True`
Call imwrite like: `cv2.imwrite(dst_file, pixel_array, [cv2.IMWRITE_JPEG2000_COMPRESSION_X1000, 1000])`

opencv-python Version: 4.4.0.42

**Comment by skvark** [comment]
There is no "python version" of OpenCV, Python just calls the C++ code. Open an issue to the OpenCV repository, this repository contains only a build toolchain and I cannot fix OpenCV bugs here.

https://github.com/opencv/opencv/issues
