### ISSUE TITLE
conflict opencv-python and opencv-contrib-python

### ISSUE THREAD

**Issue by dianaK-oss** [skvark/opencv-python#388]
When I install opencv-python==3.4.2.17, after opencv-contrib-pytho==3.4.2.17 is installed, an error occurs:
AttributeError: module 'cv2.cv2' has no attribute 'xfeatures2d'

When I install opencv-python==3.3.0.10, after opencv-contrib-python==3.3.0.10 is installed,
cv2.Videocapture(path_to_video) returns None

If I do it vice versa, there's no such problem. 

If I have a different version of opencv-contrib-python(ex:3.4.2.17) and opencv-python(ex: 4.2.0.34) the problems are the same

**Comment by skvark** [comment]
Did you read the installation guide...?! https://github.com/skvark/opencv-python#installation-and-usage

It literally says in **CAPS LOCK** that you should select only one of the four package variants.

I repeat: install only one package. You don't need multiple packages. In your case `opencv-contrib-python` is enough. It already contains all functionalities of `opencv-python` and in addition the extra modules (such as xfeatures2d).
