### ISSUE TITLE
Can opencv-python under windows OS not depend on QT?

### ISSUE THREAD

**Issue by xichaoqiang** [skvark/opencv-python#389]
Can opencv-python under windows OS not depend on QT?

I tried to install opencv via anaconda, but QT must be installed. Can I choose not to use QT?

**Comment by skvark** [comment]
These packages do not depend on Qt on Windows. I don't understand what you are asking, maybe you should ask the question from the conda repository (https://github.com/conda-forge/opencv-feedstock) if you are using their packages instead of PyPI ones? These are not conda packages.
