### ISSUE TITLE
Python 3 pathlib support  for reading images

### ISSUE THREAD

**Issue by markrowsoft** [skvark/opencv-python#396]
### Expected behaviour

Open image paths of the `PosixPath` and `WIndowsPath` types from `pathlib` and return image array.

### Actual behaviour

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in function imread> returned NULL without setting an error
```

### Steps to reproduce

- example code:
Python version: _Python 3.8.5_ (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27)
```
    import pathlib
    import cv2
    image_filename = pathlib.Path("my_image.png").resolve()
    cv_img_obj = cv2.imread(image_filename, 0)
```
- operating system: MacOS Catalina 10.15.7 (19H2)
- architecture (e.g. x86): x86_64
- opencv-python version:               4.4.0.44

### Work around:
Cast the `WindowsPath` or `PosixPath` to a string.

**Comment by skvark** [comment]
This is a build toolchain and does not contain OpenCV code which means that I cannot modify OpenCV C++ code here. `imread` as well as all other OpenCV functions are implemented in C++.
