### ISSUE TITLE
Cuda Support

### ISSUE THREAD

**Issue by LZY2006** [skvark/opencv-python#398]
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-52oirelq\opencv\modules\core\include\opencv2/core/private.cuda.hpp:106: error: (-216:No CUDA support) The library is compiled without CUDA support in function 'throw_no_cuda'
We need CUDA support!

**Comment by skvark** [comment]
Pre-built wheels with CUDA support will not be added PyPI. However, you can build CUDA-enabled wheels locally by following the manual build instructions in the README. Quick guide:

1. Set Cmake arguments to an environment variable:

`$env:CMAKE_ARGS="-DWITH_CUDA=ON -DWITH_CUDNN=ON -DOPENCV_DNN_CUDA=ON -DENABLE_FAST_MATH=ON -DCUDA_FAST_MATH=ON -DWITH_CUBLAS=ON -DCUDA_ARCH_BIN={version here}"`

2. `pip install --no-binary opencv-python opencv-python`

For more info, please refer to https://github.com/skvark/opencv-python#manual-builds

**Comment by LZY2006** [comment]
Thanks. I have built opencv with source code with cmake and MSVC.

**Comment by AjayNandoriya** [comment]
is there any particular reason for not supporting CUDA build similar to tensorflow or other open source gpu python packages?
