### ISSUE TITLE
cv2 creates too many idle threads

### ISSUE THREAD

**Issue by 0-MegaMind-0** [skvark/opencv-python#399]
```python
import cv2
import sys
import numpy as np
import imutils
from pathlib import Path
import shutil
from torf import Torrent 

def generate_hash(path):
    file = Torrent(path=path)
    file.generate()
    return file.infohash


def detect_blur_fft(image, size=60, thresh=10):
    (h, w) = image.shape
    (cX, cY) = (int(w / 2.0), int(h / 2.0))
    fft = np.fft.fft2(image)
    fftShift = np.fft.fftshift(fft)
    fftShift[cY - size:cY + size, cX - size:cX + size] = 0
    fftShift = np.fft.ifftshift(fftShift)
    recon = np.fft.ifft2(fftShift)
    magnitude = 20 * np.log(np.abs(recon))
    mean = np.mean(magnitude)
    return (mean, mean <= thresh)


def blur_detection(image_files):
    for image_path in list(dict.fromkeys(image_files)):
        orig = cv2.imread(str(image_path))
        orig = imutils.resize(orig, width=500)
        gray = cv2.cvtColor(orig, cv2.COLOR_BGR2GRAY)
        (mean, blurry) = detect_blur_fft(gray, size=60, thresh=15)
        if blurry:
            img_path = Path("screens/blurry") / image_path.name
            shutil.move(str(image_path), img_path)
            print(blurry)
        else:
            img_path = Path("screens/notblurry") / image_path.name
            shutil.move(str(image_path), img_path)
        input("wait for key input before continuing generate hash")
        print(f"generating hash for {str(img_path)}")
        file_hash = generate_hash(img_path)
        print(f"Generated File info Hash : {file_hash}")


if __name__ == '__main__':
    image_folder = Path(sys.argv[1])
    images = list(image_folder.iterdir())
    files = []
    for file in images:
        if file.is_file():
            files.append(file)
    blur_detection(files)
```

### Expected behaviour

Above code I've written is for checking if a image is blurry and it works fine on my two linux machines (running ubuntu server) and a windows machine.
But on another linux machine (Debian GNU/Linux 9.12) the above program creates too many threads which leads a `RuntimeError` when other modules try to start a thread 
i'll attach screenshots below form htop 
```
Traceback (most recent call last):
  File "fft-blurdetector.py", line 63, in <module>
    blur_detection(new_images)
  File "fft-blurdetector.py", line 52, in blur_detection
    file_hash = generate_hash(img_path)
  File "fft-blurdetector.py", line 12, in generate_torrent
    file.generate()
  File "/home2/megamind/.local/lib/python3.8/site-packages/torf/_torrent.py", line 1033, in generate
    hasher_threadpool = generate.HasherPool(threads, reader.piece_queue)
  File "/home2/megamind/.local/lib/python3.8/site-packages/torf/_generate.py", line 562, in __init__
    self._workers = [Worker(f'hasher{i}', self._worker)
  File "/home2/megamind/.local/lib/python3.8/site-packages/torf/_generate.py", line 562, in <listcomp>
    self._workers = [Worker(f'hasher{i}', self._worker)
  File "/home2/megamind/.local/lib/python3.8/site-packages/torf/_generate.py", line 91, in __init__
    self._thread.start()
  File "/home2/megamind/local/bin/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

### Actual behaviour

when `python3.8 fft.py screens` is run this should be the output and this is what i get on the machines that handle this fine
```
True
wait for key input before continuing generate hash
generating hash for screens/blurry/Test-Image.2736.frame.png
0.006024096385542169
1.0
Generated File Hash : 6aafe821b275dd75fb6661cb6c4969b0528737f0
wait for key input before continuing generate hash
generating hash for screens/notblurry/Test-Image.2580.frame.png
0.006535947712418301
1.0
Generated File Hash : 981a6488e823b416820f1a13ec6de04cd6672b22
wait for key input before continuing generate hash
generating hash for screens/notblurry/Test-Image.2685.frame.png
0.005291005291005291
1.0
Generated File Hash : aad435c864b5c3a144d6baa15520bbc55ddc0a3f
True
wait for key input before continuing generate hash
generating hash for screens/blurry/Test-Image.2590.frame.png
0.007874015748031496
1.0
```
### Steps to reproduce

- example code 
- operating system   `Debian GNU/Linux 9.12 (stretch)`
- architecture (e.g. x86)   `x86 `
- opencv-python version    `opencv-python-headless==4.4.0.44`
(the machine that fails has a lot more cores than other machines if that can lead to any issue almost 30 core / 60 threads more)

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

![image](https://user-images.githubusercontent.com/57232930/95049338-81090080-0724-11eb-89ca-c09cca7662fa.png)

![image](https://user-images.githubusercontent.com/57232930/95049497-d04f3100-0724-11eb-89d9-cb15dcd9efd2.png)

**Comment by skvark** [comment]
I'm pretty sure that your issue is not related to this repository or OpenCV in any way. Even if it was, this is not the correct place to report the issue (OpenCV bugs should be reported to the actual OpenCV C++ repository: https://github.com/opencv/opencv). 

Those OpenCV methods which you are using do not use any threading behind the scenes as far as I know. To me it looks like the `torf` library is doing some stuff with threading when computing the torrent piece hashes. There will be thousands of threads if your file is big and the piece size is small: https://github.com/rndusr/torf 

Please check also: https://stackoverflow.com/a/344292/5795428

**Comment by 0-MegaMind-0** [comment]
Thanks for the response
yes torf does create threads but they kill their threads as soon as the function finishes execution 
I have a different version of program where torf is run first and it exists all the threads fine but running cv2 causes torf to never start because of a limitation of how many threads the python program can run. and this happens on just one non root machine i have.
`Those OpenCV methods which you are using do not use any threading behind the scenes as far as I know. `
these threads are created even before the generate_hash() function is called as you can see in the first screenshot.

 `I'm pretty sure that your issue is not related to this repository or OpenCV in any way. Even if it was, this is not the correct place to report the issue (OpenCV bugs should be reported to the actual OpenCV C++ repository: https://github.com/opencv/opencv).`
sorry about this thought it was a issue related to this package 
and searching the issues on opencv did show me a similar issue  from 2015 https://github.com/opencv/opencv/issues/5150 

after a quick looking around setting `cv2.setNumThreads(0)` after the imports lets the `generate_hash()` function execute properly even though it still creates some idle threads. But I tested it with 100+ images and its goes through them without any issue 

Thanks :)
