### ISSUE TITLE
cv2.imshow()

### ISSUE THREAD

**Issue by masoudslipknot** [skvark/opencv-python#40]
is there any way to show the image in this instead of cv2.imshow() ?  you said it has limits for it

**Comment by skvark** [comment]
No, there's not in OpenCV. You can write the image into a file or use for example one of these external libraries to view the images:

- matplotlib
- PIL (pillow)
- scikit-image
- tkinter
- kivy

Those are just examples, there are dozens of different python packages which are able to show images.

**Comment by masoudslipknot** [comment]
thank you for your answer.
