### ISSUE TITLE
Ubuntu 18.04 Support OpenCV-Contrib-python==4.4.0.44

### ISSUE THREAD

**Issue by hfmartinez** [skvark/opencv-python#401]
### Ubuntu support

We currently have OpenCV `` 4.2.0``  installed on an ubuntu server, at this moment we test some functionalities with YoloV4 and OpenCV but on windows, it works with version `` 4.4.0.44`` installed by `` pip3 install opencv -contrib -python == 4.4.0.44 ``  and it has been impossible to install the same version on ubuntu, the error report:

`` Could not find a version that satisfies the requirement opencv-contrib-python == 4.4.0.44 (from versions: 3.2.0.7, 3.2.0.8, 3.3.0.9, 3.3.0.10, 3.3.1.11, 3.4.0.12, 3.4 .0.14, 3.4.1.15, 3.4.2.16, 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.5.20, 3.4.6.27, 3.4.7.28, 3.4.8.29, 3.4.9.31, 3.4.9.33, 4.0.0.21 , 4.0 .1.23, 4.0.1.24, 4.1.0.25, 4.1.1.26, 4.1.2.30, 4.2.0.32, 4.2.0.34)
No matching distribution found for opencv-contrib-python == 4.4.0.44`` 
'
For version `` 4.2.0``  this line is not valid
`` net = cv2.dnn_DetectionModel ("yolov4.cfg", "yolov4.weights") ``
but in `` 4.4.0.44``  it works

I appreciate any help you can give me

**Comment by skvark** [comment]
The issue template is there for a reason... I need more info:

* `pip` version
* Python version
* architecture

**Comment by hfmartinez** [comment]
@skvark reading your message I realized the version of pip and ran an update from version 9.0.1 to version 20.2.3 and it works, thank you very much.
