### ISSUE TITLE
cv2.optflow module not found

### ISSUE THREAD

**Issue by VijayRameshkumar** [skvark/opencv-python#407]
### Expected behaviour

cv2.optflow.DualTVL1OpticalFlow_create()

### Actual behaviour

cv2.optflow module not found

### Steps to reproduce

- cv2.optflow.DualTVL1OpticalFlow_create()
- win10 , conda env
- win10(e.g. x64)
- 4.0.0.21

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by skvark** [comment]
Cannot reproduce:

1. `pip install opencv-contrib-python`
2. 
```
>>> import cv2
>>> cv2.optflow.DualTVL1OpticalFlow_create()
<optflow_DualTVL1OpticalFlow 0000018A18DD84D0>
```
Please read the installation guide https://github.com/skvark/opencv-python#installation-and-usage
