### ISSUE TITLE
Build fails with "Exception: Not found: 'bin/opencv_videoio_ffmpeg\d{3}_64\.dll'"

### ISSUE THREAD

**Issue by rk-exxec** [skvark/opencv-python#409]
### Expected behaviour

Build with no error

### Actual behaviour

Build fails with this error message:
```
Configuring Project
    Working directory:
      C:\Users\user\AppData\Local\Temp\pip-req-build-91625mld\_skbuild\win32-3.8\cmake-build
    Command:
      cmake 'C:\Users\user\AppData\Local\Temp\pip-req-build-91625mld\opencv' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\user\AppData\Local\Temp\pip-req-build-91625mld\_skbuild\win32-3.8\cmake-install' '-DPYTHON_EXECUTABLE:FILEPATH=c:\users\user\appdata\local\programs\python\python38\python.exe' -DPYTHON_VERSION_STRING:STRING=3.8.6 '-DPYTHON_INCLUDE_DIR:PATH=c:\users\user\appdata\local\programs\python\python38\Include' '-DPYTHON_LIBRARY:FILEPATH=c:\users\user\appdata\local\programs\python\python38\libs\python38.lib' -DSKBUILD:BOOL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\user\AppData\Local\Temp\pip-build-env-zyqn77ny\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON3_EXECUTABLE=c:\users\user\appdata\local\programs\python\python38\python.exe' -DPYTHON3_INCLUDE_DIR=c:/users/user/appdata/local/programs/python/python38/Include -DPYTHON3_LIBRARY=c:/users/user/appdata/local/programs/python/python38/libs/python38.lib -DBUILD_opencv_python3=ON -DBUILD_opencv_python2=OFF -DBUILD_opencv_java=OFF -DOPENCV_SKIP_PYTHON_LOADER=ON -DOPENCV_PYTHON3_INSTALL_PATH=python -DINSTALL_CREATE_DISTRIB=ON -DBUILD_opencv_apps=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_DOCS=OFF -DCMAKE_BUILD_TYPE:STRING=Release

  Copying files from CMake output
  Traceback (most recent call last):
    File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-zyqn77ny\overlay\Lib\site-packages\setuptools\build_meta.py", line 216, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-zyqn77ny\overlay\Lib\site-packages\setuptools\build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-zyqn77ny\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-zyqn77ny\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 450, in <module>
      main()
    File "setup.py", line 210, in main
      skbuild.setup(
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-zyqn77ny\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 621, in setup
      _classify_installed_files(cmake_manifest, package_data, package_prefixes,
    File "setup.py", line 363, in _classify_installed_files_override
      raise Exception("Not found: '%s'" % relpath_re)
  Exception: Not found: 'bin/opencv_videoio_ffmpeg\d{3}_64\.dll'
  Building wheel for opencv-python (PEP 517) ... error
  ERROR: Failed building wheel for opencv-python
Failed to build opencv-python
ERROR: Failed to build one or more wheels
Exception information:
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\base_command.py", line 216, in _main
    status = self.run(options, args)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\commands\wheel.py", line 184, in run
    raise CommandError(
pip._internal.exceptions.CommandError: Failed to build one or more wheels
WARNING: You are using pip version 20.2.1; however, version 20.2.4 is available.
You should consider upgrading via the 'c:\users\user\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.
Removed build tracker: 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-tracker-sm5rl8_o'
``` 

### Steps to reproduce

- operating system: Win 10 1909 x 64
- Build: 
    -Python 3.8.6 x 64
    -VS 2019 
components installed:
```
MSVC v142 – VS 2019 C++-x64/x86-Buildtools (v14.27)
Windows 10 SDK (10.0.18362.0)
Just-in-Time-Debugger
C++-Profilerstellungstools (profile creation tools? idk what this is called in english)
C++-CMake-Tools for Windows
MSVC v142 – VS 2019 C++-x64/x86-Buildtools (v14.27)
C++-Clang-Compiler for Windows (10.0.0)
Visual C++ Redist 2015-2019
```

- opencv-python: master branch commit: ed8acbc - fix py39 entry
- steps:
In VS 2019 Developer PowerShell
`git clone https://github.com/skvark/opencv-python.git`
`cd opencv-python`
`pip wheel . `

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by skvark** [comment]
Couldn't replicate the issue. The FFmpeg binary is downloaded during build by CMake. If the binary isn't there, the download might have failed.

```
PS C:\Projects\opencv-python> py -3.8 -m pip wheel .
Processing c:\projects\opencv-python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy>=1.17.3
  Downloading numpy-1.19.3-cp38-cp38-win_amd64.whl (13.3 MB)
     |████████████████████████████████| 13.3 MB 3.3 MB/s
  Saved c:\projects\opencv-python\numpy-1.19.3-cp38-cp38-win_amd64.whl
Skipping numpy, due to already being wheel.
Building wheels for collected packages: opencv-python
  Building wheel for opencv-python (PEP 517) ... done
  Created wheel for opencv-python: filename=opencv_python-4.4.0+ed8acbc-cp38-cp38-win_amd64.whl size=34695656 sha256=acc5dca1c41ce231a6c5f6f9a9b98646efd30e91e201381f0f25462e5518a640
  Stored in directory: c:\users\\appdata\local\pip\cache\wheels\51\0c\64\94c0d0c13b2e66e97db168e57d1221bfff150fb852f27c5939
Successfully built opencv-python
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'C:\Users\\AppData\Local\Programs\Python\Python38\python.exe -m pip install --upgrade pip' command.
PS C:\Projects\opencv-python>
```

**Comment by rk-exxec** [comment]
Can you tell me where the build directory is? Then I can check.
When I run --verbose, I get these lines:  
```
-- FFMPEG: Download: opencv_videoio_ffmpeg.dll
-- FFMPEG: Download: opencv_videoio_ffmpeg_64.dll
-- FFMPEG: Download: ffmpeg_version.cmake
```
Where are these stored?

**Comment by skvark** [comment]
In your output you can see the working directory: C:\Users\user\AppData\Local\Temp\pip-req-build-91625mld\_skbuild\win32-3.8\cmake-build

**Comment by rk-exxec** [comment]
Ok, should I rather ask in the opencv repo then?

**Comment by skvark** [comment]
Before opening an issue there check that the FFmpeg binaries actually exist in the build directory. The FFmpeg binary copying logic is in this repo so if the binaries exist there then there is some issue in `setup.py`.

**Comment by rk-exxec** [comment]
There is this ffmpeg dll:
`C:\Users\user\AppData\Local\Temp\pip-req-build-psnrb0k7\_skbuild\win32-3.8\cmake-build\bin\opencv_videoio_ffmpeg440.dll`

**Comment by skvark** [comment]
I believe the error is that CMake thinks that you are doing a 32-bit build while you are actually building for 64-bit. Check this SO answer: https://stackoverflow.com/a/56086447/5795428 (this is how it's done in CI builds but this won't work for VS 2019: https://github.com/skvark/opencv-python/blob/master/setup.py#L112)

Please note that Scikit-build does not support VS 2019 but you can maybe bypass it via `CMAKE_ARGS` environment variable (check readme). If not, use VS 2017 or 2015.

**Comment by rk-exxec** [comment]
VS 2017 works 👍 
I also tried changing the env:
```python
    ci_cmake_generator = (
        ["-G", "Visual Studio 16 2019", "-A", ("x64" if x64 else "Win32")]
        if os.name == "nt"
        else ["-G", "Unix Makefiles"]
    )
```
But that didn't work.
```
Copying files from CMake output
  creating directory _skbuild\win32-3.8\cmake-install\cv2
  copying _skbuild\win32-3.8\cmake-install\bin\opencv_videoio_ffmpeg440_64.dll -> _skbuild\win32-3.8\cmake-install\cv2\opencv_videoio_ffmpeg440_64.dll
  Traceback (most recent call last):
    File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-u0jhoh2x\overlay\Lib\site-packages\setuptools\build_meta.py", line 216, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-u0jhoh2x\overlay\Lib\site-packages\setuptools\build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-u0jhoh2x\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-u0jhoh2x\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 450, in <module>
      main()
    File "setup.py", line 210, in main
      skbuild.setup(
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-u0jhoh2x\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 621, in setup
      _classify_installed_files(cmake_manifest, package_data, package_prefixes,
    File "setup.py", line 363, in _classify_installed_files_override
      raise Exception("Not found: '%s'" % relpath_re)
  Exception: Not found: 'python/cv2[^/]*\.pyd'
```
Just FYI.
Thank you for helping me with this!

**Comment by skvark** [comment]
Thanks, I hope `scikit-build` will add support for VS 2019 in the future.

**Comment by clement10601** [comment]
> VS 2017 works 👍
> I also tried changing the env:
> 
> ```python
>     ci_cmake_generator = (
>         ["-G", "Visual Studio 16 2019", "-A", ("x64" if x64 else "Win32")]
>         if os.name == "nt"
>         else ["-G", "Unix Makefiles"]
>     )
> ```
> 
> But that didn't work.
> 
> ```
> Copying files from CMake output
>   creating directory _skbuild\win32-3.8\cmake-install\cv2
>   copying _skbuild\win32-3.8\cmake-install\bin\opencv_videoio_ffmpeg440_64.dll -> _skbuild\win32-3.8\cmake-install\cv2\opencv_videoio_ffmpeg440_64.dll
>   Traceback (most recent call last):
>     File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
>       main()
>     File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
>       json_out['return_val'] = hook(**hook_input['kwargs'])
>     File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 204, in build_wheel
>       return _build_backend().build_wheel(wheel_directory, config_settings,
>     File "C:\Users\user\AppData\Local\Temp\pip-build-env-u0jhoh2x\overlay\Lib\site-packages\setuptools\build_meta.py", line 216, in build_wheel
>       return self._build_with_temp_dir(['bdist_wheel'], '.whl',
>     File "C:\Users\user\AppData\Local\Temp\pip-build-env-u0jhoh2x\overlay\Lib\site-packages\setuptools\build_meta.py", line 202, in _build_with_temp_dir
>       self.run_setup()
>     File "C:\Users\user\AppData\Local\Temp\pip-build-env-u0jhoh2x\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
>       super(_BuildMetaLegacyBackend,
>     File "C:\Users\user\AppData\Local\Temp\pip-build-env-u0jhoh2x\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
>       exec(compile(code, __file__, 'exec'), locals())
>     File "setup.py", line 450, in <module>
>       main()
>     File "setup.py", line 210, in main
>       skbuild.setup(
>     File "C:\Users\user\AppData\Local\Temp\pip-build-env-u0jhoh2x\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 621, in setup
>       _classify_installed_files(cmake_manifest, package_data, package_prefixes,
>     File "setup.py", line 363, in _classify_installed_files_override
>       raise Exception("Not found: '%s'" % relpath_re)
>   Exception: Not found: 'python/cv2[^/]*\.pyd'
> ```
> 
> Just FYI.
> Thank you for helping me with this!

Same problem here
I am trying to build with ffmpeg/gstreamer
what kind of change did you make for the regex in rearrange_cmake_output_data dict?

**Comment by rk-exxec** [comment]
>
> Same problem here
> I am trying to build with ffmpeg/gstreamer
> what kind of change did you make for the regex in rearrange_cmake_output_data dict?

Hey,
I didn't change anything in that regex.
I think that compiling from the VS x64 native tools command prompt always works, if that helps.
