### ISSUE TITLE
I can not find opencv-python-master/cv2/version.py

### ISSUE THREAD

**Issue by heartking** [skvark/opencv-python#416]
### Expected behaviour
I build opencv-python from source and run 'python setup.py bdist_wheel' but got error msgs  below

File "setup.py", line 455, in <module>
    main()
  File "setup.py", line 62, in main
    build_contrib, build_headless, is_CI_build
  File "setup.py", line 424, in get_and_set_info
    with open(version_file) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'opencv-python-master/cv2/version.py'

**Comment by skvark** [comment]
Please use `pip . wheel --verbose` as described in the readme. Make sure that `opencv-python-master` is a Git repository. It won't work if you just download the code, you must clone it.

https://github.com/skvark/opencv-python#manual-builds

**Comment by heartking** [comment]
It is work.
Thank you very much
