### ISSUE TITLE
pip runs forever on MacOS Big Sur

### ISSUE THREAD

**Issue by chenchongsong** [skvark/opencv-python#417]
### Expected behaviour

I expect this to build fast. Any suggestion for this? or any way I can use a wheel built already?

### Actual behaviour

After updating my MacOS to 11.0.1, I got stuck at wheels building.
```
pip install opencv-python==4.4.0.44
Collecting opencv-python==4.4.0.44
  Downloading opencv-python-4.4.0.44.tar.gz (88.9 MB)
     |████████████████████████████████| 88.9 MB 57.8 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.17.3 in ./venv/lib/python3.8/site-packages (from opencv-python==4.4.0.44) (1.19.4)
Building wheels for collected packages: opencv-python
  Building wheel for opencv-python (PEP 517) ... -^canceled
ERROR: Operation cancelled by user
```

### Steps to reproduce

- example code `pip install opencv-python==4.4.0.44`
- operating system `MacOS 11.0.1`
- opencv-python `4.4.0.44`

**Comment by chenchongsong** [comment]
My python version is `3.8.2`, thank you so much!

**Comment by skvark** [comment]
Python packaging tools do not support Big Sur yet: https://github.com/pypa/packaging/pull/319

Please wait for the tooling updates (`pip`, `wheel` etc.). If you wish to use `opencv-python` right now on Big Sur, you must build from source and that's going to take some time. It does not take forever, but most likely over 10 minutes depending on your hardware. OpenCV is a heavy C++ project.
