### ISSUE TITLE
structured_light sinusoidal pattern is missing?

### ISSUE THREAD

**Issue by pettaa123** [skvark/opencv-python#42]
Hello, the sinusoidal pattern methods are missing or I cant find them in opencv_contrib-python 3.3.0.9 from
https://pypi.python.org/pypi/opencv-contrib-python

**Comment by skvark** [comment]
I'm not sure if it has been exported to Python side in the C++ code, see: https://github.com/opencv/opencv_contrib/blob/6eb57fea654ca768b039d3059d5d866598664df8/modules/structured_light/src/sinusoidalpattern.cpp.

GrayCodePattern exists in the same module:
````
>>> help(cv2.structured_light)
Help on module cv2.structured_light in cv2:

NAME
    cv2.structured_light

FUNCTIONS
    GrayCodePattern_create(...)
        GrayCodePattern_create(width, height) -> retval
        .   @brief Constructor
        .   @param parameters GrayCodePattern parameters GrayCodePattern::Params: the width and the height of the projector.

DATA
    DECODE_3D_UNDERWORLD = 0
    FAPS = 2
    FTP = 0
    PSP = 1

FILE
    (built-in)
````
You could ask about this at https://github.com/opencv/opencv_contrib/issues.

**Comment by pettaa123** [comment]
https://github.com/opencv/opencv_contrib/issues/1327
