### ISSUE TITLE
unable to open: DLL Failed while opening anaconda(x64bit) PY3.7.6

### ISSUE THREAD

**Issue by gptshubham595** [skvark/opencv-python#425]
WINDOWS 10 

INSTALLED ANACONDA in "c:\ProgramData\Anaconda3"

installed Microsoft VS 2017 comm, 2019 comm

insatll anaconda 64bit pyhton 3.7.6

(Python3.dll and Python37.dll already there)

BUT ON RUNNING ANYTHING I GET THIS ERR

like anaconda-navigator

![image](https://user-images.githubusercontent.com/24877361/101402739-29d90500-38fa-11eb-823b-ebae677ca4bf.png)

like spyder

![image](https://user-images.githubusercontent.com/24877361/101402775-378e8a80-38fa-11eb-8e44-e80c07327e41.png)

paths:

![image](https://user-images.githubusercontent.com/24877361/101402530-dff01f00-38f9-11eb-915f-6368af3484a9.png)

![image](https://user-images.githubusercontent.com/24877361/101402563-ea121d80-38f9-11eb-8a65-f86e860c1701.png)

![image](https://user-images.githubusercontent.com/24877361/101402601-f72f0c80-38f9-11eb-8440-37be2754b2d0.png)

![image](https://user-images.githubusercontent.com/24877361/101402674-1037bd80-38fa-11eb-8eef-8ab490e6eda1.png)

But I can run JUPYTER NOTEBOOK

**Comment by skvark** [comment]
This is not related to this repository in any way. Your error comes from `PyQt5.QtSvg`, not from `opencv-python`.
