### ISSUE TITLE
Cant build dependencies on arch arm (rpi2)

### ISSUE THREAD

**Issue by kanehekili** [skvark/opencv-python#431]
### Expected behaviour

Can't install `pip install opencv-python-headless`on raspberry 2 with latest arch linux. 

### Actual behaviour

while compiling dependencies following errors log is shown:

>   Installing build dependencies ... error
>   ERROR: Command errored out with exit status 1:
>    command: /usr/bin/python /usr/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-wzty0a6w/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake pip 'numpy==1.13.3; python_version=='"'"'3.6'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"'' 'numpy==1.19.3; python_version>='"'"'3.9'"'"''
>        cwd: None
>   Complete output (246 lines):
>   Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
>   Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
>   Ignoring numpy: markers 'python_version == "3.8"' don't match your environment
>   Collecting setuptools
>     Using cached setuptools-51.1.1-py3-none-any.whl (2.0 MB)
>   Collecting wheel
>     Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
>   Collecting scikit-build
>     Using cached scikit_build-0.11.1-py2.py3-none-any.whl (72 kB)
>   Collecting cmake
>     Using cached cmake-3.18.4.post1.tar.gz (28 kB)
>     Installing build dependencies: started
>     Installing build dependencies: finished with status 'done'
>     Getting requirements to build wheel: started
>     Getting requirements to build wheel: finished with status 'done'
>       Preparing wheel metadata: started
>       Preparing wheel metadata: finished with status 'done'
>   Collecting pip
>     Using cached pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
>   Collecting numpy==1.19.3
>     Using cached numpy-1.19.3.zip (7.3 MB)
>     Installing build dependencies: started
>     Installing build dependencies: finished with status 'done'
>     Getting requirements to build wheel: started
>     Getting requirements to build wheel: finished with status 'done'
>       Preparing wheel metadata: started
>       Preparing wheel metadata: still running...
>       Preparing wheel metadata: finished with status 'error'
>       ERROR: Command errored out with exit status 1:
>        command: /usr/bin/python /usr/lib/python3.9/site-packages/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpvdntar_t
>            cwd: /tmp/pip-install-4401hksq/numpy
>       Complete output (212 lines):
>       Running from numpy source directory.
>       setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
>         run_build = parse_setuppy_commands()
>       Processing numpy/random/_bounded_integers.pxd.in
>       Processing numpy/random/mtrand.pyx
>       Processing numpy/random/_pcg64.pyx
>       Processing numpy/random/bit_generator.pyx
>       Processing numpy/random/_sfc64.pyx
>       Processing numpy/random/_common.pyx
>       Processing numpy/random/_bounded_integers.pyx.in
>       Processing numpy/random/_philox.pyx
>       Processing numpy/random/_generator.pyx
>       Processing numpy/random/_mt19937.pyx
>       Cythonizing sources
>       blas_opt_info:
>       blas_mkl_info:
>       customize UnixCCompiler
>         libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
>         NOT AVAILABLE
>   
>       blis_info:
>         libraries blis not found in ['/usr/local/lib', '/usr/lib']
>         NOT AVAILABLE
>   
>       openblas_info:
>         libraries openblas not found in ['/usr/local/lib', '/usr/lib']
>         NOT AVAILABLE
>   
>       atlas_3_10_blas_threads_info:
>       Setting PTATLAS=ATLAS
>         libraries tatlas not found in ['/usr/local/lib', '/usr/lib']
>         NOT AVAILABLE
>   
>       atlas_3_10_blas_info:
>         libraries satlas not found in ['/usr/local/lib', '/usr/lib']
>         NOT AVAILABLE
>   
>       atlas_blas_threads_info:
>       Setting PTATLAS=ATLAS
>         libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib']
>         NOT AVAILABLE
>   
>       atlas_blas_info:
>         libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib']
>         NOT AVAILABLE
>   
>       accelerate_info:
>         NOT AVAILABLE
>   
>       /tmp/pip-install-4401hksq/numpy/numpy/distutils/system_info.py:1914: UserWarning:
>           Optimized (vendor) Blas libraries are not found.
>           Falls back to netlib Blas library which has worse performance.
>           A better performance should be easily gained by switching
>           Blas library.
>         if self._calc_info(blas):
>       blas_info:
>       C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O3 -pipe -fno-plt -fno-semantic-interposition -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O3 -pipe -fno-plt -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O3 -pipe -fno-plt -fPIC
>   
>       creating /tmp/tmpjzlcygu4/tmp
>       creating /tmp/tmpjzlcygu4/tmp/tmpjzlcygu4
>       compile options: '-I/usr/local/include -I/usr/include -c'
>       gcc: /tmp/tmpjzlcygu4/source.c
>         FOUND:
>           libraries = ['blas', 'blas']
>           library_dirs = ['/usr/lib']
>           include_dirs = ['/usr/local/include', '/usr/include']
>   
>         FOUND:
>           define_macros = [('NO_ATLAS_INFO', 1)]
>           libraries = ['blas', 'blas']
>           library_dirs = ['/usr/lib']
>           include_dirs = ['/usr/local/include', '/usr/include']
>   
>       non-existing path in 'numpy/distutils': 'site.cfg'
>       lapack_opt_info:
>       lapack_mkl_info:
>         libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
>         NOT AVAILABLE
>   
>       openblas_lapack_info:
>         libraries openblas not found in ['/usr/local/lib', '/usr/lib']
>         NOT AVAILABLE
>   
>       openblas_clapack_info:
>         libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib']
>         NOT AVAILABLE
>   
>       flame_info:
>         libraries flame not found in ['/usr/local/lib', '/usr/lib']
>         NOT AVAILABLE
>   
>       atlas_3_10_threads_info:
>       Setting PTATLAS=ATLAS
>         libraries lapack_atlas not found in /usr/local/lib
>         libraries tatlas,tatlas not found in /usr/local/lib
>         libraries lapack_atlas not found in /usr/lib
>         libraries tatlas,tatlas not found in /usr/lib
>       <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
>         NOT AVAILABLE
>   
>       atlas_3_10_info:
>         libraries lapack_atlas not found in /usr/local/lib
>         libraries satlas,satlas not found in /usr/local/lib
>         libraries lapack_atlas not found in /usr/lib
>         libraries satlas,satlas not found in /usr/lib
>       <class 'numpy.distutils.system_info.atlas_3_10_info'>
>         NOT AVAILABLE
>   
>       atlas_threads_info:
>       Setting PTATLAS=ATLAS
>         libraries lapack_atlas not found in /usr/local/lib
>         libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
>         libraries lapack_atlas not found in /usr/lib
>         libraries ptf77blas,ptcblas,atlas not found in /usr/lib
>       <class 'numpy.distutils.system_info.atlas_threads_info'>
>         NOT AVAILABLE
>   
>       atlas_info:
>         libraries lapack_atlas not found in /usr/local/lib
>         libraries f77blas,cblas,atlas not found in /usr/local/lib
>         libraries lapack_atlas not found in /usr/lib
>         libraries f77blas,cblas,atlas not found in /usr/lib
>       <class 'numpy.distutils.system_info.atlas_info'>
>         NOT AVAILABLE
>   
>       lapack_info:
>         FOUND:
>           libraries = ['lapack', 'lapack']
>           library_dirs = ['/usr/lib']
>           language = f77
>   
>         FOUND:
>           libraries = ['lapack', 'lapack', 'blas', 'blas']
>           library_dirs = ['/usr/lib']
>           language = f77
>           define_macros = [('NO_ATLAS_INFO', 1)]
>           include_dirs = ['/usr/local/include', '/usr/include']
>   
>       /usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
>         warnings.warn(msg)
>       running dist_info
>       running build_src
>       build_src
>       building py_modules sources
>       creating build
>       creating build/src.linux-armv7l-3.9
>       creating build/src.linux-armv7l-3.9/numpy
>       creating build/src.linux-armv7l-3.9/numpy/distutils
>       building library "npymath" sources
>       Could not locate executable gfortran
>       Could not locate executable f95
>       Could not locate executable ifort
>       Could not locate executable ifc
>       Could not locate executable lf95
>       Could not locate executable pgfortran
>       Could not locate executable nvfortran
>       Could not locate executable f90
>       Could not locate executable f77
>       Could not locate executable fort
>       Could not locate executable efort
>       Could not locate executable efc
>       Could not locate executable g77
>       Could not locate executable g95
>       Could not locate executable pathf95
>       Could not locate executable nagfor
>       don't know how to compile Fortran code on platform 'posix'
>       Traceback (most recent call last):
>         File "/usr/lib/python3.9/site-packages/pep517/_in_process.py", line 280, in <module>
>           main()
>         File "/usr/lib/python3.9/site-packages/pep517/_in_process.py", line 263, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "/usr/lib/python3.9/site-packages/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
>           return hook(metadata_directory, config_settings)
>         File "/tmp/pip-build-env-_8b62nrt/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
>           self.run_setup()
>         File "/tmp/pip-build-env-_8b62nrt/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 248, in run_setup
>           super(_BuildMetaLegacyBackend,
>         File "/tmp/pip-build-env-_8b62nrt/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in run_setup
>           exec(compile(code, __file__, 'exec'), locals())
>         File "setup.py", line 508, in <module>
>           setup_package()
>         File "setup.py", line 500, in setup_package
>           setup(**metadata)
>         File "/tmp/pip-install-4401hksq/numpy/numpy/distutils/core.py", line 169, in setup
>           return old_setup(**new_attr)
>         File "/tmp/pip-build-env-_8b62nrt/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
>           return distutils.core.setup(**attrs)
>         File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
>           dist.run_commands()
>         File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
>           self.run_command(cmd)
>         File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
>           cmd_obj.run()
>         File "/tmp/pip-build-env-_8b62nrt/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 31, in run
>           egg_info.run()
>         File "/tmp/pip-install-4401hksq/numpy/numpy/distutils/command/egg_info.py", line 24, in run
>           self.run_command("build_src")
>         File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
>           self.distribution.run_command(command)
>         File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
>           cmd_obj.run()
>         File "/tmp/pip-install-4401hksq/numpy/numpy/distutils/command/build_src.py", line 144, in run
>           self.build_sources()
>         File "/tmp/pip-install-4401hksq/numpy/numpy/distutils/command/build_src.py", line 155, in build_sources
>           self.build_library_sources(*libname_info)
>         File "/tmp/pip-install-4401hksq/numpy/numpy/distutils/command/build_src.py", line 288, in build_library_sources
>           sources = self.generate_sources(sources, (lib_name, build_info))
>         File "/tmp/pip-install-4401hksq/numpy/numpy/distutils/command/build_src.py", line 378, in generate_sources
>           source = func(extension, build_dir)
>         File "numpy/core/setup.py", line 663, in get_mathlib_info
>           raise RuntimeError("Broken toolchain: cannot link a simple C program")
>       RuntimeError: Broken toolchain: cannot link a simple C program
>       ----------------------------------------
>   ERROR: Command errored out with exit status 1: /usr/bin/python /usr/lib/python3.9/site-packages/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpvdntar_t Check the logs for full command output.
>   ----------------------------------------
> ERROR: Command errored out with exit status 1: /usr/bin/python /usr/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-wzty0a6w/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake pip 'numpy==1.13.3; python_version=='"'"'3.6'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"'' 'numpy==1.19.3; python_version>='"'"'3.9'"'"'' Check the logs for full command output.

### Steps to reproduce
Install arch rpi2 image
pacman -Syu cmake python python-numpy pip
pip install opencv-python-headless

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by skvark** [comment]
There is no pre-built `numpy` or `opencv-python-headless` wheels for Raspberry Pi (arm) + Arch linux combo. You have to install the full development tool package and all possible dependencies to your system. This is indicated by the `numpy` error: 

`RuntimeError: Broken toolchain: cannot link a simple C program`

Probably at least `base-devel` is missing. This issue is out of the scope of this repository. Please refer to your Linux distribution guides on how to build packages from sources.

**Comment by kanehekili** [comment]
Thanks skvark - my mistake. Got mixed up with the device where base-devel was not installed (which I had assumed but not verified..)
