### ISSUE TITLE
compile error in m1 chip with numpy version

### ISSUE THREAD

**Issue by stereo720712** [skvark/opencv-python#433]
### Expected behaviour
Should compile completed

Write here how did you expect the library to function.
 I need to install opencv-python with Tensorflow-macos env

### Actual behaviour
in opencv-python45 source code
pip wheel . --verbose to compile

### Error 
ERROR: Command errored out with exit status 1: /Users/sean/Documents/sysvenv/tf24v/bin/python3 /Users/sean/Documents/sysvenv/tf24v/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/gy/jzs3xnwd1z3203d75y_31nxc0000gn/T/pip-build-env-en64krht/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake pip 'numpy==1.13.3; python_version=='"'"'3.6'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"'' 'numpy==1.19.3; python_version>='"'"'3.9'"'"'' Check the logs for full command output.

it lookalike the bumpy version problem.
But In Tensorflow-macos it it 1.8.5 and python is 3.8
Does anynoe have the same problem?
thanks

**Comment by skvark** [comment]
The m1 `arm` chip is a pretty new thing, `pyproject.toml` hasn't been adjusted for it. There are no macOS `arm` wheels for either `opencv-python` or `numpy` so you need to use the non-native wheels or build from source (see below). Please check: https://github.com/skvark/opencv-python/issues/418#issuecomment-736834743

If you wish to compile from source, see: https://github.com/skvark/opencv-python#source-distributions

The command you need is: `pip install --no-binary :all: opencv-python`

That will compile both `numpy` and `opencv-python` from sources.

Make sure you have the latest `pip` version in use.
