### ISSUE TITLE
Why caffe forward use 'top' name instead of layer name for conv layer?

### ISSUE THREAD

**Issue by wikiwen** [skvark/opencv-python#436]
### Expected behaviour

use `cv_net.forward(["conv1"])` to get output of the first layer.

### Actual behaviour

{error}OpenCV(4.4.0) /tmp/pip-req-build-6amqbhlx/opencv/modules/dnn/src/dnn.cpp:1500: error: (-204:Requested object was not found) Layer with requested id=-1 not found in function 'getLayerData'

When I use `cv_net.forward(["conv_blob1"])`, it works.
I try to run `cv_net.getLayerNames()`, and get all layers name correctly except Convolution layers. It always get conv layers's 'top' name instead of layer name.

 **I'm a little confused why opencv parse most layers use layesr name but use 'top' name for conv layer**.
According to this [issue comment](https://github.com/opencv/opencv/issues/16489#issuecomment-581497338), OpenCV use field "name" for layers names, not "top".

### Steps to reproduce

- example code
```
prototxt_path = ...
model_path = ...
cv_net = cv2.dnn.readNetFromCaffe(prototxt_path, model_path)
data_inputs = ...
cv_net.setInput(data_inputs)
outputs = cv_net.forward(["conv1"])
```
prototxt example:
```
name: "TestModel"
input: "input1"
input_dim: 1
input_dim: 1
input_dim: 28
input_dim: 28
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "input1"
  top: "conv_blob1"
  convolution_param {
    num_output: 16
    bias_term: true
    pad: 0
    kernel_size: 5
    group: 1
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
    dilation: 1
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "conv_blob1"
  top: "relu_blob1"
}
```
- operating system: CentOS Linux release 7.3.1611
- architecture: 64
- opencv-python version: 4.4.0.44

**Comment by skvark** [comment]
This is the `opencv-python` package build toolchain. I do not make OpenCV design decisions here. Please open an issue to the actual OpenCV repository.
