### ISSUE TITLE
It seems that Travis is ignoring also much larger projects so it doesn't look like I could use Travis in the future considering that I run this project mostly alone and I would need most likely millions of "Travis credits" per year to keep the builds running.

### ISSUE THREAD

**Issue by alirezakazemipour** [skvark/opencv-python#442]
It seems that Travis is ignoring also much larger projects so it doesn't look like I could use Travis in the future considering that I run this project mostly alone and I would need most likely millions of "Travis credits" per year to keep the builds running.  

- https://github.com/numpy/numpy/issues/17824
- https://github.com/scipy/scipy/issues/13109

You can find a lot more similar issues via Github search in other repositories. Github Actions, Azure Pipelines and CircleCI are probably worth taking a look at as alternatives.

_Originally posted by @skvark in https://github.com/skvark/opencv-python/issues/422#issuecomment-739433439_

**Comment by skvark** [comment]
?
