### ISSUE TITLE
How to check out the source code for opencv-python 3.4.6.27

### ISSUE THREAD

**Issue by samfux84** [skvark/opencv-python#443]
Hi,

I have a use case that is a bit special. On our HPC cluster I have an OpenCV 3.4.6 with CUDA and dnn module built. Now I would need the corresponding OpenCV-Python built with CUDA support.

I already tried to install the pre-build 3.4.6.27 version from PYPI, but it is not built with CUDA support. Therefore I would like to try building it from source code.

On our cluster, we already provide newer installations of opencv-python (4.x that does not require a separate OpenCV installation), but for a particular user I would still like to try to get the setup with the old version up and running.

Usually I clone a git repo, then check with

git tag -l

the available tags and then checkout the version that I need. For opencv-python I have a hard time understanding the mapping between the available tags and their corresponding versions. Could you please provide me some help in how I can checkout the source code of opencv-python 3.4.6.27? Due to the --recursive option used for git, I cannot download the 3.4.6.27 realease tarball from your github repository as it does not contain the code  for the submodules.

Thank you in advance and best regards

Sam

**Comment by skvark** [comment]
The version of this repository is the last component of the version string. So clone this repo, update submodules and `git checkout 27`. However, the `setup.py` was back then more limited than now so there might be some issues when you try to build it.
