### ISSUE TITLE
module 'cv2.cv2' has no attribute 'face'

### ISSUE THREAD

**Issue by shuq007** [skvark/opencv-python#445]
### Expected behaviour

face is a module of opencv-contrib, when both opencv and opencv-contrib are installed it must work 

### Actual behaviour

when we use "cv2.face.LBPHFaceRecognizer_create()" it is producing error "module 'cv2.cv2' has no attribute 'face'"

### Steps to reproduce
- import cv2
- help(cv2.face) will produce the same error 

Note: Believe that opencv-python and opencv-contrib-python are no more integrated in Release 4.5.1.48 

![Screenshot from 2021-01-26 10-48-29](https://user-images.githubusercontent.com/46248113/105803742-1544ef00-5fc4-11eb-976e-52b7330ad4ad.png)
![Screenshot from 2021-01-26 10-50-30](https://user-images.githubusercontent.com/46248113/105803858-5b01b780-5fc4-11eb-84da-75cbb40cef7e.png)

**Comment by skvark** [comment]
Cannot reproduce, everything seems to work as expected for me. Make sure you have only `opencv-contrib-python` installed. If you  have installed both `opencv-python` and `opencv-contrib-python`, then your environment is inconsistent / broken and might cause the issue. Please refer to the installation guide in the README:  https://github.com/skvark/opencv-python#installation-and-usage
