### ISSUE TITLE
Error with setup.py install_requires?

### ISSUE THREAD

**Issue by leblancfg** [skvark/opencv-python#47]
### Expected behaviour
I can `pip install opencv-python` without a hitch on my dev box, but am running into problems when `setup.py`'s `install_requires` is trying to do it. I'm assuming the issue lies here, perhaps some of you are familiar with the error message?

### Actual behaviour

~~~
Processing dependencies for autocrop==0.1                                      
Searching for opencv-python            
Reading https://pypi.python.org/simple/opencv-python/                          
No local packages or working download links found for opencv-python            
error: Could not find suitable distribution for Requirement.parse('opencv-python')                                                                             
~~~

### Steps to reproduce

- example code
~~~python
setup(install_requires='opencv-python')
~~~

in my package's `setup.py`, when running `python setup.py install`

- operating system
    * Manjaro Linux

- architecture (e.g. x86)
    * x86

- opencv-python version
    * Latest (any)

**Comment by skvark** [comment]
Use ``pip install .`` 

I'm pretty sure that setuptools doesn't support / understand wheel dependencies.

**Comment by leblancfg** [comment]
Ah, that explains it, thanks. Using `pip install .` instead of `python setup.py install` seems clear now, but totally didn't at the time. The joys of Python packaging :smile:
