### ISSUE TITLE
Inconsistent return type from CascadeClassifier.detectMultiScale

### ISSUE THREAD

**Issue by orenht** [skvark/opencv-python#61]
### Expected behaviour

I expected the library to return an empty ndarray when there is no detection.

### Actual behaviour

The library returns a single empty tuple when there is NO detection, and a numpy.ndarray when there are detections.

- operating system : Windows 10
- opencv-python version: 3.3.1

Is this a problem with the package or with the opencv library?

**Comment by skvark** [comment]
The bindings are generated automatically, please report the issue to OpenCV repository https://github.com/opencv/opencv/issues. Also note that the issue might be already fixed in 3.4.0.
