### ISSUE TITLE
"cv2.img_hash_PHash()"

### ISSUE THREAD

**Issue by doublex** [skvark/opencv-python#63]
I have problem to calculate the opencv-contrib "phash()"

```python
import cv2
image = cv2.imread( '/tmp/test.jpg' )
hashcode = cv2.img_hash_PHash( image )
print hashcode
```

Result -> phash-object:
````
<img_hash_PHash 0x7fbc4761d330>
````

Are there any docs?
Thanks a lot!

**Comment by skvark** [comment]
You can get the docs with ``help(cv2.img_hash_PHash)`` or via https://docs.opencv.org/3.4.0/df/d4e/classcv_1_1img__hash_1_1PHash.html. OpenCV usage questions belong to OpenCV Q&A forum: http://answers.opencv.org/questions/
