### ISSUE TITLE
Python 3.4 doesn't install through pip

### ISSUE THREAD

**Issue by drebbe-intrepid** [skvark/opencv-python#66]
```
C:\Users\drebbe>c:\python34\scripts\pip.exe install opencv_python
Collecting opencv-python
  Could not find a version that satisfies the requirement opencv-python (from versions: )
No matching distribution found for opencv-python
```

```
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

Inspecting the cv2.pyd inside opencv_python-3.4.0.12-cp34-cp34m-win32.whl (Used PEiD) looks like it was built with Visual Studio's 2015 compiler/linker whereas Python 3.4 requires Visual Studio 2010.

**Comment by drebbe-intrepid** [comment]
Python 3.5 32-bit works.

**Comment by skvark** [comment]
Try `pip install --upgrade pip` and run pip install `opencv-python` again.

**Comment by drebbe-intrepid** [comment]
Thanks, that worked. Apparently PIP 7.1.2 is too old. Upgrading to 9.0.1 works.
