### ISSUE TITLE
Is it able to provide opencv-python nightly build?

### ISSUE THREAD

**Issue by fengyuentau** [skvark/opencv-python#687]
Hello! I wonder whether we can provide opencv-python nightly builds.

Consider a case like this: patch https://github.com/opencv/opencv/pull/22100 fixed the clip node issue which [allows us to load mobilenet v2 again](https://github.com/opencv/opencv_zoo/issues/55). However, for normal users who install `opencv-python` from pypi, they will have to wait for the release of 4.7.0 which is likely taking months. During this time, they will not be able to use these models with OpenCV.

As we keep fixing and improving OpenCV, such kind of issues will occur constatnly. If we can provide opencv-python nightly builds, then we can kinda address these issues.

**Comment by Shaownak** [comment]
Agreed with you

**Comment by fengyuentau** [comment]
Hello @Shaownak , we now have weekly release: `pip install opencv-python-rolling`. Feel free to have a try!

**Comment by asmorkalov** [comment]
Implemented -rolling packages that are produced weekly and pushed to pypi to projects with --rolling suffix.

**Comment by futurewasfree** [comment]
Seems broken again?
