### ISSUE TITLE
SIFT function

### ISSUE THREAD

**Issue by boblu1234** [skvark/opencv-python#688]
Hi, bros!
anyone can tell me, is there a function called   **cv2.SIFT_Create()**  in cv2? I just used cv2 to capture the SiFT features in a image, but it does not work when I used  **cv2.xfeatures2d.SIFT_create()**, so I found someone using function **cv2.SIFT_Create()**, and It works!

**Comment by asmorkalov** [comment]
SIFT migrated from xfeatures2d (contrib) to features2d as patent expired. `cv2.SIFT_create` should be used to create it.
