### ISSUE TITLE
cv2.imshow("Frame", frame1) doesn't work even if i install OpenCv 3.4 

### ISSUE THREAD

**Issue by UmeshG-24099** [skvark/opencv-python#690]
### Expected behaviour

I am expecting to show ractangular frames around human

### Actual behaviour

It shows me an error like 
```
File "/home/iris/camera1.py", line 40, in video_stream
    cv2.imshow("Frame", frame1);
cv2.error: OpenCV(4.5.1) ../modules/highgui/src/window_gtk.cpp:641: error: (-2:Unspecified error) GTK backend is not available in function 'cvInitSystem' "
```

### Steps to reproduce

- example code 
```
from PIL import Image
import cv2
import numpy as np
import time
from flask import Flask, render_template, Response, stream_with_context, request

time.sleep(0.1)
hog = cv2.HOGDescriptor()
hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())
video = cv2.VideoCapture(0)
app = Flask('__name__')

def video_stream():
    while True:
        print("video_stream worked")
        ret, frame = video.read()
        if not ret:
            break;
        else:
            ret, buffer = cv2.imencode('.jpeg',frame)
            frame = buffer.tobytes()
            yield (b' --frame\r\n' b'Content-type: imgae/jpeg\r\n\r\n' + frame +b'\r\n')
        print ("now we are creating a frame")
        ret,frame0 = video.read()
        flipped = cv2.flip(frame0,flipCode = -1)
        frame1 = cv2.resize(flipped, (640, 480))
        font = cv2.FONT_HERSHEY_SIMPLEX
        gray = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
        boxes, weights = hog.detectMultiScale(frame1, winStride=(8,8) )
        boxes = np.array([[x, y, x + w, y + h] for (x, y, w, h) in boxes])

        for (xA, yA, xB, yB) in boxes:
           cv2.rectangle(frame1, (xA, yA), (xB, yB),(0, 255, 0), 2)
           b=len(boxes)
           cv2.putText(frame1,"peoplecount:"+str(b),(20,50),0,2,(255,0,0),3)
        img = cv2.resize(frame1,(640,480))
        print ("frame is ready")
        cv2.imshow("Frame", frame1);
        key = cv2.waitKey(1) & 0xFF
        if key == ord("q"):
           break


@app.route('/camera')
def camera():
    return render_template('camera.html')


@app.route('/video_feed')
def video_feed():
    return Response(video_stream(), mimetype='multipart/x-mixed-replace; boundary=frame')


app.run(host='0.0.0.0', port='5000', debug=False)
```
------------------------------------------------ Code - End ------------------------------------------------------------

![images](https://user-images.githubusercontent.com/84259283/179181963-6a598596-3ef2-4d6d-ba2c-0a87dd7b9931.jpeg)

- operating system = Raspburry pi
- architecture (e.g. x86) = x86
- opencv-python version = 3.4 

##### Issue submission checklist

 - [ ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
imshow uses X.org ang GTK to manage windows. It looks like X server is not started on your Pi or your app environment is not configured for X session (DISPLAY environment variable, user, etc). It's not OpenCV issue. You can prove it by running any other UI app instead of OpenCV.

**Comment by Mubashir-alam** [comment]
I solved the following error as. 
`cap=cv2.VideoCapture()` I did not define the image/video path or forgot (0) in cv2.VideoCapture(0).
`cap=cv2.VideoCapture(0)`
