### ISSUE TITLE
cv2.ximgproc.niBlackThreshold with sauvola/wolf/nick always returns the default (niblack) image

### ISSUE THREAD

**Issue by tuxcell** [skvark/opencv-python#694]
### Expected behaviour

Each one of the LocalBinarizationMethods should return an image filtered according to the method.
The equivalent C++ code works fine, therefore the issue is with OpenCV-Python..

### Actual behaviour

The output is always the default, niblack.

### Steps to reproduce

- example code
```
import cv2
import numpy as np
import os
import sys
import platform
 
print(sys.version)
print(cv2. __version__)
print(platform.platform())
print(np.__version__)

my_file = "test.png"

img = cv2.imread(my_file, 0)

t_iBlack = cv2.ximgproc.niBlackThreshold(img, 255, cv2.THRESH_BINARY, 7, 0.1 )

t_sauvola = cv2.ximgproc.niBlackThreshold(img, 255, cv2.THRESH_BINARY, 7, 0.1, cv2.ximgproc.BINARIZATION_SAUVOLA )

t_wolf = cv2.ximgproc.niBlackThreshold(img, 255, cv2.THRESH_BINARY, 7, 0.1, cv2.ximgproc.BINARIZATION_WOLF)

t_nick = cv2.ximgproc.niBlackThreshold(img, 255, cv2.THRESH_BINARY, 7, 0.1, cv2.ximgproc.BINARIZATION_NICK)

print(f'{np.all(t_iBlack==t_sauvola)}, {np.all(t_iBlack==t_wolf)}, {np.all(t_iBlack==t_nick)}, {cv2.ximgproc.BINARIZATION_NICK}')
```
- operating system
Windows 10 and 11

- architecture (e.g. x86)
X64

- opencv-python version
OpenCV 4.6.0 and 4.5.5
Python 3.8.13 and 3.10.4

**Comment by tuxcell** [comment]
A workaround is to use the parameter name, therefore there's something wrong with getting the binarization method if the parameter is passed by position. I looked into the source code but I couldn't find the bug.
This works OK:

t_sauvola = cv2.ximgproc.niBlackThreshold(img, 255, cv2.THRESH_BINARY, 7, 0.1, binarizationMethod=cv2.ximgproc.BINARIZATION_SAUVOLA )

t_wolf = cv2.ximgproc.niBlackThreshold(img, 255, cv2.THRESH_BINARY, 7, 0.1, binarizationMethod=cv2.ximgproc.BINARIZATION_WOLF)

t_nick = cv2.ximgproc.niBlackThreshold(img, 255, cv2.THRESH_BINARY, 7, 0.1, binarizationMethod=cv2.ximgproc.BINARIZATION_NICK)

**Comment by asmorkalov** [comment]
Python signature from documentation:
```
  | cv.ximgproc.niBlackThreshold( | _src, maxValue, type, blockSize, k[, _dst[, binarizationMethod[, r]]] | ) -> | _dst
```
https://docs.opencv.org/4.x/df/d2d/group__ximgproc.html#gab042a5032bbb85275f1fd3e04e7c7660
So the original code it the ticket just misplace binarization method as mentioned in the comment. Named parameters is the best solution for issues like this.
