### ISSUE TITLE
cv2.imwrite() issue

### ISSUE THREAD

**Issue by viethoang261** [skvark/opencv-python#703]
I'm trying to use imwrite with change image quality and got an error
here is my code:
`if not cv2.imwrite(save_path, result_image, [cv2.IMWRITE_JPEG_QUALITY,75]):
                    print('imwrite error')`
and here is the error
` imwrite() takes 2 positional arguments but 3 were given`

Anyone can help me to solve this?
ps: the same environment but run in main and it runs normally

**Comment by asmorkalov** [comment]
@viethoang261 What OpenCV version do you use? I just tried OpenCV-Python 4.5.5 on Ubuntu Linux and it works for me well:
```
$ python3
Python 3.6.9 (default, Jun 29 2022, 11:45:57) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2 as cv
>>> lena = cv.imread("lena.jpg")
>>> cv.imwrite("lena_compressed.jpg", lena, [cv.IMWRITE_JPEG_QUALITY,75])
True
>>> quit()
```
lena.jpg: https://github.com/opencv/opencv/blob/4.x/samples/data/lena.jpg
The code above returns true and writes new jpeg to disk. The image looks fine.

**Comment by viethoang261** [comment]
@asmorkalov 
I'm using OpenCV-python 4.6.0.66
but as I mentioned above, I ran it in main normally but when I called it in service, it got an error
that is why I don't understand where the error come from

**Comment by asmorkalov** [comment]
It means that you have yet another instance of OpenCV, e.g. system package, that is imported when the code is executed as a service. Please add `cv.getBuildInformation()` call before OpenCV code to catch it.
