### ISSUE TITLE
Missing CUDA implementation

### ISSUE THREAD

**Issue by JustusW** [skvark/opencv-python#71]
### Expected behaviour

When CUDA capabilities are available on the system cv2.cuda should be usable.

### Actual behaviour

cv2.cuda is not exposed in any way, so duplicating the following cpp code is not possible using opencv-python:
`Ptr<cuda::TemplateMatching> matcher = cuda::createTemplateMatching(CV_8U, CV_TM_SQDIFF);
UMat gpu_haystack, gpu_needle, gpu_result;
haystack = imread("haystack.png", 1);
needle = imread("needle.png", 1);
gpu_haystack.upload(haystack);
gpu_needle.upload(needle);	
matcher->match(gpu_haystack, gpu_needle, gpu_result);`

**Comment by skvark** [comment]
This requires that OpenCV is compiled with CUDA support. There are a few things to consider:

1. CUDA toolkit might be impossible or very hard to install on CentOS 5.
2. If we somehow manage to get CUDA working on all different platforms, there still remains the licensing issue. Can we redistribute CUDA binaries with opencv-python packages?
3. If the redistribution is allowed, does it restrict the commercial usage of the packages?

For now it's better to build OpenCV manually if you need CUDA support.

**Comment by skvark** [comment]
Similar issue at conda-forge for reference: https://github.com/conda-forge/conda-forge.github.io/issues/63

It looks like this is impossible to implement with the current CentOS 5 manylinux containers. In addition, the licensing of CUDA toolkit is a bit unclear.

**Comment by drzraf** [comment]
Could CUDA libraries be loaded dynamically at runtime?

**Comment by skvark** [comment]
No, because the wheel format is self-contained i.e. it includes all the dependencies. CUDA libs could be probably excluded from the wheels. However, the packages would become dependent on arbitrary third party libs. Then everyone would have to install CUDA libs on their computers to get the import working in the first place. Additionally, CUDA can be installed only on systems which have Nvidia GPUs.

I'm going to close this issue since CUDA support will not be added to these packages. You can build OpenCV yourself on a CUDA enabled machine if you wish to have support for it.

**Comment by cipri-tom** [comment]
Thanks for the explanation! 

I was wondering, maybe we can get some inspiration from `tensorflow-gpu` and PyTorch, who distribute wheels that are CUDA-enabled. What do you think?

**Comment by Light--** [comment]
need to run cv2 on gpu.................

**Comment by alsrgv** [comment]
After reading [skbuild docs](https://scikit-build.readthedocs.io/en/latest/usage.html#enabling-parallel-build) I've found a way to make a CUDA-enabled wheel locally:
```
ENABLE_CONTRIB=1 python setup.py bdist_wheel -- \
    -DWITH_CUDA=ON \
    -DENABLE_FAST_MATH=1 \
    -DCUDA_FAST_MATH=1 \
    -DWITH_CUBLAS=1 \
    -DCUDA_ARCH_BIN=7.5 -- \
    -j8
```

It would be nice if this was supported out of the box with say `ENABLE_CUDA=1 CUDA_ARCH_BIN=7.5 python setup.py bdist_wheel`.
