### ISSUE TITLE
[Feature Request] Lower macOS build target to 10.13?

### ISSUE THREAD

**Issue by joeyballentine** [skvark/opencv-python#714]
As you might be aware, OpenCV-python is currently built for a macOS build target of 10.15. This means that anyone on a version below 10.15 will not be able to install the prebuilt wheel and therefore pip will try to compile OpenCV on their machines.

Many macOS users are still on pre-10.15 builds as those are the last to support 32-bit applications. While I cannot personally test running a version built for 10.13, I have successfully built wheels for 10.13 on my fork of opencv-python, and the [wheels pass every test](https://github.com/joeyballentine/opencv-python/runs/7996723485?check_suite_focus=true). 

Therefore, I am wondering if you could lower the build target to support people who are on these older versions still. I have an application that uses OpenCV, and I have received many reports from people that OpenCV fails to install as it attempts to compile locally and fails. [Here is an example issue where that is the case](https://github.com/joeyballentine/chaiNNer/issues/820). This issue is unfixable by me unless I were to start maintaining my own OpenCV builds with that lower build target and uploading them to pypi. I would rather not do this, and I would much rather just use the official package.

Now, if there is a reason for not using a lowered build target, please let me know. But at least based on my attempt, it seems like it should work fine.

**Comment by skvark** [comment]
If I remember correctly, the build target was raised to 10.15 due to some issues with external dependencies on older macOS versions (especially with Qt) and Travis (build time limits) when it was still used instead of Github Actions. Since Qt is not a dependency on macOS anymore and Travis is not used, I see no reason why 10.13 couldn't be used.

**Comment by joeyballentine** [comment]
Well that's great to hear. Any idea how long it would take to get this change released, if it's approved?
