### ISSUE TITLE
Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by pouledodue** [skvark/opencv-python#72]
### Expected behaviour

I expect to be able to do `import cv2` without error

### Actual behaviour

[this](https://stackoverflow.com/questions/48302857/installing-opencv-for-python-2-7-on-a-mac?rq=1) happened

### Steps to reproduce

`pip install opencv-python==3.4.0.12`

- operating system: OSX El Capitan
- opencv-python version: 3.4.0.12

**Comment by skvark** [comment]
Should be fixed in next release. Duplicate of https://github.com/skvark/opencv-python/issues/67.
