### ISSUE TITLE
report a bug about autocomplete

### ISSUE THREAD

**Issue by Juddd** [skvark/opencv-python#721]
I'm in Windows 11. If I use version 4.6.0.66 with Pycharm 2022.1.3, then I cannot use the code autocomplete. I have to install version 4.5.5.64. Hope to fix quickly

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv-python/issues/676

**Comment by adarmawan117** [comment]
Read this : https://youtrack.jetbrains.com/issue/PY-35691/Code-completion-doesnt-work-for-cv2-module#focus=Comments-27-5402199.0-0

And this is the current sollution i have been try : https://youtrack.jetbrains.com/issue/PY-35691/Code-completion-doesnt-work-for-cv2-module#focus=Comments-27-6426279.0-0. And its work

**Comment by zihaomu** [comment]
This problem will occur when the version of opencv-python is higher than `4.5.5`.

This solution works for me: https://stackoverflow.com/a/75054982/14419009.
It works well with `opencv-python+PyCharm`.

**Comment by asmorkalov** [comment]
Fixed in:
- https://github.com/opencv/opencv/pull/20370
- https://github.com/opencv/opencv-python/pull/853
