### ISSUE TITLE
Video stream being cut off one either side.

### ISSUE THREAD

**Issue by zborges** [skvark/opencv-python#724]
### Expected behaviour
Should show full image from VGA. 

### Actual behaviour
Cutting off one side of the image.

#### example code
```python
import cv2

cap = cv2.VideoCapture(1)
ret, frame = self.cap.read()
timestamp = int(time.time())
frame_path = f'static/{timestamp}.jpg'
cv2.imwrite(frame_path, frame, [cv2.IMWRITE_JPEG_QUALITY, 20])

```

#### operating system
- OSX
- Debian
#### architecture
- ARM
#### opencv-python version
- 4.6.0

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
@zackartborges Please provide more details on camera, and your hardware setup. What about other apps for webcam like cheese on Linux? Do they show full frame?

**Comment by asmorkalov** [comment]
Closed as abandoned.
