### ISSUE TITLE
missing DLL error when compiling from source with Gstreamer enabled

### ISSUE THREAD

**Issue by mark-77** [skvark/opencv-python#727]
Good evening to everyone,

I have been trying to wrap my head around an issue which should be supposedly simple to solve. I just can't seem to make opencv-contrib-python to work when compiled from source with Gstreamer enabled. Compilation succeeds and the wheel is correctly generated but when I try to run this simple script in VScode 1.70.2, i get the error below (in Actual behaviour section)

### Code example
```
import numpy as np
import cv2

print(cv2.getBuildInformation())
```

### Expected behaviour

Script should run just fine and print opencv build informations

### Actual behaviour

Script fails with this error message.

Exception has occurred: ImportError
DLL load failed while importing cv2: The specified module could not be found.
  File "C:\Users\marco\Documents\lavoro\tersa\cvoas\python_scripts\build_info.py", line 2, in <module>
    import cv2

I have tried to build opencv-contrib-python without Gstreamer support and it works just fine. There must be some sort of problem with environmental variables I guess..

### Environment

- Windows 10.0.19044 Build 19044
- Virtual environment with Python 3.9.13
- VScode 1.70.2
- Gstreamer v. 1.20.3 installed in D:\gstreamer\1.0\msvc_x86_64
- opencv has been git cloned from this repository

following this guide:
https://galaktyk.medium.com/how-to-build-opencv-with-gstreamer-b11668fa09c

I have set the following environmental variables:

- CMAKE_ARGS="-DWITH_GSTREAMER=ON"
- ENABLE_CONTRIB=1
- GSTREAMER_DIR=D:\gstreamer\1.0\msvc_x86_64

and i have added the following to the path env. variable:

- D:\gstreamer\1.0\msvc_x86_64\bin
- D:\gstreamer\1.0\msvc_x86_64\lib
- D:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0

As you can see from the build recap I have checkout both opencv and opencv-contrib submodules at the tag 4.5.4 but it shows the same problems with other versions. And again if i disable gstreamer in the build, by setting CMAKE_ARGS="-DWITH_GSTREAMER=OFF" it works as expected and doesn't throw the error anymore.

### build recap
```
 -- General configuration for OpenCV 4.5.4 =====================================
  --   Version control:               4.5.4
  --
  --   Extra modules:
  --     Location (extra):            C:/Users/marco/Documents/lavoro/nhazca/custom_opencv/opencv-python/opencv_contrib/modules
  --     Version control (extra):     4.5.4
  --
  --   Platform:
  --     Timestamp:                   2022-09-02T16:46:08Z
  --     Host:                        Windows 10.0.19044 AMD64
  --     CMake:                       3.24.1
  --     CMake generator:             Visual Studio 16 2019
  --     CMake build tool:            C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/MSBuild/Current/Bin/MSBuild.exe
  --     MSVC:                        1928
  --     Configuration:               Debug Release
  --
  --   CPU/HW features:
  --     Baseline:                    SSE SSE2 SSE3
  --       requested:                 SSE3
  --     Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
  --       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
  --       SSE4_1 (15 files):         + SSSE3 SSE4_1
  --       SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
  --       FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
  --       AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
  --       AVX2 (30 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
  --       AVX512_SKX (5 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX
  --
  --   C/C++:
  --     Built as dynamic libs?:      NO
  --     C++ standard:                11
  --     C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe  (ver 19.28.29914.0)
  --     C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP  /MT /O2 /Ob2 /DNDEBUG
  --     C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP  /MTd /Zi /Ob0 /Od /RTC1
  --     C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe
  --     C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP   /MT /O2 /Ob2 /DNDEBUG
  --     C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP /MTd /Zi /Ob0 /Od /RTC1
  --     Linker flags (Release):      /machine:x64  /NODEFAULTLIB:atlthunk.lib /INCREMENTAL:NO  /NODEFAULTLIB:libcmtd.lib /NODEFAULTLIB:libcpmtd.lib /NODEFAULTLIB:msvcrtd.lib
  --     Linker flags (Debug):        /machine:x64  /NODEFAULTLIB:atlthunk.lib /debug /INCREMENTAL  /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:libcpmt.lib /NODEFAULTLIB:msvcrt.lib
  --     ccache:                      NO
  --     Precompiled headers:         YES
  --     Extra dependencies:          wsock32 comctl32 gdi32 ole32 setupapi ws2_32 Iconv::Iconv
  --     3rdparty dependencies:       libprotobuf ade ittnotify libjpeg-turbo libwebp libpng libtiff libopenjp2 IlmImf zlib quirc ippiw ippicv
  --
  --   OpenCV modules:
  --     To be built:                 aruco barcode bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dnn_superres dpm face features2d flann fuzzy gapi hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor mcc ml objdetect optflow phase_unwrapping photo plot python3 quality rapid reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab wechat_qrcode xfeatures2d ximgproc xobjdetect xphoto
  --     Disabled:                    world
  --     Disabled by dependency:      -
  --     Unavailable:                 alphamat cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv freetype hdf java julia matlab ovis python2 sfm ts viz
  --     Applications:                -
  --     Documentation:               NO
  --     Non-free algorithms:         NO
  --
  --   Windows RT support:            NO
  --
  --   GUI:                           WIN32UI
  --     Win32 UI:                    YES
  --     VTK support:                 NO
  --
  --   Media I/O:
  --     ZLib:                        build (ver 1.2.11)
  --     JPEG:                        build-libjpeg-turbo (ver 2.1.0-62)
  --     WEBP:                        build (ver encoder: 0x020f)
  --     PNG:                         build (ver 1.6.37)
  --     TIFF:                        build (ver 42 - 4.2.0)
  --     JPEG 2000:                   build (ver 2.4.0)
  --     OpenEXR:                     build (ver 2.3.0)
  --     HDR:                         YES
  --     SUNRASTER:                   YES
  --     PXM:                         YES
  --     PFM:                         YES
  --
  --   Video I/O:
  --     DC1394:                      NO
  --     FFMPEG:                      YES (prebuilt binaries)
  --       avcodec:                   YES (58.134.100)
  --       avformat:                  YES (58.76.100)
  --       avutil:                    YES (56.70.100)
  --       swscale:                   YES (5.9.100)
  --       avresample:                YES (4.0.0)
  --     GStreamer:                   YES (1.20.3)
  --     DirectShow:                  YES
  --     Media Foundation:            YES
  --       DXVA:                      YES
  --
  --   Parallel framework:            Concurrency
  --
  --   Trace:                         YES (with Intel ITT)
  --
  --   Other third-party libraries:
  --     Intel IPP:                   2020.0.0 Gold [2020.0.0]
  --            at:                   C:/Users/marco/Documents/lavoro/nhazca/custom_opencv/opencv-python/_skbuild/win-amd64-3.9/cmake-build/3rdparty/ippicv/ippicv_win/icv
  --     Intel IPP IW:                sources (2020.0.0)
  --               at:                C:/Users/marco/Documents/lavoro/nhazca/custom_opencv/opencv-python/_skbuild/win-amd64-3.9/cmake-build/3rdparty/ippicv/ippicv_win/iw
  --     Lapack:                      NO
  --     Eigen:                       NO
  --     Custom HAL:                  NO
  --     Protobuf:                    build (3.5.1)
  --
  --   OpenCL:                        YES (NVD3D11)
  --     Include path:                C:/Users/marco/Documents/lavoro/nhazca/custom_opencv/opencv-python/opencv/3rdparty/include/opencl/1.2
  --     Link libraries:              Dynamic load
  --
  --   Python 3:
  --     Interpreter:                 C:/Users/marco/AppData/Local/Programs/Python/Python39/python.exe (ver 3.9.13)
  --     Libraries:                   C:/Users/marco/AppData/Local/Programs/Python/Python39/libs/python39.lib (ver 3.9.13)
  --     numpy:                       C:/Users/marco/AppData/Local/Temp/pip-build-env-qnf0o1tw/overlay/Lib/site-packages/numpy/core/include (ver 1.19.3)
  --     install path:                python/cv2/python-3
  --
  --   Python (for build):            C:/Users/marco/AppData/Local/Programs/Python/Python39/python.exe
  --
  --   Java:
  --     ant:                         NO
  --     JNI:                         C:/Program Files/Java/jdk-17.0.2/include C:/Program Files/Java/jdk-17.0.2/include/win32 C:/Program Files/Java/jdk-17.0.2/include
  --     Java wrappers:               NO
  --     Java tests:                  NO
  --
  --   Install to:                    C:/Users/marco/Documents/lavoro/nhazca/custom_opencv/opencv-python/_skbuild/win-amd64-3.9/cmake-install
```

thanks in advance and let me know if you require further information.

**Comment by McDonnellJoseph** [comment]
Hello, 
I had a similar issue when trying to interface some open-cv functions with Qt. From a quick google search it looks like Gstreamer also uses Qt5.  

A possible solution is creating a new conda or pip environment and installing opencv-python-headless and adding all your other packages including Gstreamer to this new environment. You can then run your code in this new environment.

**Comment by skvark** [comment]
It looks like the build works just fine. The error occurs during runtime when you try to import cv2. 

Open the cv2 binary with Dependencies https://github.com/lucasg/Dependencies to see which DLLs are missing and double-check that they are in your PATH.

**Comment by mark-77** [comment]
Thanks very much to all of you for your swift replys. I do appreciate it.

> A possible solution is creating a new conda or pip environment and installing opencv-python-headless and adding all your other packages including Gstreamer to this new environment. You can then run your code in this new environment.

Joseph, I don't quite understand what you mean. Should I build the headless version of opencv-python with Gstreamer enabled (but then I would loose the functionality related to the gui part like cv2.imshow()) or should I install Gstreamer separately through pip or other methods??

> Open the cv2 binary with Dependencies https://github.com/lucasg/Dependencies to see which DLLs are missing and double-check that they are in your PATH.

Hi skvark! Could you please tell me which binary I should open with Dependecies? I don't see any .exe file in the folder where I built the source code. I have a folder named _skbuild with a folder inside "win-amd64-3.9" and inside this folder there are 3 other folders "cmake-build", "cmake-install", "setuptools". When the build process completes it yields a wheel file that I use with pip to perform the installation. In order to build opencv I issued the command "pip wheel . " inside the top level opencv-python folder. I really don't know what binary are you exactly referring to...

Thanks in advance!

**Comment by skvark** [comment]
> Hi skvark! Could you please tell me which binary I should open with Dependecies? I don't see any .exe file in the folder where I built the source code. I have a folder named _skbuild with a folder inside "win-amd64-3.9" and inside this folder there are 3 other folders "cmake-build", "cmake-install", "setuptools". When the build process completes it yields a wheel file that I use with pip to perform the installation. In order to build opencv I issued the command "pip wheel . " inside the top level opencv-python folder. I really don't know what binary are you exactly referring to...
> 
> Thanks in advance!

The path depends on where you installed opencv-python, but for example, for global Python 3.10 installation it can be found here: `C:\Python310\Lib\site-packages\cv2\cv2.pyd`. It's a Python C extension binary module.

**Comment by asmorkalov** [comment]
@mark-77 Have you resolved the linkage issue? May I close the ticket?

**Comment by mark-77** [comment]
Good morning,

I didn't try the method suggested by skvark (Dependency walker) but I was able to make it work using a different python version (3.6.8). Oddly enough with that version everything works fine and it doesn't complain about missing DLL.
asmorkalov, you can close the ticket if you want. When I ll have a minute I'll try the method suggested by Skvark with python  3.9.13 and in case I'll reopen the issue.
Thanks to everyone!

**Comment by asmorkalov** [comment]
You issue with dll resolution is most probably caused by this change: https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew. You have to follow new guidelines to update python then.

**Comment by ehdrndd** [comment]
I think window OS version is also has dependencies.. I success in 10.0.17 ~ 10.0.19, but 10.0.22 I fail...

check., cmd's command 'ver'

**Comment by mark-77** [comment]
Thank you very much asmorkalov for your precious suggestion!

I just had to add these 3 lines of code to the python file importing cv2 and everything works as expected.

```
import os
gstreamerPath = "D:\\gstreamer\\1.0\\msvc_x86_64\\bin"
os.add_dll_directory(gstreamerPath)
```

cheers!
