### ISSUE TITLE
Failed to build opencv for a specific version of python (3.7)

### ISSUE THREAD

**Issue by LotfiT** [skvark/opencv-python#734]
Hi,
I am trying to install opencv for python3.7 on an ARM 32bit processor (FPGA board). I tried to install it with `python3.7 -m pip install opencv-python`, I updated `pip` but the system failed to build it.

Hence, I tried to build it from scratch following the cross compilation for ARM based Linux systems tutorial [https://docs.opencv.org/4.x/d0/d76/tutorial_arm_crosscompile_with_cmake.html](url) but it was installed for python3.8 (I have two version of python installed).

Is there any parameter to specify that I need opencv to be installed for python3.7?

Any suggestions would be appreciated. 

Thank you

**Comment by arif-pens77** [comment]
> Hi, I am trying to install opencv for python3.7 on an ARM 32bit processor (FPGA board). I tried to install it with `python3.7 -m pip install opencv-python`, I updated `pip` but the system failed to build it.
> 
> Hence, I tried to build it from scratch following the cross compilation for ARM based Linux systems tutorial [https://docs.opencv.org/4.x/d0/d76/tutorial_arm_crosscompile_with_cmake.html](url) but it was installed for python3.8 (I have two version of python installed).
> 
> Is there any parameter to specify that I need opencv to be installed for python3.7?
> 
> Any suggestions would be appreciated.
> 
> Thank you

I successfully install opencv for python3.7 on armv7l. 
Try the following instruction:
1. Download the opencv whl file:
wget https://www.piwheels.org/simple/opencv-python/opencv_python-4.6.0.66-cp37-cp37m-linux_armv7l.whl#sha256=70e5f777be8b2027e6667f840e64db82255461085eb7b81b5052416925ed3038

2. Install the opencv whl file
sudo pip install opencv_python-4.6.0.66-cp37-cp37m-linux_armv7l.whl

4. Install dependencies packages
sudo apt install libgraphite2-3 libatspi2.0-0 libthai0 libxcb-shm0 libxcb-render0 libswscale5 librsvg2-2 libvorbisenc2 libx264-155 libavutil56 libzvbi0 libgsm1 libxinerama1 libtiff5 libxvidcore4 libjbig0 libswresample3 libgdk-pixbuf2.0-0 libatk1.0-0 libvorbisfile3 libogg0 libpangoft2-1.0-0 libwayland-egl1 libharfbuzz0b libpango-1.0-0 libcairo2 libva-x11-2 libwayland-cursor0 libgfortran5 libxfixes3 libgme0 libxrender1 libvorbis0a libwebp6 libxi6 libspeex1 libwebpmux3 libdatrie1 libatk-bridge2.0-0 libxrandr2 libbluray2 libwavpack1 libxcomposite1 libpangocairo-1.0-0 libsoxr0 libshine3 libcroco3 libxkbcommon0 libvdpau1 libgtk-3-0 libopus0 libfontconfig1 libavformat58 libmpg123-0 libxdamage1 libopenmpt0 libatlas3-base libva2 libva-drm2 libxcursor1 libssh-gcrypt-4 libavcodec58 libaom0 libwayland-client0 libcairo-gobject2 libpixman-1-0 libdrm2 libsnappy1v5 libopenjp2-7 libtheora0 libtwolame0 libepoxy0 libchromaprint1 libmp3lame0 libjpeg62

5. Install opencv-python (Its only give you information that your previous installation are sufficient)
sudo pip install opencv-python==4.6.0.66

6. Check your openCV version in python:
import cv2
cv2.__version__

**Comment by asmorkalov** [comment]
In case if you have more than one version of python you can set CMake option `PYTHON3_EXECUTABLE` with path to particular python executable. It detects all pythonic dependencies relatively to python interpreter.
