### ISSUE TITLE
Segmentation fault when using aruco.DetectorParameters

### ISSUE THREAD

**Issue by prensing** [skvark/opencv-python#735]
### Expected behaviour

I am not sure if I am just doing something wrong, but I definitely don't expect a seg fault.

I have install opencv-contrib-python version 4.6.0.66 from the pip wheel. I then try this:
```
$ python3 -c 'import cv2; x = cv2.aruco.DetectorParameters(); x.aprilTagQuadDecimate = 2.0'
Segmentation fault (core dumped)
```

This is in Linux Mint 21. 
python 3.10

### Actual behaviour
```
$ python3 -c 'import cv2; x = cv2.aruco.DetectorParameters(); x.aprilTagQuadDecimate = 2.0'
Segmentation fault (core dumped)
```

### Steps to reproduce

OS: LInux 64-bit, Linux Mint
Python 3.10 
opencv-contrib-python installed from PyPi

Any access to fields in DetectorParameters seems to cause this crash.

##### Issue submission checklist

 - [ x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ x] I'm using the latest version of ``opencv-python``

**Comment by AleksandrPanov** [comment]
@prensing, use static create method: `x = cv2.aruco.DetectorParameters_create()`
this will fix your problem

**Comment by prensing** [comment]
Thanks. That does seem to fix the problem. May I suggest that you add a bit to the documentation? At least from Python, there is no way to tell that the "constructor" does not actually produce a valid instance. 

Thanks for the support!!
