### ISSUE TITLE
Pipenv Install unable to install opencv-python

### ISSUE THREAD

**Issue by ZWMiller** [skvark/opencv-python#737]
### Expected behaviour

My Pipfile is here: 

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
opencv-python = "*"


[dev-packages]

[requires]
python_version = "3.10"
```

If I run `pipenv shell`, I successfully create a virtual env. When I then run `pipenv install` I expect that pipenv will create a Pipfile.lock and install opencv-python alongside all dependencies.

### Actual behaviour

Running `pipenv install --verbose` generates:

```
:~/tester_dir$ pipenv install --verbose
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
Reporter.starting()
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting()
Reporter.adding_requirement(SpecifierRequirement('opencv-python'), None)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('opencv-python'), None)
✘ Locking Failed! 
```

with a failure to install

### Steps to reproduce

Pipfile above is shown, using python3.10 installed with:

```
sudo apt-get -y install python3.10 python3.10-distutils python3.10-dev
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3.10 get-pip.py && rm get-pip.py
```

As of yesterday (10/11/2022), this was not failing. Starting today, it began failing to build. All other packages that were being installed continue to function. 

Using a `pip install opencv-python` works correctly if I am outside of pipenv, so there seems to be some issue specifically between `opencv-python` and `pipenv` that started in the last 24 hours.

**Comment by ZWMiller** [comment]
Additional context - if I set the Pipfile to have:

```
[packages]
opencv-python = "<=4.4" 
```

And run with `pipenv install --skip-lock` to try to rule out problems with the newest version/the locking, I still have an installation failure, but with additional information:

```
Installing dependencies from Pipfile...
An error occurred while installing opencv-python<=4.4! Will try again.
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Collecting opencv-python<=4.4
[pipenv.exceptions.InstallError]:   Using cached opencv-python-4.3.0.38.tar.gz (88.0 MB)
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'error'
[pipenv.exceptions.InstallError]: error: subprocess-exited-with-error
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   × python setup.py egg_info did not run successfully.
[pipenv.exceptions.InstallError]:   │ exit code: 1
[pipenv.exceptions.InstallError]:   ╰─> [6 lines of output]
[pipenv.exceptions.InstallError]:       Traceback (most recent call last):
[pipenv.exceptions.InstallError]:         File "<string>", line 2, in <module>
[pipenv.exceptions.InstallError]:         File "<pip-setuptools-caller>", line 34, in <module>
[pipenv.exceptions.InstallError]:         File "/tmp/pip-install-n2kra2_i/opencv-python_6d67ad0c720447209841a47f6b0fe389/setup.py", line 9, in <module>
[pipenv.exceptions.InstallError]:           import skbuild
[pipenv.exceptions.InstallError]:       ModuleNotFoundError: No module named 'skbuild'
[pipenv.exceptions.InstallError]:       [end of output]
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
[pipenv.exceptions.InstallError]: error: metadata-generation-failed
[pipenv.exceptions.InstallError]: 
[pipenv.exceptions.InstallError]: × Encountered error while generating package metadata.
[pipenv.exceptions.InstallError]: ╰─> See above for output.
[pipenv.exceptions.InstallError]: 
[pipenv.exceptions.InstallError]: note: This is an issue with the package mentioned above, not pip.
[pipenv.exceptions.InstallError]: hint: See above for details.
ERROR: Couldn't install package: [Requirement(_name='opencv-python', vcs=None, req=NamedRequirement(name='opencv-python', version='<= 4.4', req=Requirement.parse('opencv-python<=4.4'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=opencv-python, path=None, uri=None, extras=(), markers=None, vcs=None, specifier=<=4.4, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=opencv-python<=4.4)>), markers=None, _specifiers='<=4.4', index=None, editable=False, hashes=frozenset(), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=opencv-python, path=None, uri=None, extras=(), markers=None, vcs=None, specifier=<=4.4, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=opencv-python<=4.4)>, _ireq=None)]
 Package installation failed...
```

**Comment by asmorkalov** [comment]
`ModuleNotFoundError: No module named 'skbuild'`. You need to install it beforehand.

**Comment by skvark** [comment]
For some reason, `pipenv` does not seem to honor the `pyproject.toml` that defines the build requirements since you seem to be building `opencv-python` from sources. This is usually caused by too old `pip` as explained in the FAQ:

> Q: Pip install fails with ModuleNotFoundError: No module named 'skbuild'?
> 
> Since opencv-python version 4.3.0.*, manylinux1 wheels were replaced by manylinux2014 wheels. If your pip is too old, it will try to use the new source distribution introduced in 4.3.0.38 to manually build OpenCV because it does not know how to install manylinux2014 wheels. However, source build will also fail because of too old pip because it does not understand build dependencies in pyproject.toml. To use the new manylinux2014 pre-built wheels (or to build from source), your pip version must be >= 19.3. Please upgrade pip with pip install --upgrade pip.

Please double-check your environment, unless you are explicitly trying to build `opencv-python` from the sources.

**Comment by ZWMiller** [comment]
Hi there. Thanks for getting back to me. 

I had started to type up a bunch of questions on this, as my pip is a new version 22.2.2 and the dependency management should take care of skbuild - but then I reran the EXACT same code from yesterday in the EXACT same environment - and it just installed perfectly with no fanfare. 

I have no idea why it was breaking yesterday, but it seems to be back to normal today - including resolving the need for skbuild and installing it correctly. Apologies for the unneeded issue. I wish I knew what happened, but I'm just going to thank the python gods and move on. Cheers.
