### ISSUE TITLE
ImportError: OpenCV loader: missing configuration file: ['config-3.9.py', 'config-3.py']. Check OpenCV installation.

### ISSUE THREAD

**Issue by ghost** [skvark/opencv-python#739]
When I importing OpenCV in anywhere with Anaconda on my server it didn't imports, it gives 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/site-packages/cv2/__init__.py", line 112, in bootstrap
    load_first_config([
  File "/usr/local/lib/python3.8/site-packages/cv2/__init__.py", line 109, in load_first_config
    raise ImportError('OpenCV loader: missing configuration file: {}. Check OpenCV installation.'.format(fnames))
ImportError: OpenCV loader: missing configuration file: ['config-3.9.py', 'config-3.py']. Check OpenCV installation. 

I worked only on virtual environment and conda environment. Because i was worried that something might go wrong. And now OpenCV is not working in my any environment or base of anaconda. It worked 1.5 months ago, and run successfully PGGaN code in this repo: https://github.com/tkarras/progressive_growing_of_gans 
It uses OpenCV too. But now i can't run that too. I didn't touched this repo's environment. I worked on other environment.

My operating system: Ubuntu 20.04.5 LTS
OS Type 64-Bit
OpenCV-Version: 4.6.0.66

Somebody's systems gives that error after using pyinstaller but i have never used it in my work. So these things didn't solved my problem (https://github.com/opencv/opencv-python/issues/569)

I want only run the YOLO V7 in this repo: https://github.com/WongKinYiu/yolov7 I created virtual environment in conda environment for that before making all of these process.

Thanks for helping.

**Comment by alalek** [comment]
> /usr/local/lib/python3.8/site-packages/

How do you manage this location?
Look like it hijacks your virtual/conda environment.

**Comment by ghost** [comment]
I solved the problem with checking .bashrc. PYTHONPATH is described wrong (it described Python 3.8's site-packages path), when i uncommented, it works correctly. Thanks for advice @alalek .
