### ISSUE TITLE
VideoCapture() takes no arguments

### ISSUE THREAD

**Issue by hamdimina** [skvark/opencv-python#743]
```
import cv2

cap=cv2.VideoCapture("video/elyza.mp4")


i=0
while(cap.isOpened()):
    flag,frame=cap.read()
    if flag==False:
        break
    cv2.imwrite('elyza'+str(i)+'.jpg',frame)
    i+=1

cap.release()
cv2.destroyALLWindows()
```
**### #But i get this problem**

File "C:\Users\achre\PycharmProjects\OpenCVExamples\main.py", line 3, in <module>
    cap=cv2.VideoCapture("video/elyza.mp4")
TypeError: VideoCapture() takes no arguments

**Comment by HirunaVishwamith** [comment]
Put the video that you want to open in the same folder that the python files located at. If you using an IDE make sure that your current working directory is your project folder then run this code.

```import cv2

cap=cv2.VideoCapture("gg.mkv")

i=0
while(cap.isOpened()):
    flag,frame=cap.read()
    if flag==False:
        break
    cv2.imwrite('elyza'+str(i)+'.jpg',frame)
    i+=1

cap.release()
cv2.destroyALLWindows()
```
hear "gg.mkv" is the file name of the video file.

![image_2022-11-10_234104737](https://user-images.githubusercontent.com/69134587/201173790-9ae5a4cd-5a0e-4936-aad0-4561a7d71c7d.png)

**Comment by Maaitrayo** [comment]
Try to use the entire path of the video file and not the relative path. it should be like... <Drive_name>/<folder_1>/<folder_2>/.../<video.mp4>

**Comment by asmorkalov** [comment]
Please ensure that you use proper OpenCv version with cv2.getBuildInformation() call. See https://docs.opencv.org/4.x/db/de0/group__core__utils.html#ga0ae377100bc03ce22322926bba7fdbb5
