### ISSUE TITLE
Error when importing opencv version 4.6.0.66

### ISSUE THREAD

**Issue by WillRocha-GuiHub** [skvark/opencv-python#745]
### Expected behaviour

Library options not showing.

### Steps to reproduce

- Image print below 
- Windows 11
- architecture (64 bits)
- opencv-python version: 4.6.0.66
![Sem título](https://user-images.githubusercontent.com/99710787/201479518-2091c456-e8b3-4b8f-87c9-f0acb2fa9144.png)

**Comment by Indekkusu545** [comment]
#676

**Comment by WillRocha-GuiHub** [comment]
Sorted out. Thank you very Much!
