### ISSUE TITLE
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

### ISSUE THREAD

**Issue by aruiplex** [skvark/opencv-python#749]
### Expected behaviour

`cv2` could be successfully imported.

### Actual behaviour

After I install the `opencv-python` or `opencv-python-headless`, I import `cv2`, it will raise a exception:

`AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)`

### Steps to reproduce

OS: ubuntu22.04 in docker.
opencv-version:  4.6.0.66

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)

P.S.: I can solve this issue using the [answer](https://stackoverflow.com/questions/72706073/attributeerror-partially-initialized-module-cv2-has-no-attribute-gapi-wip-gs). I use the version `4.5.5.62`, everything will be ok. However, that is the problem, I do not know why the new version will cause the error.

Thank you.

**Comment by asmorkalov** [comment]
Most probably you faced the same issue as here: https://github.com/opencv/opencv/issues/23177
The most probable reason: multiple OpenCV instances installed on your system.

**Comment by asmorkalov** [comment]
Closed as related OpenCV ticket has been resolved.
