### ISSUE TITLE
Charuco marker pose estimation -> Z-axis in wrong direction 

### ISSUE THREAD

**Issue by Patricks15** [skvark/opencv-python#755]
Hello,
I would like to determine the pose of my board. 
I used all provided functions from the library (opencv in python)

### Actual behaviour

I was able to detect the marker + id and the corners correctly.
But when I use the function `cv2.aruco.estimatePoseCharucoBoard(...)` it returns me not the correct pose ( in my understanding).
I would have expected, that the z-axis will point to the camera and the board is placed in the x-y plane.
By drawing the pose of the complete board and also the poses of the single markers I was able to visualize the mistake.
Code and image results are attached.

### Steps to reproduce
OpenCV => opencv-contrib-python 4.5.5.64
Env: Python 3.8

Here my code:

```
import numpy as np
import cv2
from cv2 import aruco
from PIL import Image

file = "img_left.png"
img = Image.open(file) 
np_img = np.array(img)
np_img_3c = np.stack([np_img, np_img, np_img], axis=-1)
np_img_result = np.copy(np_img_3c)

"setup"
arucoDict = aruco.Dictionary_get(aruco.DICT_6X6_250)
arucoParams = aruco.DetectorParameters_create()

"create the charuco board"
calibration_board = aruco.CharucoBoard_create(squaresX=5, squaresY=7, squareLength=0.072, markerLength=0.062, dictionary=arucoDict)
img_board = calibration_board.draw((200*3,200*3))
cv2.imwrite('sample_board.png',img_board)


"camera parameters"
fx = 1632.677490234375 
fy = 1632.677490234375 
cx = 640. 
cy = 480.
cameraMatrix = np.array([[fx, 0, cx], [0, fy, cy], [0.,0.,1.]])
distorsionCoeff = np.array([0.0, 0.0, 0.0, 0.0])

"detect markers"
(marker_corners, marker_ids, rejected) = aruco.detectMarkers(np_img_3c, arucoDict, parameters=arucoParams)
"draw detected markers"
img2 = aruco.drawDetectedMarkers(np_img_result, marker_corners, marker_ids)
detected = Image.fromarray(img2)
detected.save("1_detected_markers.png")

"interpolate corners"
_, charuco_corners, charuco_ids = cv2.aruco.interpolateCornersCharuco(marker_corners, marker_ids, np_img_3c, calibration_board, cameraMatrix=cameraMatrix, distCoeffs=distorsionCoeff)

"draw detected corners"
img1 = aruco.drawDetectedCornersCharuco(np_img_result, charuco_corners, charuco_ids, (255, 0, 0))
img_corners = Image.fromarray(img1)
img_corners.save("2_detected_corners.png")

"get pose of board"
valid, rvec, tvec = aruco.estimatePoseCharucoBoard(charuco_corners, charuco_ids, calibration_board, cameraMatrix, distorsionCoeff, np.empty(1), np.empty(1), useExtrinsicGuess=False)

img_result = cv2.drawFrameAxes(np.copy(np_img_3c), cameraMatrix, distorsionCoeff, rvec, tvec, 0.08)
img_calib_result = Image.fromarray(img_result)
img_calib_result.save("3_calib_pose.png")


"get pose of single markers"
rvecs, tvecs, objPoints = aruco.estimatePoseSingleMarkers(marker_corners, markerLength=0.062, cameraMatrix=cameraMatrix, distCoeffs=distorsionCoeff)
img_single_pose = np.copy(np_img_3c)
for i in range(len(rvecs)):
    img_single_pose = cv2.drawFrameAxes(img_single_pose, cameraMatrix, distorsionCoeff, rvecs[i], tvecs[i], 0.05)
img_single_pose = Image.fromarray(img_single_pose)
img_single_pose.save("4_calib_single_pose.png")
```

Find attached the result:
Detection of markers and coners works:
![image](https://user-images.githubusercontent.com/113530941/206405034-1794c84d-1433-4c76-95e4-2e762f87e622.png)

Resulting pose and single marker pose
![image](https://user-images.githubusercontent.com/113530941/206405247-2e9b212a-49d1-4760-a1ac-443ca1166ad2.png)
![image](https://user-images.githubusercontent.com/113530941/206405406-0faa603a-a16e-41b9-b3c1-f0051e83f20d.png)

In my understanding the z-axis (blue) should point to the camera. Am I right?
Hope you can help me.

Best regard, 
Patrick

**Comment by Patricks15** [comment]
Hello, 
I still have this issue. Any updates regarding this ?

Best regard,
Patrick

**Comment by AleksandrPanov** [comment]
@Patricks15 I think, that Z axis (blue) should feel like it is perpendicular to our charuco/chessboard plane ([drawFrameAxes()](https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html#gab3ab7bb2bdfe7d5d9745bb92d13f9564)).

Regarding your sample, it uses the old API (aruco was moved from contrib to main repo). Actual API implemented in opencv 4.7

Use [docs](https://docs.opencv.org/4.x/d9/d6a/group__aruco.html), [py tests](https://github.com/opencv/opencv/tree/4.x/modules/objdetect/misc/python/test), and [new sample](https://github.com/opencv/opencv/pull/23139) to use new API.

I converted your sample with new API:
[sample.py.txt](https://github.com/opencv/opencv-python/files/10429362/sample.py.txt)

In this implementation we get images like this:

![2_detected_markers](https://user-images.githubusercontent.com/22337800/212762807-13a98a7e-c0a0-477a-a7bf-3d4104548225.png)
![3_calib_pose](https://user-images.githubusercontent.com/22337800/212762808-0f962a38-04c5-4434-8f3c-813cf4b4a9c9.png)
![4_calib_single_pose](https://user-images.githubusercontent.com/22337800/212762801-75201302-2804-472d-aaf4-74513788ed2e.png)

There is problem with python binding in [matchImagePoints()](https://docs.opencv.org/4.x/d4/db2/classcv_1_1aruco_1_1Board.html#a305c3c47c1f87562ed06de5c7e703e4f), [PR #23138](https://github.com/opencv/opencv/pull/23138) fixes this. Until the PR merge, you can using custom `matchImagePoints()` from sample:

```
def matchImagePoints(charuco_board, charuco_corners, charuco_ids):
    objPoints = []
    imgPoints = []
    for i in range(0, len(charuco_ids)):
        index = charuco_ids[i]
        objPoints.append(charuco_board.getChessboardCorners()[index])
        # objPoints[-1][0][1] = charuco_board.getRightBottomCorner()[1] - objPoints[-1][0][1]  # set old axis direction
        imgPoints.append(charuco_corners[i])
    return np.array(objPoints), np.array(imgPoints)
```

Also you can change Z-axis direction (like in old API):

![3_calib_pose_old](https://user-images.githubusercontent.com/22337800/212764918-599a387b-8bce-4a38-8f7f-5c53e04c3f4a.png)


![4_calib_single_pose_old](https://user-images.githubusercontent.com/22337800/212765335-cc6650a7-6aaf-41fa-89a6-c7a560bb997b.png)


Also you can set custom axis with [projectPoints()](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga1019495a2c8d1743ed5cc23fa0daff8c)
You can use only `cv.imread`/`cv.imwrite` without using `Pillow` module.
Please attach source image (without axes) in next time.

**Comment by Patricks15** [comment]
Thank you very much Aleksandr for your detailed response.

I switched the opencv to main version and version=4.7.0.68 and tested your implementation.
Unfortunately I got the following errors for:

`estimateParameters = aruco.EstimateParameters()`
> AttributeError: module 'cv2.aruco' has no attribute 'EstimateParameters'

`rvecs, tvecs, objPoints = aruco.estimatePoseSingleMarkers(marker_corners, markerLength=0.062, cameraMatrix=cameraMatrix,
                                                          distCoeffs=distorsionCoeff,
                                                          estimateParameters=estimateParameters)`

> AttributeError: module 'cv2.aruco' has no attribute 'estimatePoseSingleMarkers'

in the docs there are these functions.

Best regards,
Patrick

**Comment by AleksandrPanov** [comment]
@Patricks15, please, update opencv-python-contrib to use`EstimateParameters` (in new version there were removed useless fabric methods such as `EstimateParameters::create`/`EstimateParameters_create`. Now just constructors are used).

Also [estimatePoseSingleMarkers() ](https://docs.opencv.org/4.x/d9/d6a/group__aruco.html#gaba7f1e107f93451e2bc43b8ea96eef8c) is deprecated, you can use [cv::solvePnP](https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html#ga549c2075fac14829ff4a58bc931c033d):

```
img_single_pose = np.copy(np_img_3c)
objPoints = np.array([[0., 0., 0.], [1., 0., 0.], [1., 1., 0.], [0., 1., 0.]])
for marker_corner in marker_corners:
    valid, rvec, tvec = cv.solvePnP(objPoints, marker_corner, cameraMatrix, distorsionCoeff)
    cv.drawFrameAxes(img_single_pose, cameraMatrix, distorsionCoeff, rvec, tvec, 1)
```


More information will appear in the new samples.

**Comment by Patricks15** [comment]
A final question please.
How to change the Z-axis direction (like in old API) ? Which function can I use? Is there a function?
To reproduce your result with the z-Axis pointing to the camera.

**Comment by asmorkalov** [comment]
@AleksandrPanov

**Comment by AleksandrPanov** [comment]
@Patricks15, you can configure custom axes with `projectPoints` function:

```
def get_custom_axes(cam, dist, rvec, tvec, length=1.):
    # set array to configure custom axes
    axes = np.array([[0., 0., 0.], [length, 0., 0.], [0., length, 0.], [0., 0., -length]])
    axes_to_img, _ = cv.projectPoints(axes, rvec, tvec, cam, dist)
    return np.floor(np.squeeze(axes_to_img)).astype(int)


def draw_axes(img, axes, thickness=5):
    img = cv.line(img, axes[0], axes[0+1], (0,0,255), thickness)
    img = cv.line(img, axes[0], axes[1+1], (0,255,0), thickness)
    img = cv.line(img, axes[0], axes[2+1], (255,0,0), thickness)
    return img
```

Also you can configure custom matchImagePoints:
```
def matchImagePoints(charuco_board, charuco_corners, charuco_ids):
    objPoints = []
    imgPoints = []
    for i in range(0, len(charuco_ids)):
        index = charuco_ids[i]
        objPoints.append(charuco_board.getChessboardCorners()[index])
        # objPoints[-1][0][1] = charuco_board.getRightBottomCorner()[1] - objPoints[-1][0][1]  # uncomment to set old axis
        imgPoints.append(charuco_corners[i])
    return np.array(objPoints), np.array(imgPoints)
```

sample:
[main.py.txt](https://github.com/opencv/opencv-python/files/10899638/main.py.txt)

**Comment by AleksandrPanov** [comment]
original.png:
![original](https://user-images.githubusercontent.com/22337800/223151279-85eece58-f246-4f64-900a-b7a66c69c7a5.png)

**Comment by asmorkalov** [comment]
Looks like the issue has been solved. Closing the ticket.
