### ISSUE TITLE
Hi, how to detect  Image RGB along with Image saturation pixcel ?

### ISSUE THREAD

**Issue by rsurendraidexcel** [skvark/opencv-python#764]
Image Pixel RGB is perfect detection.

what about Image RGB along with Saturation pixcel?

**Comment by puneeth072003** [comment]
Get the pixel value at every point using the getRGB() method. Instantiate the Color object by passing the pixel value as a parameter. Get the Red, Green, Blue values using the getRed(), getGreen() and getBlue() methods respectively.

**Comment by asmorkalov** [comment]
Please use forum.opencv.org for questions.
