### ISSUE TITLE
Why can opencv-python-headless run cv2.imshow() on Mac M1?

### ISSUE THREAD

**Issue by Chris-fullerton** [skvark/opencv-python#766]
### Expected behaviour

`opencv-python-headless` runs `cv2.imshow()` correctly on Mac M1, but it shouldn't.

According to [opencv-python-headless - PyPI](https://pypi.org/project/opencv-python-headless/), `headless` version is suitable for servers and does not provide ui-related functions like `cv2.imshow()`:

> b. Packages for server (headless) environments (such as Docker, cloud environments etc.), no GUI library dependencies
>
> These packages are smaller than the two other packages above because they do not contain any GUI functionality (not compiled with Qt / other GUI components). This means that the packages avoid a heavy dependency chain to X11 libraries and you will have for example smaller Docker images as a result. You should always use these packages if you do not use cv2.imshow et al. or you are using some other package (such as PyQt) than OpenCV to create your GUI.

### Actual behaviour

When I tried to install `insightface`(https://github.com/deepinsight/insightface) package, it would automatically install `opencv-python-headless`(seems like the installation was fallowing the requirements of `setup.py` from `insightface`, but I'm not sure about it), and I can run `cv2.imshow()` correctly(use webcam with `cv2.VideoCapture(0)` and show by frames with `cv2.imshow()`).

### Steps to reproduce

<details>
  <summary>example code</summary>

  How I build my conda env(insightface==0.7.2):
  ```
conda create -n test python=3.8
conda activate test
pip install insightface
  ```

  ```
import cv2

if __name__ == '__main__':

    # 開啟 RTSP 串流
    vidCap = cv2.VideoCapture(0)

    while True:
        ret, image = vidCap.read()

        cv2.namedWindow('image_display', cv2.WINDOW_AUTOSIZE)
        cv2.imshow('image_display', image)
        cv2.waitKey(1)

        if cv2.waitKey(1) & 0xff == ord('q'):
            break

    vidCap.release()
    cv2.destroyAllWindows()
  ```
</details>
<details>
  <summary>operating system</summary>
  macOS Ventura 13.0
</details>
<details>
  <summary>architecture (e.g. x86)</summary>
  Apple M1, 2020
</details>
<details>
  <summary>opencv-python version</summary>

  `conda list | grep opencv`:
  ```
opencv-python-headless    4.7.0.68                 pypi_0    pypi
  ```
</details>

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python`` (the problem is about **`opencv-python-headless`**)

**Comment by skvark** [comment]
Because the Apple Cocoa backend cannot be disabled with OpenCV CMake flags.

**Comment by Chris-fullerton** [comment]
@skvark I am not a related developer of macos, and I am not very familiar with cocao. 😭 Can it be understood that the headless version should not be able to run UI-related functions such as imshow(), but the function division fails due to the above reasons?

**Comment by skvark** [comment]
There's no way to turn off the UI-related functions on Mac. Due to this, the headless version has support for `imshow` et al.. 

This is not really a problem, since to my knowledge MacOS is not used in server environments. The headless variant is targeted mostly for Linux and Windows server environments. But we need to publish the headless variant for all platforms to make sure that `pip install` works identically on all platforms.

See: https://github.com/opencv/opencv-python/blob/339bca572ecd866b56df1f61214cbf03c5f276f2/setup.py#L201

**Comment by Chris-fullerton** [comment]
Got it. I went through the entire setup.py quickly and didn't notice this comment. My mistake. Do I need to close this issue myself since the problem has been answered?

btw: Does the document need to be updated for this part? Or are there plans to fix this in the future?
