### ISSUE TITLE
import cv2... DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Dani134134** [skvark/opencv-python#77]
> I have installed opencv in anaconda using comand 'conda install -c menpo opencv'

> it was working correct but today it is giving error in comand **import cv2**

**I installed keras library and tenserflow using comands** 

> conda install -c conda-forge keras
after installation completes....then paste other comand
conda install -c conda-forge tensorflow

> It installed successfully but after this when i tried comand **import cv2** it start giving error

![capture](https://user-images.githubusercontent.com/37267272/37254944-508dceb4-2567-11e8-82ed-4db8c2e9ce9e.PNG)

- operating system
Window10
- architecture x64
- opencv-python version
python3

**Comment by skvark** [comment]
I can't help you, this repository has nothing to do with conda packages. This repository provides packages called ``opencv-python`` and they can be installed with **pip**. For example ``pip install opencv-python``. They are targeted for original **CPython**.

**Comment by Dani134134** [comment]
> pip install opencv-python 

could opencv be installed through this command in anaconda python 3.6.3
![anaconda prompt](https://user-images.githubusercontent.com/37267272/37562826-59e0c1ac-2a93-11e8-9ba5-bc3be4f60ad1.PNG)
