### ISSUE TITLE
Installation with pip falis fpr python3.6 (pep517)

### ISSUE THREAD

**Issue by walterschneider** [skvark/opencv-python#773]
### Actual behaviour

installation fails with an error converning pep517

### Steps to reproduce

> $ pip3 install opencv-python
Collecting opencv-python
  Downloading opencv-python-4.7.0.68.tar.gz (91.1 MB)
     |████████████████████████████████| 91.1 MB 270 kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp63ipabs6
       cwd: /tmp/pip-install-qbgk08_t/opencv-python
  Complete output (1 lines):
  /usr/bin/python3: can't find '__main__' module in '/usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp63ipabs6 Check the logs for full command output.

OS: Ubuntu 18.04 (bionic), amd64
opencv-python 4.7.0.68

Revision `4.6.0.66` is working with pyhton3.6, `4.7.0.68` is working with pyhton3.10

**Comment by asmorkalov** [comment]
Duplicate: https://github.com/opencv/opencv-python/issues/782
