### ISSUE TITLE
Unable to package opencv-python using python 3.10

### ISSUE THREAD

**Issue by HiranCser** [skvark/opencv-python#778]
### Expected behaviour

To build and package opencv-python package by disable/removing unwanted packages/third party.

### Actual behaviour

Unable to package opencv-python package.

### Steps to reproduce

- Clone the repo with version 4.6.0.66
- operating system: Microsoft Windows 10 Enterprise (10.0.19042 Build 19042)
- architecture (e.g. x86): x64
- opencv-python version: 4.6.0.66
-  Cmake used from: VS2022  (3.25.0)

Updated setup.py file with following flags:
"-DPYTHON3_EXECUTABLE=%s" % sys.executable,
            "-DPYTHON3_INCLUDE_DIR=%s" % python_include_dir,
            "-DPYTHON3_LIBRARY=%s" % python_lib_path,
            "-DBUILD_opencv_python3=ON",
            "-DBUILD_opencv_python2=OFF",
            "-DWITH_FFMPEG=OFF",
            "-DWITH_QUIRC=OFF",
            "-DWITH_JPEG=OFF",
            "-DWITH_TIFF=OFF",
            "-DWITH_WEBP=OFF",
            "-DWITH_JASPER=OFF",
            "-DWITH_PNG=OFF",
            "-DWITH_OPENEXR=OFF",
            "-DWITH_GDAL=OFF",
            "-DWITH_GDCM=OFF",
            "-DWITH_PROTOBUF=OFF",
            "-DOPENCV_SKIP_PYTHON_LOADER=ON",
            # Disable the Java build by default as it is not needed
            "-DBUILD_opencv_java=OFF",
            # Relative dir to install the built module to in the build tree.
            # The default is generated from sysconfig, we'd rather have a constant for simplicity
            "-DOPENCV_PYTHON3_INSTALL_PATH=python",
            # Otherwise, opencv scripts would want to install `.pyd' right into site-packages,
            # and skbuild bails out on seeing that
            "-DINSTALL_CREATE_DISTRIB=ON",
            # See opencv/CMakeLists.txt for options and defaults
            "-DBUILD_opencv_apps=OFF",
            "-DBUILD_opencv_freetype=OFF",
            "-DBUILD_SHARED_LIBS=OFF",
            "-DBUILD_TESTS=OFF",
            "-DBUILD_PERF_TESTS=OFF",
            "-DBUILD_DOCS=OFF",
            "-DPYTHON3_LIMITED_API=ON",
            "-DBUILD_OPENEXR=ON",
            "-DBUILD_opencv_ffmpeg=OFF",		
            "-DBUILD_opencv_calib3d=OFF",
            "-DBUILD_opencv_imgcodecs=OFF",
            "-DBUILD_opencv_dnn=OFF",
            "-DBUILD_opencv_features2d=OFF",
            "-DBUILD_opencv_flann=OFF",
            "-DBUILD_opencv_gapi=OFF",
            "-DBUILD_opencv_highgui=OFF",
            "-DBUILD_opencv_java=OFF",
            "-DBUILD_opencv_js=OFF",
            "-DBUILD_opencv_ml=OFF",
            "-DBUILD_opencv_objdetect=OFF",
            "-DBUILD_opencv_photo=OFF",
            "-DBUILD_opencv_stitching=OFF",
            "-DBUILD_opencv_ts=OFF",
            "-DBUILD_opencv_video=OFF",
            "-DBUILD_opencv_videoio=OFF",
            "-DBUILD_opencv_world=OFF",	            
            "-DBUILD_opencv_videostab=OFF",

Run following command: 

set ENABLE_HEADLESS=1
set Path=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;%path%
py -3.10  setup.py build

See the attached file for error information.

[Opencv-BuildError.txt](https://github.com/opencv/opencv-python/files/10422540/Opencv-BuildError.txt)

Not sure if I am missing any settings in my system.

**Comment by alalek** [comment]
This deprecated flag:

> `-DOPENCV_SKIP_PYTHON_LOADER=ON`

causes this problem (as expected files are missing):

```
  File "E:\github\opencv-python-4.6.0.66\opencv-python\setup.py", line 426, in _classify_installed_files_override
    with open('%spython/cv2/config-%s.py'
FileNotFoundError: [Errno 2] No such file or directory: '_skbuild\\win-amd64-3.10\\cmake-install\\python/cv2/config-3.py'
```

---

Also looks like there is python misconfigured as there is missing `opencv_python3` target (and `cv2.pyd` file).
Ensure that you have `numpy` in your python.

**Comment by HiranCser** [comment]
@alalek : thanks for the hint.

After setting -DOPENCV_SKIP_PYTHON_LOADER=OFF and changing environment variable PATH to have python 3.10 executable as first path, I was able to resolve above error. I have even installed numpy 1.21.2.

However, even after these steps, I face attached error.
[Opencv-BuildError_2.txt](https://github.com/opencv/opencv-python/files/10424192/Opencv-BuildError_2.txt)

Please note that this error comes with python setup.py build  command as well.
Is it possible to build/pack only in release mode? I tried with following but no luck:
`if build_headless:
        # it seems that cocoa cannot be disabled so on macOS the package is not truly headless
        cmake_args.append("-DWITH_WIN32UI=OFF")
        cmake_args.append("-DCMAKE_BUILD_TYPE=Release")`

**Comment by alalek** [comment]
The same problem.
You have changed configuration but didn't update the packaging script - expectations/assumptions of setup.py are broken and script fails.
Only "default" settings are supported.
Do NOT touch CMake settings if you don't know that they really do.

> `-DWITH_FFMPEG=OFF`

causes this as expected:

> `Exception: Not found: 'bin/opencv_videoio_ffmpeg\d{3}_64\.dll'`

---

> only in release mode

It is already in Release mode (from logs):

```
-- Install configuration: "Release"
```

---

`numpy` is still not detected and OpenCV Python bindings are not generated:

```
  --   Python 3:
  --     Interpreter:                 C:\Users\z0040ftv\AppData\Local\Programs\Python\Python310\python.exe (ver 3.10.8)
  --     Libraries:                   NO
  --     numpy:                       NO (Python3 wrappers can not be generated)
  --     install path:                -
```

---

Refer to GitHub Actions CI for validated build environment and expected build logs:

- workflow: https://github.com/opencv/opencv-python/blob/4.x/.github/workflows/build_wheels_windows.yml
- runs: https://github.com/opencv/opencv-python/actions/workflows/build_wheels_windows.yml
