### ISSUE TITLE
Opencv-python-contrib VS python-contrib in C++

### ISSUE THREAD

**Issue by WANGYuSCU** [skvark/opencv-python#78]
Please tell me about the difference in python and C++

I want to use multiband and cameraPoseFromHomography in opencv.

In the past, I want to use multiband blending and I find in python-contrib version of C++. I can find the class which I can use.
While in python-opencv-contrib, I can't find multibandblender. But I can see something in cv2.detail.
I feel quite comfused. If there is no multibandblender in python version, why there are still something like cv2.detail.Blender_MULTI_BAND.

- C++: Multibandblender  blender;   Python: I can't find related code.
- Win10
- architecture (e.g. x64)
- opencv-python-contrib 3.2.0

**Comment by skvark** [comment]
Please ask common usage questions at https://stackoverflow.com/ or at http://answers.opencv.org/.
