### ISSUE TITLE
opencv-python missing bindings for setting videocapture open timeout and read timeout

### ISSUE THREAD

**Issue by ribeirompl-soldersmith** [skvark/opencv-python#788]
`cv2.VideoCapture` and the `.read()` method can hang indefinitely in certain situations when an RTSP stream drops connection abnormally.
There appears to have been some timeout parameters added to account for this: https://github.com/opencv/opencv/pull/20541
But these parameters don't appear to be available in the latest version of opencv-python.

Although, the timeout feature in general seems to be missing? It was added to opencv here https://github.com/opencv/opencv/pull/6053 with a default of 30sec, but it does not seem to be functional in opencv-python. With some minimal testing, it appears to timeout (stop blocking) after around 90 seconds.

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
Looks like the issue has been fixed  in upstream repository. Both `CAP_PROP_OPEN_TIMEOUT_MSEC` and `CAP_PROP_READ_TIMEOUT_MSEC` are available in manual build with 4.8.0 and CI produced packages, e.g. https://github.com/opencv/opencv-python/actions/runs/5414007554?pr=864:
```
>>> q = cv.CAP_PROP_OPEN_TIMEOUT_MSEC
>>> print(q)
53
>>> print(cv.CAP_PROP_READ_TIMEOUT_MSEC)
54
```
