### ISSUE TITLE
Where could find the souce code of the function[cv2.projectPoinst()]?

### ISSUE THREAD

**Issue by kt-rax** [skvark/opencv-python#796]
I want debug the function cv2.projectPoints and get some process result. But couldn't the the python vesion source code of it.

Thx

**Comment by asmorkalov** [comment]
Python bindings for OpenCV are generated during build procedure in C++. There is no Python code for the function.

**Comment by kt-rax** [comment]
OK,got it,I have found the C++ souce code of this function. Thanks.

Additional, I have a new question. 
For the C++ source code:Python bindings for OpenCV could be generated during build procedure in C++. 
For some python source code: C++ bindings for it could be generated during build procedure in python？

Thanks again

**Comment by asmorkalov** [comment]
Package setup.py builds full library from C++. Python code distributed with the package has C++ "back-end" and just adapt some C++ abstractions for Python users.

**Comment by kt-rax** [comment]
Yeah，I got it, But I want to put some python code into c++ code, so the python version could be built into c++ lib directly or not?Thanks!

**Comment by skvark** [comment]
That's not how it works. If you would like to add a new feature in OpenCV, you need to go and code it in C++ to the upstream repository.

Of course, you can always extend opencv-python by creating your own open-source package that wraps around opencv-python. But embedding Python into C++ is not feasible.

**Comment by kt-rax** [comment]
OK，got it，Thank you very much for the quickly and detail response
