### ISSUE TITLE
Tesseract OCR not found

### ISSUE THREAD

**Issue by pevogam** [skvark/opencv-python#80]
Hi, I am installing this contrib version with travis-ci as follows

    pip install opencv-contrib-python

(saving you the fact that the name is in a `requirements.txt` list). However, even though I install tesseract on Ubuntu 14.04.5 LTS as

    sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install tesseract-ocr tesseract-ocr-dev

when I try to use tesseract from within opencv's contributed text module I get

    OCRTesseract(33): Tesseract not found.

A quick check on the installed module shows the tesseract library is not even required:

    $ sudo ldd /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/cv2/cv2.so
	linux-vdso.so.1 =>  (0x00007ffcd7d52000)
	libz-a147dcb0.so.1.2.3 => /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/cv2/.libs/libz-a147dcb0.so.1.2.3 (0x00007fab3bda5000)
	libavcodec-7625dabe.so.58.6.103 => /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/cv2/.libs/libavcodec-7625dabe.so.58.6.103 (0x00007fab3a621000)
	libavformat-d3ca1b40.so.58.3.100 => /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/cv2/.libs/libavformat-d3ca1b40.so.58.3.100 (0x00007fab3a1e0000)
	libavutil-eaec640f.so.56.5.100 => /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/cv2/.libs/libavutil-eaec640f.so.56.5.100 (0x00007fab39f6b000)
	libswscale-bc8d848b.so.5.0.101 => /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/cv2/.libs/libswscale-bc8d848b.so.5.0.101 (0x00007fab39ce2000)
	libQtGui-6d0f14dd.so.4.8.7 => /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/cv2/.libs/libQtGui-6d0f14dd.so.4.8.7 (0x00007fab38e51000)
	libQtTest-1183da5d.so.4.8.7 => /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/cv2/.libs/libQtTest-1183da5d.so.4.8.7 (0x00007fab38c24000)
	libQtCore-ba1dc80c.so.4.8.7 => /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/cv2/.libs/libQtCore-ba1dc80c.so.4.8.7 (0x00007fab38718000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fab38514000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fab382f6000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fab380ee000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fab37dea000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fab37ae4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fab378ce000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fab37505000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fab3e556000)
	libswresample-81cb7b3e.so.3.0.101 => /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/cv2/.libs/libswresample-81cb7b3e.so.3.0.101 (0x00007fab372e7000)
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007fab370e5000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fab36ddd000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007fab36bd5000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007fab369b9000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fab367af000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fab3659d000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fab36268000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fab3602a000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fab35e25000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fab35c06000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fab35a02000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fab357fc000)

I thought the contributions module should include this library as well. Or was it compiled in some other way?

**Comment by skvark** [comment]
Tesseract OCR is completely separate project and an optional dependency of OpenCV. To be able to use Tesseract with these packages I would need to:

1. Build Tesseract on every different platform (Cent OS 5, macOS, Windows)
2. Link it with OpenCV during build
3. Ship it with these packages

You can't use your globally installed libraries (except the whitelisted ones: https://github.com/pypa/auditwheel/blob/master/auditwheel/policy/policy.json) with precompiled wheel packages. That's how the .whl format works in Python.

It's a major effort to get all these third party libraries into the package. Currently only Qt and FFmpeg are provided as you can see in the ``ldd`` output at folder ``/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/cv2/.libs/``.

**Comment by pevogam** [comment]
Sorry what I mean was that I thought the contributions module should *be compiled against* this library as well. Clearly, shipping the tesseract library as well could be a mess. However, now I understand that global libraries cannot even be reached in general which is a deal breaker for many use cases, especially ones with projects that have nonpython dependencies. Do you think there could be any workaround other than recompiling opencv manually? Tesseract is a significant part of the contributed text module so I won't be able to use pip-based setup without it.

**Comment by skvark** [comment]
No, there's no workaround for this. Third party dependencies have to be enabled in Cmake config and linked with OpenCV during compilation. There's no way to add support for them afterwards. 

OpenCV is a very complex and large project with tens of different optional dependencies. Enabling all of them is a huge task and in many cases impossible since these packages have to compatible with almost all GNU/Linux distributions which were released after 2007. That's why the external dependencies in wheel packages are limited to a standardized, restricted subset of the Linux kernel and core userspace ABI. For more information, see [PEP 513](https://www.python.org/dev/peps/pep-0513/).

However, there's ongoing effort to refactor ``setup.py`` so that this package can be built also locally. When that's done, you can force a local custom build with optional dependencies from a source distribution. This means that the package is built from source whenever it needs to be installed.

**Comment by pevogam** [comment]
I see, thanks a lot!
