### ISSUE TITLE
Why is python2 needed?

### ISSUE THREAD

**Issue by beew** [skvark/opencv-python#800]
Hi, I am compiling opencv-python from source. While it compiled I am getting these warning

```
CMake Warning at cmake/OpenCVDetectPython.cmake:81 (message):
  CMake's 'find_host_package(PythonInterp 2.7)' found wrong Python version:

  PYTHON_EXECUTABLE=/home/beew/opt/python310/bin/python

  PYTHON_VERSION_STRING=3.10.9

  Consider providing the 'PYTHON2_EXECUTABLE' variable via CMake command line
  or environment variables

Call Stack (most recent call first):
  cmake/OpenCVDetectPython.cmake:271 (find_python)
  CMakeLists.txt:643 (include)
```

Python 2.7 has deprecated for a while, why is it still looking for python2?

OS is Ubuntu 22.04. opencv-python from git branch origin/4.x

**Comment by asmorkalov** [comment]
Some old OpenCV build and test scripts were written for Python 2. Also OpenCV can generate Python bindings for 2.x, but it's deprecated config and is not tested by the core team.
