### ISSUE TITLE
opencv-python 4.7.0.68 wheels does not solve the zlib issue

### ISSUE THREAD

**Issue by epeisach** [skvark/opencv-python#801]
### Expected behaviour

import cv2

should work

### Actual behaviour

>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/wwpdb_da/da_top/wwpdb_python/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/wwpdb_da/da_top/wwpdb_python/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/wwpdb_da/da_top/tools/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /data/wwpdb_da/da_top/wwpdb_python/lib/python3.8/site-packages/cv2/../opencv_python.libs/libpng16-186fce2e.so.16.37.0)

### Steps to reproduce

Centos-7 O/S
Compiled python 3.8
pip install python-opencv

python
import cv2

##### Issue submission checklist

 - [X] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [X] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [X] I'm using the latest version of ``opencv-python``

**Comment by wqh17101** [comment]
@epeisach dumplicate https://github.com/opencv/opencv-python/issues/772

**Comment by wqh17101** [comment]
The reason it that there is no zlib >=1.2.9 in you system.
