### ISSUE TITLE
Can't display image on fullscreen on MacOS

### ISSUE THREAD

**Issue by c6s0** [skvark/opencv-python#804]
### Expected behaviour

Displaying an image on fullscreen

### Actual behaviour

```cv2.imshow()``` function works fine in "window mode" but as soon as i try to display the image on fullscreen i just get a grey screen.
Same code works fine on windows.
### Steps to reproduce

````
import cv2

img = 'test.png'
image = cv2.imread(img)
cv2.namedWindow('test', cv2.WND_PROP_FULLSCREEN)
cv2.setWindowProperty('test', cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_FULLSCREEN)
cv2.imshow("test", image)
cv2.waitKey(0)
cv2.destroyAllWindows()
````
- operating system: MacOS Ventura 13.2.1
- architecture: M1 arm64
- opencv-python version 4.5.5

**Comment by asmorkalov** [comment]
Possibly related: https://github.com/opencv/opencv/issues/4605

**Comment by tallosim** [comment]
Is there any update related to this issue?

**Comment by 0xMihir** [comment]
For some reason getWindowRect returns a totally bogus value that doesn't reflect the actual resolution:

for example, `(0, 2734, 0, 0)` on a 2560x1440p monitor

**Comment by AlexWTT** [comment]
Getting this exact issue. Did you manage to find a solution?

**Comment by 0xMihir** [comment]
I'm trying to fix it. There's some issue with the way OpenCV sets the options and sizing for the window. Objective C is making me lose my sanity though...

**Comment by asmorkalov** [comment]
@VadimLevin I believe we can close the ticket. Right?

**Comment by VadimLevin** [comment]
Yep, issue should be closed

**Comment by ShlomiRex** [comment]
I still have this problem
opencv-python 4.8.0.76
macbook pro M1 macOS
<img width="1440" alt="image" src="https://github.com/opencv/opencv-python/assets/17744127/14ea6933-09ee-4999-b159-9ac64abcf5bf">
If I disable this code (not fullscreen) then I see fine:
```
  cv2.setWindowProperty(
      "Select Region", cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_FULLSCREEN)
```

like so:
<img width="1440" alt="image" src="https://github.com/opencv/opencv-python/assets/17744127/4b76bb7a-6060-482a-8b05-b2b52f69bf1a">

**Comment by asmorkalov** [comment]
The issue has been fixed in OpenCV 4.x branch. The fix will be available with OpenCV-Python 4.9.0 release.

**Comment by ShlomiRex** [comment]
> The issue has been fixed in OpenCV 4.x branch. The fix will be available with OpenCV-Python 4.9.0 release.

Thanks! Do you know when it will be released? Or how to install beta version with pip?

**Comment by 0xMihir** [comment]
You can try it now by installing from source or pointing pip to the git repo

**Comment by lucadimascolo** [comment]
I have recently installed opencv-python from this repo, but I am stil getting the same grey screen issue when trying to open a fullscren window.
I am not a Macbook Pro M1 with macOS Ventura 13.5.2. I tried running everything with python 3.9 and 3.10. 

Any suggestions?
