### ISSUE TITLE
connectedComponentsWithStats ignores connectivity parameter

### ISSUE THREAD

**Issue by MarkusSchiefele** [skvark/opencv-python#809]
### Expected behaviour

My example code creates a mask with two squares, which touch only at one corner. With connectivity equals 4 I would expect the output of figure 2, i.e. different labels for for each square.
With connectivity equals 8 I get the same labels for both squares, which is as expected.

### Actual behaviour

With connectivity equals 4 I get the output of figure 1, i.e. the same output as for connectivity equals 8 (figure3). Specifying the connectivity has no influence on the output.

### Steps to reproduce
This is the code, that created figure 1, 2 and 3:

```
import cv2
import matplotlib.pyplot as plt
import numpy as np

mask = np.zeros((6,6), dtype=np.uint8)
mask[1:3,1:3] = 255
mask[3:5,3:5] = 255

connectivity=4
_, labels, _, _ = cv2.connectedComponentsWithStats(mask, connectivity, cv2.CV_32S)
plt.figure()
plt.imshow(labels, cmap='jet')
plt.title('connectivity = {:d}'.format(connectivity))
labels[3:5,3:5]=2 # manually changing the labels to the expected output
plt.figure()
plt.imshow(labels, cmap='jet')
plt.title('connectivity = {:d} (expected)'.format(connectivity))

connectivity=8
_, labels, _, _ = cv2.connectedComponentsWithStats(mask, connectivity, cv2.CV_32S)
plt.figure()
plt.imshow(labels, cmap='jet')
plt.title('connectivity = {:d}'.format(connectivity))

plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/67169464/221916044-afd5fd41-be67-457e-bd04-9e15776e3d8a.png)
![Figure_2](https://user-images.githubusercontent.com/67169464/221916075-1c92b8a2-298b-46de-96da-e8da777a2dd5.png)
![Figure_3](https://user-images.githubusercontent.com/67169464/221916097-b48e994f-8923-42c4-918b-44e79f04f8cb.png)

**Comment by asmorkalov** [comment]
The python function incorrectly. You can achieve expected behaviour with named parameters:
```
_, labels, _, _ = cv2.connectedComponentsWithStats(mask, connectivity=connectivity, ltype=cv2.CV_32S)
```
See documentation: https://docs.opencv.org/4.x/d3/dc0/group__imgproc__shape.html#ga107a78bf7cd25dec05fb4dfc5c9e765f

**Comment by MarkusSchiefele** [comment]
Hi Alexander,

That fixed the problem, thank you!

Markus

Markus Schiefele, PhD
Principal Software and Algorithm Engineer
***@***.***
[HID Global Logo]<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.hidglobal.com%2F&data=04%7C01%7Czach.osne%40hidglobal.com%7C71d566eedc614b5a89b808da0223509f%7Cf0bdc1c951484f86ac40edd976e1814c%7C0%7C0%7C637824647955524029%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=y%2FcEbu0Z4vCt0ew0u8dYV4nspj%2FGiivEW2mlEQrkRcc%3D&reserved=0>
3950 RCA Blvd. Ste 5001, Palm Beach Gardens, FL 33410 , USA
www.hidglobal.com<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.hidglobal.com%2F&data=04%7C01%7Czach.osne%40hidglobal.com%7C71d566eedc614b5a89b808da0223509f%7Cf0bdc1c951484f86ac40edd976e1814c%7C0%7C0%7C637824647955524029%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=y%2FcEbu0Z4vCt0ew0u8dYV4nspj%2FGiivEW2mlEQrkRcc%3D&reserved=0>


From: Alexander Smorkalov ***@***.***>
Sent: Wednesday, March 1, 2023 1:52 AM
To: opencv/opencv-python ***@***.***>
Cc: Schiefele, Markus ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [opencv/opencv-python] connectedComponentsWithStats ignores connectivity parameter (Issue #809)

CAUTION: This email is external. Do not click links or attachments that are unexpected or from unknown senders. If unsure, click the Report Phishing Button in Outlook.

The python function incorrectly. You can achieve expected behaviour with named parameters:

_, labels, _, _ = cv2.connectedComponentsWithStats(mask, connectivity=connectivity, ltype=cv2.CV_32S)

See documentation: https://docs.opencv.org/4.x/d3/dc0/group__imgproc__shape.html#ga107a78bf7cd25dec05fb4dfc5c9e765f<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.opencv.org%2F4.x%2Fd3%2Fdc0%2Fgroup__imgproc__shape.html%23ga107a78bf7cd25dec05fb4dfc5c9e765f&data=05%7C01%7CMarkus.Schiefele%40hidglobal.com%7C2706ebc95cf343d24f4908db1a2178cb%7Cf0bdc1c951484f86ac40edd976e1814c%7C0%7C0%7C638132503289791053%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gf9jFlKiRErl0hnWFy8D4fh6rnAoYdXodV02QG0tQBY%3D&reserved=0>

-
