### ISSUE TITLE
sfm reconstruction function ends up in overload resolution failed

### ISSUE THREAD

**Issue by Keasys** [skvark/opencv-python#810]
### Expected behaviour
calling cv2.sfm.reconstruct() with a numpy array as K parameter should not give any error in the C++ backend. 

It's the first time I compile and use opencv contrib to use sfm module, so I might have missed something. 

Anyway I built and installed opencv following instructions and installing dependencies (ceres installs fine and it's found during opencv-contrib building process). Any other python binding module in opencv contrib runs fine.

### Actual behaviour
```
Traceback (most recent call last):
  File "<string>", line 19, in __PYTHON_EL_eval
  File "/home/++++/+++/+++/+++/+++/fundamental_matrix.py", line 161, in <module>
    cv.reconstruct
cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'reconstruct'
> Overload resolution failed:
>  - K is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'K'
```
### Steps to reproduce

- *sample code* - 

P, P_prime = cv.sfm.projectionsFromFundamental(F)
K= np.identity(3)
cv.sfm.reconstruct([scene_coordinates.T, projector_coordinates.T], [P, P_prime], P)

- *operating system* - Arch Linux 
- *architecture* - x86_64
- *opencv-python version* - 4.7.0 

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
@Keasys Thanks for the report. Could you provide some reproducer code for the issue?

**Comment by Keasys** [comment]
Ok, turns out I was actually missing something. 

>>> help(cv.sfm.reconstruct)
Help on built-in function reconstruct:

reconstruct(...)
    reconstruct(points2d, K[, Ps[, points3d[, is_projective]]]) -> Ps, points3d, K
    .   @brief Reconstruct 3d points from 2d correspondences while performing autocalibration.
    .     @param points2d Input vector of vectors of 2d points (the inner vector is per image).
    .     @param Ps Output vector with the 3x4 projections matrices of each image.
    .     @param points3d Output array with estimated 3d points.
    .     @param K Input/Output camera matrix \f$K = \vecthreethree{f_x}{0}{c_x}{0}{f_y}{c_y}{0}{0}{1}\f$. Input parameters used as initial guess.
    .     @param is_projective if true, the cameras are supposed to be projective.
    .   
    .     This method calls below signature and extracts projection matrices from estimated K, R and t.
    .   
    .      @note
    .       - Tracks must be as precise as possible. It does not handle outliers and is very sensible to them.

The output here shows I exported the wrong overloaded function.
Thank for the quick reply.
