### ISSUE TITLE
No tab completion recognition of installed opencv-python

### ISSUE THREAD

**Issue by Petros626** [skvark/opencv-python#811]
Hello people

I have installed the latest version (4.7.0) and by itself the use of functions in the terminal works, e.g. 
```python
import cv2 
cv2.waitKey()
```
However, I have the problem when using the _Thonny IDE_ (uses pip to install packages). There I can also import OpenCV, but I cannot call any functions via tab completion. What is the problem? Have also made a link as follows:

`sudo ln -s /home/pk/.local/lib/python3.9/site-packages/cv2 /home/pk/.config/Thonny/plugins/lib/python3.9/site-packages/cv2`

Thanks in advance

**Comment by asmorkalov** [comment]
Fixed in:
- https://github.com/opencv/opencv/pull/20370
- https://github.com/opencv/opencv-python/pull/853
