### ISSUE TITLE
Is it possible to access CuPy array directly within cuda_GpuMat?

### ISSUE THREAD

**Issue by amanda-peng** [skvark/opencv-python#818]
Is it possible to access CuPy array directly within cuda_GpuMat to support CudaArrayInterface?

Implemented a wrapper of CudaArrayInterface works fine to move GpuMat memory directly to CuPy. However, it failed with move from CuPy array to GpuMat.

Reference below link
https://github.com/rapidsai/cucim/issues/329#issuecomment-1397507158

if initiated cuda_GpuMat with CuPy array pointer, the results is not as expected, it seems cv2.cuda_GpuMat calls some default allocator and does not use the passed pointer memory. 

img_cv2_cu = cv2.cuda_GpuMat(img_cp.__cuda_array_interface__['shape'],
                             cv2.CV_8U, # or cv2.CV_8UC1
                             img_cp.__cuda_array_interface__['data'][0])

Is there anyone can help to check this ? any guidance on how to do this?

**Comment by asmorkalov** [comment]
Please use https://forum.opencv.org. It has larger audience for such questions.

**Comment by amanda-peng** [comment]
Thank you! Created a topic here 
https://forum.opencv.org/t/is-it-possible-to-access-cupy-array-directly-within-cuda-gpumat/12404

**Comment by amanda-peng** [comment]
Thank you! With this fix, I can create the GpuMat with the passed GPU memory pointer what as I expected.
