### ISSUE TITLE
Is opencv-python-rolling still built every week?

### ISSUE THREAD

**Issue by WanliZhong** [skvark/opencv-python#819]
Is opencv-python-rolling still built every week? I found the latest version was built on Feb. 11.
![image](https://user-images.githubusercontent.com/49567307/225233177-862b9f03-9dd0-4d2b-8d43-3bd7b82f1ee6.png)

**Comment by asmorkalov** [comment]
Looks like something broken in CI. I'll take a look.

**Comment by WanliZhong** [comment]
`opencv-python-rolling` is recovery, so close this issue
