### ISSUE TITLE
Autocomplete is still not working on pycharm.

### ISSUE THREAD

**Issue by zihaomu** [skvark/opencv-python#821]
### Expected behaviour

Autocomplete is still not working on pycharm.

### Steps to reproduce
Test it with Apple M1, PyCharm.
And the opencv-version: 
`4.7.0.68` and `4.7.0.72` are both not working.

Related discuss: https://stackoverflow.com/a/75054982/14419009
##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [ ] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by perspicacitee** [comment]
How it solved, can I get some advice, plz

**Comment by xucian** [comment]
any updates?

**Comment by 775124946** [comment]
me too

**Comment by 775124946** [comment]
> me too

pip install opencv-python
pip install opencv-contrib-python

success ~~

**Comment by Gornoka** [comment]
Workaround for Windows is to create a hard link from the site-packages folder to the binary file mentioned in the linked discussion.

be aware that 'mklink' is only available in the old windows command line.
````shell
cd <your_venv_location>/Lib/site-packages
mklink /H cv2.pyd cv2\cv2.pyd
````

**Comment by damonmaria** [comment]
On MacOS (M1) I had to symlink the `cv2.abi3.so` file into the `site-packages` dir:
```shell
cd <venv>/lib/python3.8/site-packages
ln -s cv2/cv2.abi3.so
```

**Comment by kylefmohr** [comment]
> On MacOS (M1) I had to symlink the `cv2.abi3.so` file into the `site-packages` dir:
> 
> ```shell
> cd <venv>/lib/python3.8/site-packages
> ln -s cv2/cv2.abi3.so
> ```

Thanks, this also does the trick on my Intel Mac. I ran:

`ln -s /Users/kyle/PycharmProjects/animation-processing/venv/lib/python3.11/site-packages/cv2/cv2.abi3.so  /Users/kyle/PycharmProjects/animation-processing/venv/lib/python3.11/site-packages/`

And then I also needed to invalidate caches in PyCharm before autocomplete started working (`File -> Invalidate Caches`)

**Comment by damonmaria** [comment]
@kylefmohr I'm doing this in IDEA where the symlink gets picked up automatically. 

But an issue with the symlink is `pipenv` often seems to clear it away and I have to re-add the symlink fairly often.

**Comment by Gornoka** [comment]
I now had access to a test system with Linux/AMD64, and the workaround also works there.

Linux and Mac (thanks to @damonmaria):
````shell
cd <your_venv>/lib/<your_python_version>/site-packages
ln -s cv2/cv2.abi3.so
````

Windows (old windows cmd line)
````cmd
cd <your_venv_location>/Lib/site-packages
mklink /H cv2.pyd cv2\cv2.pyd
````

**Comment by damonmaria** [comment]
> Linux and Mac (thanks to @damonmaria):
> ````shell
> cd <your_venv>/lib/<your_python_version>/site-packages
> ln -s cv2/cv2.abi3.so
> ````

I do find you have to recreate it fairly often (with `pipenv` anyway). But still worth it.

**Comment by Gornoka** [comment]
> > Linux and Mac (thanks to @damonmaria):
> > ```shell
> > cd <your_venv>/lib/<your_python_version>/site-packages
> > ln -s cv2/cv2.abi3.so
> > ```
> 
> I do find you have to recreate it fairly often (with `pipenv` anyway). But still worth it.

I normally use venv, which does not appear to have this problem.

**Comment by asmorkalov** [comment]
Fixed in:
- https://github.com/opencv/opencv/pull/20370
- https://github.com/opencv/opencv-python/pull/853

**Comment by Gornoka** [comment]
Thanks a @asmorkalov lot for working on a fix for that, do you happen to know when we can expect the next release of the Python package?

**Comment by asmorkalov** [comment]
In good luck - next week.  Main OpenCV release will happen first, OpenCV-Python in a couple of days.
