### ISSUE TITLE
Can't open 3 simulataneous videocaptures over USB hub

### ISSUE THREAD

**Issue by UncleBob125** [skvark/opencv-python#827]
Hi,

I'm trying to connect 3 camera's for object detection over a USB hub.
When I try to open them 1 by 1 over the USB hub , they all work.
But when I try to open all 3 streams at the same time only 2 out of 3 work.
The 3rd one always gives False, None on the VideoCapture.read()

When I connect them to my PC in different USB ports it also works, but not over the USB hub.

So I'm aware that it's a problem related to the hub and not directly to opencv.
But would like to know how I can see what the issue is.
I've tried to lower the FPS as well, to limit bandwidth, but that doesn't seem to be the issue.
I've tried 3 different types of USB hubs 2.0 / powered 2.0 & 3.0, none of them work.

Can anyone give me any direction or tell me how I could use the opencv library to investigate why it's not working?
I'm not getting any errors, warning or info at the moment, so difficult to debug.

Any help would be greatly appreciated.

Thanks!

**Comment by asmorkalov** [comment]
Looks like it's some power or speed limitation of your hub. What I've tried on your side:
- Use hub with external power. Do not relay on host USB.
- Use mjpeg for cameras, if it's possible. It's loosy compression, but it can dramatically reduce USB load, if it's supported by cameras

**Comment by asmorkalov** [comment]
Please use forum.opencv.org for such kind of questions and discussions.
