### ISSUE TITLE
cv2.imwrite() does not throw an exception when a dir does not exist, resulting in silent failure

### ISSUE THREAD

**Issue by danglingptr0x0** [skvark/opencv-python#832]
### Expected behaviour

I expected the library to either raise an error when the output directory does not exist or to create the directory automatically when using the cv2.imwrite() function.

### Actual behaviour

The cv2.imwrite() function does not raise any error or create the directory if it does not exist, resulting in a silent failure.

### Steps to reproduce

```python
import cv2

# Read an image file
img = cv2.imread('path/to/input/image.jpg')

# Attempt to save the image to a non-existent directory
cv2.imwrite('path/to/non_existent_directory/output.jpg', img)
```

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
OpenCV `cv2.imwrite` returns boolean value with status, but does not throw exceptions: https://docs.opencv.org/4.x/d4/da8/group__imgcodecs.html#gabbc7ef1aa2edfaa87772f1202d67e0ce
