### ISSUE TITLE
opencv-python-aarch64 cp35

### ISSUE THREAD

**Issue by jiangyuhe123** [skvark/opencv-python#84]
### Expected behaviour
Do you have opencv-python-aarch64 for python 3.5 version running on aarch64 device, like Jetson TX2 with jetpack 3.2

### Actual behaviour
I only found opencv-python-aarch64 3.3.0.1 with cp34 on https://pypi.org/project/opencv-python-aarch64/#files

I hope you can help me on this since Jetpack 3.2 are in cp35 platform.

Thanks,
Michael

**Comment by skvark** [comment]
Sorry, I don't maintain any aarch64 releases. I have no idea who is https://pypi.org/user/microsoft-ell/.
