### ISSUE TITLE
How about make opencv-python depend on dynamic link library of opencv

### ISSUE THREAD

**Issue by wqh17101** [skvark/opencv-python#845]
For now, you use `"-DBUILD_SHARED_LIBS=OFF"` when building opencv-python.

There is one scene that I have a .so which depends on dynamic link library of opencv,  and a .py which depends on opencv-python 
 which depends on dynamic link library of opencv. 

So in this scene , i will need to install two kinds of the same opencv —— dynamic for  c and static which is in the opencv-python for python.

How about make opencv-python depend on dynamic link library of opencv? Thus in above scene, i will only install opencv-python which depends on dynamic link library of opencv once to work well instead of two,

**Comment by asmorkalov** [comment]
OpenCV-Python is linked statically with main OpenCV intentionally:
- It resolves issues with environment setup to find all modules.
- There are no issues with modules version mix.
- Statically linked version is slightly smaller than dynamic one.

There is no ideal solution, but I see two options:
- Just build OpenCV from main repo and do `make install`. You'll gen Dynamic OpenCV installed and it's available to Python. The drawback - it's not registered in pip.
- Hack source code of opencv-python repo and build dynamically. In this case you do not get source cede and headers for the built package. Dynamic linkage against it could be dangerous (versions, build flags, dependencies resolution, etc).
