### ISSUE TITLE
write video with opencv 

### ISSUE THREAD

**Issue by martin0496** [skvark/opencv-python#846]
Hello 

I tried to write a video using a sequence of images using : out = cv2.VideoWriter('sequencemjpg.mp4',cv2.VideoWriter_fourcc('P','I','M','1'), 5 , frameSize)

The video is saved correctly with 5 fps as I mentioned. 
The problem occurs when I try to load it back, It plays too fast.

This is the code I am using for loading: 

**import cv2
import numpy as np
 
# Create a VideoCapture object and read from input file
# If the input is the camera, pass 0 instead of the video file name
cap = cv2.VideoCapture(r"sequence.mp4")
 
# Check if camera opened successfully
if (cap.isOpened()== False): 
  print("Error opening video stream or file")
 
# Read until video is completed
while(cap.isOpened()):
  # Capture frame-by-frame
  ret, frame = cap.read()
  if ret == True:
 
    # Display the resulting frame
    cv2.imshow('Frame',frame)
 
    # Press Q on keyboard to  exit
    if cv2.waitKey(25) & 0xFF == ord('q'):
      break
 
  # Break the loop
  else: 
    break
 
# When everything done, release the video capture object
cap.release()
 
# Closes all the frames
cv2.destroyAllWindows()**

I just want to understand how to create the video and load it back with the same fps rat I fixed during creation

**Comment by Sunilstar-V** [comment]
Hey I think I can complete it could you assign it to me

**Comment by asmorkalov** [comment]
`if cv2.waitKey(25) & 0xFF == ord('q'):` this line makes 25ms delay between frames. OpenCV itself does not introduce delays.
