### ISSUE TITLE
Running cv2.videoCapture("rtsp://xxxx") and show is slow in  Multi-core CPU.

### ISSUE THREAD

**Issue by Dxymiemiemie** [skvark/opencv-python#847]
### Expected behaviour

Write here how did you expect the library to function.
`import cv2

cv2.namedWindow("enhanced",0)
cv2.resizeWindow("enhanced", 1920, 1080)

if __name__=="__main__":
    from multiprocessing import cpu_count
 
    addr="rtsp://xxxx"
    cap = cv2.VideoCapture(addr)    
    cap.set(cv2.CAP_PROP_BUFFERSIZE, 2)
    
        
    print("Number of CPUs:", cv2.getNumberOfCPUs())
    print("Number of threads:", cv2.getNumThreads())
    
    while True:
        ret, frame = cap.read()

        if not ret:
            print("break")
            break

        cv2.imshow('enhanced', frame)
        

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

        del(ret)
        del(frame)

    cap.release()
    cv2.destroyAllWindows()`
### Actual behaviour
system information:

- windows server 2016 CPU: E5 2696 v4 (22 cores 44thread support) 
- software tools: Virtual Box and VMware workstation16

Write here what went wrong.
when I allocate multiple Cores in virtal mechine  compared with single Core running the same code above.
I find the it is faster with less core. And more you allocate the cores the slower it is.
I also tried on my Laptop with AMD R7-6800H and get the same result.
I put the pictures here show the actual delay time VS webcam official webset

1. with multiple cores on my Laptop.
![5b20e64fed4b58f3557451add8b32f9](https://github.com/opencv/opencv-python/assets/71275391/c10c51d9-9d27-4bdb-8ea4-5bd7aba1a576)

2. with less Cores on my Lartop
![924ebdfd57ced77059a48ac1cd18807](https://github.com/opencv/opencv-python/assets/71275391/27519763-5433-4ccd-ac98-866e92aa0c5f)

### Steps to reproduce

- opencv-python version : 4.6.0.66

I have found some suggestions that to build wheels of opencv to support TBB or openMP ,Is it true?
I want to make it out .Any one can give me some advice?
The delay is unbearable
By the way ,on the server with E5 2696 v4 ,it is very slow (almost 3 seconds delayy) with all cores,but it is much faster in the virtual mechaine with less cores. And I tried two virtual mechaine software (VirtualBox and VMware) I think it is not the reason of softeare.

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
Related issue in main OpenCV repo: https://github.com/opencv/opencv/pull/22248
Related fix in main repo: https://github.com/opencv/opencv/pull/23014
Summary:  OpenCV sets cocurrency options to FFmpeg and forced it to use as many cores as possible. It's not efficient. OpenCV 4.7.0 limited it to 16 cores and introduced option to tune FFmpeg consumption.
