### ISSUE TITLE
Cannot open cv2.VideoCapture() with rtsp if there is a # in the password

### ISSUE THREAD

**Issue by pkinnane** [skvark/opencv-python#848]
As per the title.  If there is a '#' in the RTSP password, calling VideoCapture returns an error "[tcp @ 0x227f500] Port missing in uri" even when port 554 is specified.  This is on a HIK camera.  Setting the password to something without a '#' fixes the issue.  

opencv-python Version: 4.7.0.72

Thanks

Paul

**Comment by asmorkalov** [comment]
OpenCV uses FFmpeg and other backends for video decoding. FFmpeg and others use common rules for URLs as browser and other network tools. See https://stackoverflow.com/questions/22544219/how-do-i-use-special-characters-password-on-the-url-when-dealing-with-http-aut and https://www.w3schools.com/tags/ref_urlencode.ASP
