### ISSUE TITLE
Running into trouble trying to complile opencv-python with GPU support.

### ISSUE THREAD

**Issue by Richzrich** [skvark/opencv-python#850]
I am using Ubuntu 20.04 and I want to to compile opencv-python with GPU support and gstreamer support. I have a GTX-1660 Ti GPU with Cuda-11.2 and cuDnn 8.9.0 installed. When I try to configure the cmake command for this I get an error indicating that it is not able to find my cuDNN installation.

The exact cmake command I used is this:

```
cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D INSTALL_C_EXAMPLES=OFF \
-D OPENCV_ENABLE_NONFREE=ON \
-D WITH_CUDA=ON \
-D WITH_CUDNN=ON \
-D OPENCV_DNN_CUDA=ON \
-D ENABLE_FAST_MATH=1 \
-D CUDA_FAST_MATH=1 \
-D CUDA_ARCH_BIN=7.5 \
-D WITH_CUBLAS=1 \
-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
-D HAVE_opencv_python3=ON \
-D PYTHON_EXECUTABLE=/usr/bin/python3 \
-D BUILD_EXAMPLES=ON \
-D WITH_GSTREAMER=ON ..

```

The error I get is this:

```
CMake Error at modules/dnn/CMakeLists.txt:56 (message):
  DNN: CUDA backend requires cuDNN.  Please resolve dependency or disable
  OPENCV_DNN_CUDA=OFF
```

I used pytorch and tensorflow-gpu to verify if my cuDNN is available with a positive output like so:

```
import torch
print(torch.backends.cudnn.is_available()) # This prints out as True
```

and

```
import tensorflow as tf
print(tf.test.is_built_with_cuda())  # This prints out True
print(tf.config.list_physical_devices('GPU')) # This shows my GPU
```

I'm obviously doing something wrong, but could somebody help pointing me in the right direction how to resolve this issue??

**Comment by asmorkalov** [comment]
CuDNN was not found on your host during build. In case if you install CuDNN as apt package, please ensure that all related `-dev` packages are installed.

**Comment by Richzrich** [comment]
I downloaded CuDNN from the official Nvidia site in the .tar folder version and unpacked and installed it per the instructions ... :(

**Comment by soloist-tech** [comment]
How did you come up with this cmake command? I'm curious where I can find all those flags you are using.

**Comment by asmorkalov** [comment]
OpenCV CMake scripts expects CuDNN installed to the same location as CUDA toolkit. Please ensure CuDNN location. In case of issue, please use https://forum.opencv.org for questions.
