### ISSUE TITLE
Help with building opencv-python with non-free modules in vs code

### ISSUE THREAD

**Issue by aadinesarkar** [skvark/opencv-python#858]
### Expected behaviour

Expected opencv-contrib-python wheel package to be created in dist in visual studio code.

### Actual behaviour

scikit-build could not get a working generator for your system. Aborting build.

Building windows wheels for Python 3.11 requires Microsoft Visual Studio 2022.
Get it with "Visual Studio 2017":

### Steps to reproduce

#306 [comment](https://github.com/opencv/opencv-python/issues/306#issuecomment-605416796)

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by aadinesarkar** [comment]
Can non-free modules not be installed without using visual studio?

**Comment by asmorkalov** [comment]
Related https://github.com/opencv/opencv-python/pull/831

**Comment by asmorkalov** [comment]
OpenCV uses scikit-build infrastructure for C++ code. It supports `CMAKE_ARGS` environment variable to provide custom CMake options. 
See: 
- https://github.com/scikit-build/scikit-build/issues/479
- https://github.com/scikit-build/scikit-build/issues/588

For example, if you want to build OpenCV-Python  package from sources for Linux and enable OpenVINO and GStreamer:
```
 export CMAKE_ARGS="-DWITH_OPENVINO=ON -DWITH_GSTREAMER=OFF"
python3 setup.py bdist_wheel
```
