### ISSUE TITLE
[question] How to discover compiler / compiler flags user to build python bits in pypi

### ISSUE THREAD

**Issue by vadimkantorov** [skvark/opencv-python#879]
Hi!

I'm benchmarking `cv2.ximgproc.segmentation.createSelectiveSearchSegmentation` from `opencv-python` package (version 4.8.0) with manually compiled [`selectivesearchsegmentation.cpp` from opencv_contrib](https://github.com/opencv/opencv_contrib/blob/master/modules/ximgproc/src/selectivesearchsegmentation.cpp) linked to `libopencv_core.so` (from the ubuntu package, version 4.2.0). 

I'm compiling with `g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0`, using `-Ofast -shared -fPIC`. The manually compiled `.so` (I have a three-line wrapper in C++ exporting a single C function which I'm calling from python using `ctypes`) gives 2.2 seconds, while `cv2.ximgproc.segmentation.createSelectiveSearchSegmentation` gives 1.6 seconds. I'm using the same params for the both ways, so both ways produce equal number of proposal bboxes.

I'm benchmarking against manual compilation because I want to introduce some modifications in the future.

What could explain this difference? Why is opencv-python-contrib version faster than my manual one? :)

It might be nice if the build info (like the used compiler / flags were burned in the Python packge and accessible via some `cv2.__buildinfo__` or similar.

Thank you!

**Comment by asmorkalov** [comment]
cv.getBuildInformation() returns CMake status page, It contains information about compiler and all flags: https://docs.opencv.org/4.x/db/de0/group__core__utils.html#ga0ae377100bc03ce22322926bba7fdbb5
