### ISSUE TITLE
I'm looking for the buildMaps() and remap() functions in cv2 namespace.

### ISSUE THREAD

**Issue by KrisJe** [skvark/opencv-python#883]
### Expected behaviour

I'm looking for the buildMaps() and remap() functions in cv2 namespace. This is to optimize the Warp perspective.
See issue: https://github.com/opencv/opencv/issues/4324

### Actual behaviour

Unavailable feature

##### Issue submission checklist

 - [x ] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)

**Comment by asmorkalov** [comment]
The related issue has a solution for you.
