### ISSUE TITLE
AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'

### ISSUE THREAD

**Issue by fa9r** [skvark/opencv-python#886]
Hey, I just encountered a very weird error when running some integration tests inside Docker containers, which I'm guessing is somehow related to the new [4.8.0.76 release](https://github.com/opencv/opencv-python/releases/tag/76) since the error is raised inside the new `cv2.typing` module. Note that I'm using an older cv2 version (`4.5.5.64`), not the new release itself.

The specific test passes when I run it locally but fails once I run it inside a Docker container during `import cv2`. See stack trace below:

<img width="485" alt="Screenshot 2023-08-10 at 10 41 09" src="https://github.com/opencv/opencv-python/assets/23118541/b03ba5da-dbdc-4602-8c6f-6868e60edb26">

### Expected behaviour

`import cv2` works inside Docker containers for older `opencv-python` versions

### Actual behaviour

See stacktrace above.

### Steps to reproduce

- example code: `import cv2` inside a Docker container
- operating system: doesn't matter, happens under both MacOS and Linux
- architecture (e.g. x86)
- opencv-python version: 4.5.5.64 (installed under Python 3.8)

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by VadimLevin** [comment]
I'm a bit confused...
You are using new release inside Docker environment or 4.5.5.64 version? How you get typing module in 4.5.5.64?
Have you installed OpenCV from PyPi or use custom build?

**Comment by fa9r** [comment]
I'm also confused 😅

I'm installing `"deepchecks[vision]==0.8.0"` via PyPi which depends on `opencv-python<4.6.0.66 and >=4.5.5.62` and in turn installs `opencv-python-4.5.5.64`. Also no clue where the typing module is coming from and why it only happens in Docker environments. I'm still investigating this myself at the moment to find a workaround, will let you know if I find any more concrete/helpful info.

**Comment by fa9r** [comment]
I don't exactly know why, but explicitly pinning both `opencv-python` and `opencv-python-headless` to the same version fixed this for me. My guess is that `opencv-python-headless` is required for some dependency of our Docker images which then clashed with the older `opencv-python` version. In any case, the issue was on my side so I'm closing this.
