### ISSUE TITLE
Who can help me? I want to use opencv dnn, I need compiler opencv-python wheel with cuda-10.2

### ISSUE THREAD

**Issue by stu-github** [skvark/opencv-python#897]
### Expected behaviour

I need compiler opencv-python wheel with cuda-10.2

### Actual behaviour

In file included from /usr/local/cuda/include/cuda_runtime.h:83,
                   from <command-line>:
  /usr/local/cuda/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
    138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
        |  ^~~~~

### Steps to reproduce

1.  git clone --recursive https://github.com/opencv/opencv-python.git

2.  docker run -it --gpus all --privileged=true --user root -v /home/dnn/opencv-python:/opencv-python -v /usr/local/cuda-10.2:/usr/local/cuda --name test02 quay.io/opencv-ci/opencv-python-manylinux2014-x86-64:20230628 /bin/bash

3.  export ENABLE_HEADLESS=1
    export VERBOSE=1
   export CMAKE_ARGS="-DWITH_CUDA=ON -DWITH_CUDNN=ON -DOPENCV_DNN_CUDA=ON -DBUILD_opencv_python2=OFF"
   export ENABLE_CONTRIB=0

4.  /usr/local/bin/python3.8 -m pip wheel . --verbose

**Comment by asmorkalov** [comment]
```
#error -- unsupported GNU version! gcc versions later than 8 are not supported!
```
This is CUDA 10.2 limitation. You need to update CUDA or downgrade the compiler.
