### ISSUE TITLE
Which version of opencv-python should I use with opencv 4.6.0

### ISSUE THREAD

**Issue by shirha** [skvark/opencv-python#898]
Hi,
I'm installing Anaconda 2023.07 (Win10) and it has Python 3.11 and opencv 4.6.0. Can I use opencv-python 4.8.0.76 or should I use ONLY opencv-python 4.6.0.66?

Thanks in advance for your consideration
shirha

**Comment by asmorkalov** [comment]
OpenCV team does not build package for Conda. They are handled by Conda community. Pip package works with  Python11 since 4.7.0.68.
