### ISSUE TITLE
Wrong FPS with 4.8.0.76 but not with 4.7.0.72

### ISSUE THREAD

**Issue by ChrCoello** [skvark/opencv-python#899]
### Expected behaviour
We are expecting to get FPS = 10, as we get with opencv-python 4.7.0.72
```python
import cv2
cap = cv2.VideoCapture('C:\\data\\raw\\avd13_cam6_20221112190637_20221112195338.mp4')
print(cap.get(cv2.CAP_PROP_FPS))
```
prints 10.0

### Actual behaviour

When using the latest version of opencv-python 4.8.0.78, we get 25.
```python
import cv2
cap = cv2.VideoCapture('C:\\data\\raw\\avd13_cam6_20221112190637_20221112195338.mp4')
print(cap.get(cv2.CAP_PROP_FPS))
```
prints 25.0

### Steps to reproduce

Video codec information from VLC
![image](https://github.com/opencv/opencv-python/assets/11834181/dad1788b-df8a-48e8-ba74-40e0f3e02606)

- minimal example code
```python
import cv2
cap = cv2.VideoCapture('C:\\data\\raw\\avd13_cam6_20221112190637_20221112195338.mp4')
print(cap.get(cv2.CAP_PROP_FPS))
```

- operating system
Python in Windows

- architecture (e.g. x86)

- opencv-python version
4.7.0.72
4.8.0.78

**Comment by opencv-alalek** [comment]
Probably related to https://github.com/opencv/opencv/pull/23692 and https://github.com/opencv/opencv/issues/21006

/cc @asmorkalov @wangwei1237

---

Minimal reproducer should include input data to be complete (try to capture non-sensitive data and upload them).

**Comment by alaskax8** [comment]
Is there any update on this issue? I am experiencing something similar with some videos. OpenCV is giving me a fps value of 90000 for them though it should be around 120fps.

**Comment by ChrCoello** [comment]
@asmorkalov here is a video (https://wetransfer.com/downloads/e5616cfcd00fb63ebebb934ce6b59f4820231102152901/a8e98d) where this error can be reproduced. Using 4.7.0.72 you get 10fps (correct), using 4.8.0.76 you get 25 fps (incorrect)

**Comment by asmorkalov** [comment]
Related patch: https://github.com/opencv/opencv/pull/23692
FFmpeg allows to get FPS for entire video and particular stream inside the video. Olerall FPS: 25, stream FPS: 10. Looks like we need to re-prioritize source of truth in out implementation.
