### ISSUE TITLE
Is there a way to use cv2 without libsm6?

### ISSUE THREAD

**Issue by akmalhakimi1991** [skvark/opencv-python#90]
Hi. I'm developing a Python facial recognition program in a robot called NAO. I'm using `opencv` to crop face out of the picture. I have written the facial recognition program that works fine in my VM (running in Ubuntu). However, when I try to run the program in NAO robot, it shows error message:  

> ImportError: libSM.so.6: cannot open shared object file: No such file or directory

**Comment by skvark** [comment]
I will publish soon two new headless distributions which don't depend on libSM: ``opencv-python-headless`` and ``opencv-contrib-python-headless``. Meanwhile you can downgrade your version to 3.3.0.9 which does not include any GUI dependencies. See: https://github.com/skvark/opencv-python/issues/44

**Comment by gilv** [comment]
@skvark hit the same issue..did you release opencv-contrib-python-headless already? thanks
