### ISSUE TITLE
Module "cv2" does not explicitly export attribute "typing"

### ISSUE THREAD

**Issue by rassie** [skvark/opencv-python#901]
### Expected behaviour

Type hints (e.g. with `mypy`) work properly on `cv2.imdecode`

### Actual behaviour

`cv2.imdecode` return values resolve to `Any`.

### Steps to reproduce

* create a clean project with `opencv-python-headless` 4.8.0.76 and `mypy` 1.5.1
* add a `main.py` with the following code:
```
import cv2

reveal_type(cv2.typing.MatLike)
reveal_type(cv2.imdecode)
```
* run `mypy` on `main.py`
* observe the following:
```
main.py:3: error: Module "cv2" does not explicitly export attribute "typing"  [attr-defined]
main.py:3: note: Revealed type is "Any"
main.py:4: note: Revealed type is "Overload(def (buf: Any, flags: builtins.int) -> Any, def (buf: cv2.UMat, flags: builtins.int) -> Any)"
```

It seems like the original override definition 
```
@typing.overload
def imdecode(buf: cv2.typing.MatLike, flags: int) -> cv2.typing.MatLike: ...
@typing.overload
def imdecode(buf: UMat, flags: int) -> cv2.typing.MatLike: ...
```
can't resolve `cv2.typing.MatLike` and replaces it by `Any`. The reason seems to be the error message `Module "cv2" does not explicitly export attribute "typing"`.

##### Issue submission checklist

 - [X] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [X] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [X] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [X] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
Thanks a lot for the issue report. Most probably the issue has been resolved in OpenCV 4.x branch and the fix will be released in 4.9.0. Could you try current 4.x branch?
Possibly related PRs:
- https://github.com/opencv/opencv/pull/23972
- https://github.com/opencv/opencv/pull/23958
- https://github.com/opencv/opencv/pull/23956
- https://github.com/opencv/opencv/pull/23927

**Comment by rassie** [comment]
@asmorkalov Gladly! How do I do that properly? Do I just build a wheel from this repository or is this a more involved process?

**Comment by rassie** [comment]
I've taken a wheel out of https://github.com/opencv/opencv-python/actions/runs/6221534986 (`opencv_python_headless-4.8.0+8621b7c-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`) and tried running my test case. Sadly, it's the same problem again, so if that wheel is the right one, I'd have to assume the problem is not fixed in the newest branch.

**Comment by rassie** [comment]
Or maybe that's the wrong branch, let me check...

**Comment by rassie** [comment]
Same result with `opencv_python_headless_rolling-4.8.0.76-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` from https://github.com/opencv/opencv-python/actions/runs/6204924813.

**Comment by Avasam** [comment]
This is a static type-checking error saying that the module `cv2` does seem to have an existing symbol `typing`. But it doesn't seem to be intended to be re-exported. (pyright flat out gives a `"typing" is not a known member of module "cv2"`, mypy is a bit clearer here)

Big edit: scrap that. It's a mypy issue. it gets confused between the cv2 module importing `typing` and `cv2.typing` being its own module.

pyright handles it correctly.

```py
import cv2
import cv2.typing

_ = cv2.typing.MatLike  # Module "cv2" does not explicitly export attribute "typing" Mypy([attr-defined](https://mypy.readthedocs.io/en/latest/_refs.html#code-attr-defined))
```

Edit 2: Created issue: https://github.com/python/mypy/issues/16216
In the meantime, opencv **could** work around the issue by aliasing `typing` in `cv2`: `import typing as _typing` (https://github.com/opencv/opencv/issues/24352). I think whether mypy is updated to handle that case, it would probably a change for the better in opencv

**Comment by rassie** [comment]
Thanks, guys! Will try to test it this week!

**Comment by rassie** [comment]
@asmorkalov @VadimLevin @Avasam I have built the wheels and can confirm it's working as expected! Thank you very much!
