### ISSUE TITLE
OpenCV Python Wheel Build Issue: `cv2` Missing Methods After Building from Source

### ISSUE THREAD

**Issue by WoodieDudy** [skvark/opencv-python#909]
After building OpenCV Python wheel from source, the `cv2` module seems to be missing its expected methods. When inspecting the module methods using `dir(cv2)`, only the default Python module methods are returned.

**Steps to Reproduce**:
1. Built the OpenCV Python wheel using the following Dockerfile:
```Dockerfile
FROM python:3.10

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install --no-install-recommends -y build-essential gcc software-properties-common curl

RUN apt-get install -y curl cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libtbbmalloc2 \
                     libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-dev

RUN python3.10 -m pip install --upgrade pip
RUN python3.10 -m pip install --upgrade wheel setuptools requests

ENV OPENCV_VERSION=4.8.1

WORKDIR /opencv

RUN git clone --recurse-submodules https://github.com/opencv/opencv-python.git
WORKDIR /opencv/opencv-python

RUN python3.10 -m pip install numpy

ENV CMAKE_ARGS="-D BUILD_SHARED_LIBS=OFF -D CMAKE_BUILD_TYPE=RELEASE -D WITH_FFMPEG=ON -D BUILD_opencv_python3=ON"
ENV ENABLE_HEADLESS=1
RUN python3.10 -m pip wheel . --verbose
```

2. Entered the container to install the built wheel:
```bash
pip install opencv_python_headless-4.8.1+7cfd1ee-cp310-cp310-linux_x86_64.whl
```

3. Checked available methods:
```python
import cv2
print(dir(cv2))
```

**Expected Behavior**:
The `cv2` module should have its usual methods available.

**Actual Behavior**:
Only the default Python module methods were returned:
`['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']`

**Additional Question**:
I want to ensure that OpenCV is built with support for the `avc1` codec and that no additional installations are required on the target system. I believe that adding the flags `-D BUILD_SHARED_LIBS=OFF -D WITH_FFMPEG=ON` will statically link the required libraries. Can you confirm or provide corrections if I'm mistaken?

**Comment by Mattral** [comment]
I guess, the issue you are facing with the missing methods in the `cv2` module seems to be related to the way you built OpenCV and installed it. It appears that your custom build of OpenCV might not be providing the expected Python bindings. To address this, you can try the following steps:

1. Ensure you have the necessary dependencies installed:

   Your Dockerfile lists several dependencies, which is a good start. However, OpenCV might have additional dependencies or requirements depending on the functionality you need. Make sure you have installed all the necessary dependencies for your specific use case.

2. Verify your build process:

   The process of building OpenCV can be complex, and any misconfiguration can lead to missing features or bindings. Double-check that your CMake options and build process are correctly configured. In your Dockerfile, you have set `CMAKE_ARGS` and `ENABLE_HEADLESS`, but these might need adjustments depending on your specific requirements.

3. Clean the build and rebuild OpenCV:

   Sometimes, issues can arise if there were problems during the initial build process. Try cleaning your build directory and rebuilding OpenCV:

   ```bash
   rm -r /opencv/opencv-python/build
   python3.10 -m pip wheel . --verbose
   ```

4. Verify the Python version and OpenCV version compatibility:

   Ensure that the Python version you are using (Python 3.10 in this case) is compatible with the version of OpenCV you are building. OpenCV might have some version-specific differences in its Python bindings.

Regarding your additional question about building OpenCV with support for the `avc1` codec, you are on the right track with the CMake option `-D WITH_FFMPEG=ON`. This option enables support for FFmpeg, which includes many codecs, including `avc1`. By statically linking the required libraries using `-D BUILD_SHARED_LIBS=OFF`, you can create a self-contained OpenCV package that includes the necessary FFmpeg support.

**Comment by kokamido** [comment]
It looks like the described behavior caused by the `/opencv/opencv-python/cv2` folder. Python treats it as a cv2 package if python is runing in `WORKDIR /opencv/opencv-python`

![image](https://github.com/opencv/opencv-python/assets/7046074/a7b3166a-f831-4c1a-8691-8da3800d39b2)

**Comment by WoodieDudy** [comment]
Oh, really
Thanks
