### ISSUE TITLE
Pycharm import still not happy (but almost there)

### ISSUE THREAD

**Issue by leogout** [skvark/opencv-python#91]
### Steps to reproduce
Create a new project, install cv2 with `pip install opencv-python`, try to import and use `cv2.[anything]()`

### Possible solution
Hi, I think I've localized the problem in the file `my_project/my_venv/cv2/cv2/__init__.py`
```python
# encoding: utf-8
# module cv2.cv2
# from /project_home/venv/lib/python3.6/site-packages/cv2/cv2.cpython-36m-x86_64-linux-gnu.so
# by generator 1.145
""" Python wrapper for OpenCV. """

# imports
import cv2.cv2 as # HERE IS THE PROBLEM, missing the "cv2" after the "as". Adding it fixes the issue
import cv2.Error as Error # <module 'cv2.Error'>
# ...
```
Unfortunately I couldn't find where this file is located so i guess it's generated. I don't even know if you can do something about it in your repo.

Cheers!

**Comment by skvark** [comment]
The file looks like something that was generated by PyCharm. There's nothing I can do if PyCharm doesn't understand the import since to my knowledge there's no other way to do the import properly and retain backward compatibility. 

Note that the import was different in versions < 3.3.0.9 and those versions had issues at least with PyCharm. Can you double check that you are running the latest version of ``opencv-python``?

**Comment by leogout** [comment]
Of course! Here it is:
![screenshot from 2018-05-11 09-59-59](https://user-images.githubusercontent.com/9843962/39913439-26c8e558-5502-11e8-8889-fd156c63327f.png)
Do you mind if i keep this open to show it to the PyCharm team (if i manage to contact them)?

**Comment by leogout** [comment]
Oh actually there it is: https://youtrack.jetbrains.com/issue/PY-24535
Someone already did the job :) i'll close this one then, cheers !

**Comment by jirislav** [comment]
Could you guys please vote up the JetBrains issue? It's 2 years old already and still seems it has zero progress :/

**Comment by fatalfeel** [comment]
windows

//If cannot import name 'cv2'
C:\Program Files\Python35\Lib\site-packages\cv2\cv2.cp35-win_amd64.pyd (it is a dll)
copy to
C:\Program Files\JetBrains\PyCharm 2019.x.x\helpers\pydev


linux

//If cannot import name 'cv2'
/usr/local/lib/python3.5/dist-packages/cv2/cv2.cpython-35m-x86_64-linux-gnu.so
copy to
/opt/pycharm-2019.x.x/helpers/pydev/cv2.cpython-35m-x86_64-linux-gnu.so

.so lib path
Run > Edit Configurations:
[Environment Variables]
add
LD_LIBRARY_PATH=/usr/local/lib/python3.5/dist-packages/cv2/.libs

will be done and ok
I try this, use almost 24 hours   by Jesse Stone

**Comment by fatalfeel** [comment]
windows

//If cannot import name 'cv2'
C:\Program Files\Python35\Lib\site-packages\cv2\cv2.cp35-win_amd64.pyd (it is a dll)
copy to
C:\Program Files\JetBrains\PyCharm 2019.x.x\helpers\pydev


linux

//If cannot import name 'cv2'
/usr/local/lib/python3.5/dist-packages/cv2/cv2.cpython-35m-x86_64-linux-gnu.so
copy to
/opt/pycharm-2019.x.x/helpers/pydev/cv2.cpython-35m-x86_64-linux-gnu.so

.so lib path
Run > Edit Configurations:
[Environment Variables]
add
LD_LIBRARY_PATH=/usr/local/lib/python3.5/dist-packages/cv2/.libs

will be done and ok
I try this, use almost 24 hours   by Jesse Stone
