### ISSUE TITLE
Could not find encoder for codec_id=173, error: Encoder not found

### ISSUE THREAD

**Issue by Miho-an-kou** [skvark/opencv-python#912]
### Expected behaviour

For privacy and security reasons, I want to overwrite the osd information in the video. At first I used the mp4v codec uniformly to save the processed videos, but found that the saved videos were sometimes much larger than the original videos. Then I want to read the codec of the original video and save the video with the original codec to solve the problem.

### Actual behaviour
output:
Codec of Video:1.mp4 is hvc1
[ERROR:0@325.304] global /croot/opencv-suite_1691620365762/work/modules/videoio/src/cap_ffmpeg_impl.hpp (2927) open Could not find encoder for codec_id=173, error: Encoder not found
[ERROR:0@325.304] global /croot/opencv-suite_1691620365762/work/modules/videoio/src/cap_ffmpeg_impl.hpp (3002) open VIDEOIO/FFMPEG: Failed to initialize VideoWriter

(python:1060085): GStreamer-CRITICAL **: 09:55:15.776: gst_element_make_from_uri: assertion 'gst_uri_is_valid (uri)' failed
[ WARN:0@325.304] global /croot/opencv-suite_1691620365762/work/modules/videoio/src/cap_gstreamer.cpp (2067) open OpenCV | GStreamer warning: OpenCV backend does not support passed FOURCC value
[ WARN:0@325.304] global /croot/opencv-suite_1691620365762/work/modules/videoio/src/cap_gstreamer.cpp (1813) close_ OpenCV | GStreamer warning: No source in GStreamer pipeline. Ignore

### Steps to reproduce

- example code
from pathlib import Path

import cv2
from loguru import logger

def decode_fourcc(cc):
    return "".join([chr((int(cc) >> 8 * i) & 0xFF) for i in range(4)])

def cover(video_dir: Path, coordinates: list):
    """

    Args:
        video_dir:
        coordinates:

    Returns:

    """
    new_dir = video_dir / "Covered"
    new_dir.mkdir(exist_ok=True)
    for video_p in video_dir.iterdir():
        cap = cv2.VideoCapture(str(video_p))
        fps = cap.get(cv2.CAP_PROP_FPS)
        w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        frame_num = cap.get(cv2.CAP_PROP_FRAME_COUNT)
        codec_int = int(cap.get(cv2.CAP_PROP_FOURCC))
        codec_str = decode_fourcc(codec_int)
        logger.info(f"Codec of Video:{video_p} is {codec_str}")
        new_video_path = new_dir / video_p.name
        video_writer = cv2.VideoWriter(str(new_video_path), cv2.VideoWriter_fourcc(*codec_str), fps, (w, h))
        n = 0
        while cap.isOpened() and n <= frame_num - 1:
            ret, img = cap.read()
            if not ret:
                n += 1
                logger.warning(f"Video:{video_p} ({n}/{frame_num} frame) read failed")
            else:
                for coordinate in coordinates:
                    img[coordinate[1] : coordinate[3], coordinate[0] : coordinate[2]] = 0
                video_writer.write(img)
                n += 1
                logger.info(f"Video:{video_p} ({n}/{frame_num} frame) written to {new_video_path}.")
        else:
            logger.info(f"Process of Video:{video_p} complete!")
            cap.release()
            video_writer.release()

- operating system
Ubuntu 20.04
- architecture (e.g. x86)
x86_64
- opencv-python version
conda install -c conda-forge opencv
conda list:
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
blas                      1.0                    openblas    defaults
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               h5eee18b_0    defaults
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cairo                     1.16.0               hb05425b_5    defaults
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
charset-normalizer        2.0.12                   pypi_0    pypi
cyrus-sasl                2.1.28               h9c0eb46_1    defaults
dbus                      1.13.18              hb2f20db_0    defaults
eigen                     3.4.0                h4bd325d_0    conda-forge
expat                     2.5.0                h6a678d5_0    defaults
ffmpeg                    4.2.2                h20bf706_0    defaults
fontconfig                2.14.1               h4c34cd2_2    defaults
freetype                  2.10.4               h0708190_1    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.69.1               h4ff587b_1    defaults
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.15               he1e5248_0    defaults
graphite2                 1.3.14               h295c915_1    defaults
gst-plugins-base          1.14.1               h6a678d5_1    defaults
gstreamer                 1.14.1               h5eee18b_1    defaults
harfbuzz                  4.3.0                hf52aaf7_1    defaults
hdf5                      1.12.1          nompi_h2750804_100    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      3.3                      pypi_0    pypi
jpeg                      9e                   h166bdaf_1    conda-forge
krb5                      1.20.1               h568e23c_1    defaults
lame                      3.100             h7f98852_1001    conda-forge
ld_impl_linux-64          2.38                 h1181459_1    defaults
lerc                      3.0                  h295c915_0    defaults
libblas                   3.9.0           15_linux64_openblas    conda-forge
libcblas                  3.9.0           15_linux64_openblas    conda-forge
libclang                  14.0.6          default_hc6dbbc7_1    defaults
libclang13                14.0.6          default_he11475f_1    defaults
libcups                   2.4.2                ha637b67_0    defaults
libcurl                   8.2.1                h91b91d3_0    defaults
libdeflate                1.17                 h5eee18b_1    defaults
libedit                   3.1.20221030         h5eee18b_0    defaults
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.12               h8f2d780_0    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgfortran-ng            13.2.0               h69a702a_0    conda-forge
libgfortran5              13.2.0               ha4646dd_0    conda-forge
libgomp                   11.2.0               h1234567_1    defaults
libidn2                   2.3.4                h5eee18b_0    defaults
liblapack                 3.9.0           15_linux64_openblas    conda-forge
libllvm14                 14.0.6               hef93074_0    defaults
libnghttp2                1.52.0               ha637b67_1    defaults
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.39               h5eee18b_0    defaults
libpq                     12.15                h37d81fd_1    defaults
libprotobuf               3.20.3               he621ea3_0    defaults
libssh2                   1.10.0               h37d81fd_2    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libtasn1                  4.19.0               h5eee18b_0    defaults
libtiff                   4.5.1                h6a678d5_0    defaults
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   1.41.5               h5eee18b_0    defaults
libvpx                    1.7.0                h439df22_0    defaults
libwebp                   1.3.2                h11a3e52_0    defaults
libwebp-base              1.3.2                h5eee18b_0    defaults
libxcb                    1.15                 h7f8727e_0    defaults
libxkbcommon              1.0.1                h5eee18b_1    defaults
libxml2                   2.10.4               hcbfbd50_0    defaults
libxslt                   1.1.37               h2085143_0    defaults
loguru                    0.6.0                    pypi_0    pypi
lxml                      4.9.1                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0    defaults
mysql                     5.7.24               he378463_2    defaults
ncurses                   6.4                  h6a678d5_0    defaults
nettle                    3.7.3                hbbd107a_1    defaults
numpy                     1.22.4                   pypi_0    pypi
opencv                    4.6.0            py38ha16400d_5    defaults
openh264                  2.1.1                h4ff587b_0    defaults
openjpeg                  2.4.0                h3ad879b_0    defaults
openssl                   1.1.1w               h7f8727e_0    defaults
pcre                      8.45                 h9c3ff4c_0    conda-forge
pillow                    9.1.1                    pypi_0    pypi
pip                       22.1.2           py38h06a4308_0    defaults
pixman                    0.40.0               h7f8727e_1    defaults
python                    3.8.13               h12debd9_0    defaults
python_abi                3.8                      2_cp38    conda-forge
qt-main                   5.15.2               h5b8104b_9    defaults
qt-webengine              5.15.9               hbbf29b9_6    defaults
qtwebkit                  5.212                h3fafdc1_5    defaults
readline                  8.1.2                h7f8727e_1    defaults
requests                  2.27.1                   pypi_0    pypi
setuptools                61.2.0           py38h06a4308_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
urllib3                   1.26.10                  pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0    defaults
x264                      1!157.20191217       h7b6447c_0    defaults
xz                        5.4.2                h5eee18b_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults
##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [ ] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
OpenCV does not implement video codecs by itself, but uses FFmpeg, GStreamer or other 3rdparty libraries for it. According to logs you use self-built OpenCV with FFmpeg and GStreamer enabled. Both of them do not have the required codec on board. Options:
- Install more plugins for GStreamer to get the required codec.
- Rebuild FFmpeg with extra options (enable GPL, non-free codecs, install exta FFmpeg dependnecies like libaom, etc)
