### ISSUE TITLE
module 'cv2' has no attribute 'xfeatures2d'

### ISSUE THREAD

**Issue by TuanBao0711** [skvark/opencv-python#922]
I'm trying use BRIEF in img matching but not work
self.matching = cv2.xfeatures2d.BriefDescriptorExtractor_create()
AttributeError: module 'cv2' has no attribute 'xfeatures2d'

My cv2 version is 4.8.1
>>> print(cv2.__version__)
4.8.1

Someone help me

**Comment by asmorkalov** [comment]
You need opencv_contrib package for it.
