### ISSUE TITLE
How to disable large amount of logging?

### ISSUE THREAD

**Issue by rolandblok** [skvark/opencv-python#924]
### Expected behaviour

I would expect that there is not so much logging

### Actual behaviour

When calling CV2 functions in python , there is copious amount of logging, This makes it hard to see real (caused by me) problems

### Steps to reproduce
> python
>>> import cv2
>>> cap = cv2.VideoCapture(1)
==> LOGGING see below

- operating system :windows 11
- architecture (x86, NVIDEA GeForceRTX3050Ti laptop)
- opencv-python version 
     - OpenCV version: 4.8.1
     - Python 3.10.11

### 
Logging:
[INFO] [DSH]  python3.10.exe
 [INFO] [DSH]  Creating WndMsg Listener Window
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Performing initializing sequence
 [INFO] [DSH]  Get MessageBus interface succeeded
 [WARN] [DSH]  MessageBus perform initialize in progress
 [WARN] [DSH]  MessageBus perform start in progress
 [INFO] [MBHB] Updating MB Status
 [INFO] [MBHB] Previous marked bus status : Reserved : 0 | Core : 0 | NvContainer Plugin : 0 | DShow Filter : 0 | Camera UI Backend : 0 | Audio UI Backend : 0 |
 [INFO] [MBHB] Bus connected. (5) peers connected : Audio UI Backend, Core, DShow Filter, NvContainer Plugin, Camera UI Backend
 [INFO] [MBHB] Marked joined / connected for module (1) Core
 [INFO] [MBHB] Marked joined / connected for module (2) NvContainer Plugin
 [INFO] [MBHB] Marked joined / connected for module (3) DShow Filter
 [INFO] [MBHB] Marked joined / connected for module (4) Camera UI Backend
 [INFO] [DSH]  Self joined the MessageBus
 [INFO] [MBHB] Marked joined / connected for module (5) Audio UI Backend
 [INFO] [DSH]  Request to get container state
 [INFO] [MBHB] Updated marked bus status  : Reserved : 0 | Core : 1 | NvContainer Plugin : 1 | DShow Filter : 1 | Camera UI Backend : 1 | Audio UI Backend : 1 |
 [INFO] [DSH]  Successfully fetched the GPU details
 [INFO] [DSH]  Released Adapter
 [INFO] [DSH]  Found matching GPU for CUDA and D3D
 [INFO] [DSH]  Chosen GPU for D3D: (1) NVIDIA GeForce RTX 3050 Ti Laptop GPU : 76679, 0
 [INFO] [DSH]  Request to start core exe
 [INFO] [DSH]  Core reported already running -- Verifying
 [INFO] [DSH]  Verified core exe started
 [INFO] [DSH]  Request to wait for core launch init
 [INFO] [DSH]  Core launch init is done
 [INFO] [DSH]  Request to post cmd for core init
 [INFO] [DSH]  Core initializing now
 [INFO] [DSH]  Initializing streaming output
 [INFO] [DSH]  Request query output resolution
 [INFO] [DSH]  Querying stream output successful. Params: 1920x1080@30/1
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
and much more...

**Comment by asmorkalov** [comment]
The mentioned logs are produced not by OpenCV, but some other app.

**Comment by AndreusUltimus** [comment]
@asmorkalov The logging itself might be coming from an included library and not directly from OpenCV, but these _do not appear_ unless particular calls are made to the OpenCV VideoCapture API, specifically on Windows.

These have appeared for me every time I've used VideoCapture on Windows for years, and I've never managed to make them go away. Using contextlib and redirecting stdout/stderr doesn't do it, and neither does messing with OPENCV_LOG_LEVEL. At least you've given me a clue as to why the latter doesn't work: they aren't coming from opencv-python OR OpenCV itself. 

Some (presumably DirectShow related) library must be generating this spam. It would take some digging around in the Windows implementation of VideoCapture to figure out out, probably.

**Comment by siddharthlh24** [comment]
i have a nexigo n970p and i get this too ! It's probably from there ? I have mailed nexigo too.

[stream_output_log.txt](https://github.com/user-attachments/files/16947710/stream_output_log.txt)

[INFO] [DSH]  python.exe
 [INFO] [DSH]  Creating WndMsg Listener Window
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Performing initializing sequence
 [INFO] [DSH]  Get MessageBus interface succeeded
 [WARN] [DSH]  MessageBus perform initialize in progress
 [WARN] [DSH]  MessageBus perform start in progress
 [INFO] [MBHB] Updating MB Status
 [INFO] [MBHB] Previous marked bus status : Reserved : 0 | Core : 0 | NvContainer Plugin : 0 | DShow Filter : 0 | Camera UI Backend : 0 | Audio UI Backend : 0 | 
 [INFO] [MBHB] Bus connected. (5) peers connected : Audio UI Backend, Core, DShow Filter, NvContainer Plugin, Camera UI Backend
 [INFO] [MBHB] Marked joined / connected for module (1) Core
 [INFO] [MBHB] Marked joined / connected for module (2) NvContainer Plugin
 [INFO] [MBHB] Marked joined / connected for module (3) DShow Filter
 [INFO] [DSH]  Self joined the MessageBus
 [INFO] [DSH]  Request to get container state
 [INFO] [MBHB] Marked joined / connected for module (4) Camera UI Backend
 [INFO] [MBHB] Marked joined / connected for module (5) Audio UI Backend
 [INFO] [MBHB] Updated marked bus status  : Reserved : 0 | Core : 1 | NvContainer Plugin : 1 | DShow Filter : 1 | Camera UI Backend : 1 | Audio UI Backend : 1 | 
 [INFO] [DSH]  Successfully fetched the GPU details
 [INFO] [DSH]  Found matching GPU for CUDA and D3D
 [INFO] [DSH]  Chosen GPU for D3D: (0) NVIDIA GeForce RTX 3070 Laptop GPU : 83495, 0
 [INFO] [DSH]  Request to start core exe
 [INFO] [DSH]  Core reported already running -- Verifying
 [INFO] [DSH]  Verified core exe started
 [INFO] [DSH]  Request to wait for core launch init
 [INFO] [DSH]  Core launch init is done
 [INFO] [DSH]  Request to post cmd for core init
 [INFO] [DSH]  Core initializing now
 [INFO] [DSH]  Initializing streaming output
 [INFO] [DSH]  Request query output resolution
 [INFO] [DSH]  Querying stream output successful. Params: 1920x1080@30/1
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  fmt:2 bpp:24 :640x480
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  On Thread Create
 [INFO] [DSH]  Request to start core exe
 [INFO] [DSH]  Core reported already running -- Verifying
 [INFO] [DSH]  Verified core exe started
 [INFO] [DSH]  Request core to start streaming
 [INFO] [DSH]  Fill buffer started
 [INFO] [DSH]  Initializing image blit data
 [INFO] [DSH]  jpeg exif orientation property not found
 [INFO] [DSH]  image size acquired successfully. src: 1920x1080
 [INFO] [DSH]  image scaler initialized successfully. dst: 1920x1080
 [INFO] [DSH]  Flip/Rotation Options: 16
 [INFO] [DSH]  flip rotator initialized successfully
 [INFO] [DSH]  Successfully copied image pixels
 [INFO] [DSH]  Verify core stream readiness before the first frame (sh)
 [INFO] [UIB]  Request to wait for core output stream readiness
 [INFO] [UIB]  Core output stream is ready
 [INFO] [DSH]  Request query surf
 [INFO] [DSH]  On Destroy Create
 [INFO] [DSH]  Request core to stop streaming
 [WARN] [DSH]  MessageBus perform stop in progress
 [INFO] [MBHB] Force marking all NBX MB modules as disconnected
 [INFO] [MBHB] Previous marked bus status : Reserved : 0 | Core : 1 | NvContainer Plugin : 1 | DShow Filter : 1 | Camera UI Backend : 1 | Audio UI Backend : 1 |
 [INFO] [MBHB] Marked left / disconnected for module (0) Reserved
 [INFO] [MBHB] Marked left / disconnected for module (1) Core
 [INFO] [MBHB] Marked left / disconnected for module (2) NvContainer Plugin
 [INFO] [MBHB] Marked left / disconnected for module (3) DShow Filter
 [INFO] [MBHB] Marked left / disconnected for module (4) Camera UI Backend
 [INFO] [MBHB] Marked left / disconnected for module (5) Audio UI Backend
 [INFO] [MBHB] Updated marked bus status  : Reserved : 0 | Core : 0 | NvContainer Plugin : 0 | DShow Filter : 0 | Camera UI Backend : 0 | Audio UI Backend : 0 |
 [INFO] [DSH]  Destroying parent object
 [INFO] [DSH]  Destroying D3D SH Object
 [INFO] [DSH]  Released FiltShSurf
 [INFO] [DSH]  Released FiltStgRes
 [INFO] [DSH]  Released ImmCtx
 [INFO] [DSH]  Released D3D Device
 [INFO] [DSH]  Released Adapter
 [INFO] [DSH]  Released DXGI Factory
 [INFO] [DSH]  Destroying WndMsg Listener Window
 [INFO] [DSH]  Destroyed window
 [INFO] [DSH]  Unregistered window class
 [INFO] [DSH]  Creating WndMsg Listener Window
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Performing initializing sequence
 [INFO] [DSH]  Re-initializing MessageBus Handler
 [INFO] [DSH]  Request to get container state
 [WARN] [DSH]  MessageBus perform initialize in progress
 [WARN] [DSH]  MessageBus perform start in progress
 [INFO] [MBHB] Updating MB Status
 [INFO] [MBHB] Previous marked bus status : Reserved : 0 | Core : 0 | NvContainer Plugin : 0 | DShow Filter : 0 | Camera UI Backend : 0 | Audio UI Backend : 0 |
 [INFO] [MBHB] Bus connected. (5) peers connected : Audio UI Backend, Core, DShow Filter, NvContainer Plugin, Camera UI Backend
 [INFO] [MBHB] Marked joined / connected for module (1) Core
 [INFO] [MBHB] Marked joined / connected for module (2) NvContainer Plugin
 [INFO] [MBHB] Marked joined / connected for module (3) DShow Filter
 [INFO] [MBHB] Marked joined / connected for module (4) Camera UI Backend
 [INFO] [MBHB] Marked joined / connected for module (5) Audio UI Backend
 [INFO] [MBHB] Updated marked bus status  : Reserved : 0 | Core : 1 | NvContainer Plugin : 1 | DShow Filter : 1 | Camera UI Backend : 1 | Audio UI Backend : 1 |
 [INFO] [DSH]  Successfully fetched the GPU details
 [INFO] [DSH]  Found matching GPU for CUDA and D3D
 [INFO] [DSH]  Chosen GPU for D3D: (0) NVIDIA GeForce RTX 3070 Laptop GPU : 83495, 0
 [INFO] [DSH]  Request to start core exe
 [INFO] [DSH]  Core reported already running -- Verifying
 [INFO] [DSH]  Verified core exe started
 [INFO] [DSH]  Request to wait for core launch init
 [INFO] [DSH]  Core launch init is done
 [INFO] [DSH]  Request to post cmd for core init
 [INFO] [DSH]  Core initializing now
 [INFO] [DSH]  Initializing streaming output
 [INFO] [DSH]  Request query output resolution
 [INFO] [DSH]  Querying stream output successful. Params: 1920x1080@30/1
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  fmt:2 bpp:24 :1920x1080
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  Requested to perform initializing sequence
 [INFO] [DSH]  Already initialized
 [INFO] [DSH]  On Thread Create
 [INFO] [DSH]  Request to start core exe
 [INFO] [DSH]  Core reported already running -- Verifying
 [INFO] [DSH]  Verified core exe started
 [INFO] [DSH]  Request core to start streaming
 [INFO] [DSH]  Fill buffer started
 [INFO] [DSH]  Initializing image blit data
 [INFO] [DSH]  jpeg exif orientation property not found
 [INFO] [DSH]  image size acquired successfully. src: 1920x1080
 [INFO] [DSH]  image scaler initialized successfully. dst: 1920x1080
 [INFO] [DSH]  Flip/Rotation Options: 16
 [INFO] [DSH]  flip rotator initialized successfully
 [INFO] [DSH]  Successfully copied image pixels
 [INFO] [DSH]  Verify core stream readiness before the first frame (sh)
 [INFO] [UIB]  Request to wait for core output stream readiness
 [INFO] [UIB]  Core output stream is ready
 [INFO] [DSH]  Request query surf
 [INFO] [DSH]  Status: (0) | frm: 150 | afbcpy: 2862 | f2f: 30471
 [INFO] [DSH]  Status: (0) | frm: 300 | afbcpy: 2194 | f2f: 31139
 [INFO] [DSH]  Status: (0) | frm: 450 | afbcpy: 2192 | f2f: 31141
 [INFO] [DSH]  Status: (0) | frm: 600 | afbcpy: 2461 | f2f: 30872
 [INFO] [DSH]  Status: (0) | frm: 750 | afbcpy: 2134 | f2f: 31199

**Comment by Bilabong29** [comment]
Have you solved the problem?
I get that message too, when i want use open cv

**Comment by siddharthlh24** [comment]
Yeah, I think it was hooking into one of the virtual camera ( like the digicam control or obs virtual cam )

I just changed the camera id and all was well.
