### ISSUE TITLE
ImportError: dlopen(/env/lib/python3.10/site-packages/cv2/cv2.abi3.so, 0x0002): Symbol not found: _iconv

### ISSUE THREAD

**Issue by Chhunneng** [skvark/opencv-python#929]
### Expected behaviour

fix this error.

### Actual behaviour
Just import cv2 then it error.

### Steps to reproduce
- example code
```py
import cv2
```
- MacBook Air Apple M1

```bash
Traceback (most recent call last):
  File "check_face.py", line 1, in <module>
    import cv2
  File "env/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "env/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File ".pyenv/versions/3.10.11/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(env/lib/python3.10/site-packages/cv2/cv2.abi3.so, 0x0002): Symbol not found: _iconv
  Referenced from: <51F29614-574A-3957-B1EB-7B338150D9A1> env/lib/python3.10/site-packages/cv2/.dylibs/libavcodec.59.37.100.dylib
  Expected in:     <5FEC81F0-90A7-34F9-AFA5-27882CEBD803> /opt/local/lib/libiconv.2.dylib
```

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)

 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)

 - [x] I'm using the latest version of ``opencv-python``

**Comment by prsabahrami** [comment]
Hey!

Was wondering, how did you fix this?

Thanks,

**Comment by 1769782410** [comment]
> Hey!
> 
> Was wondering, how did you fix this?
> 
> Thanks,
I it wish I knew how to fix

**Comment by surbhi498** [comment]
me too. I am also struglling with same issue.
