### ISSUE TITLE
disable mouse wheel image scrolling on Linux

### ISSUE THREAD

**Issue by kimwue** [skvark/opencv-python#93]
Hi,

I display images in a opencv window which works fine. But using the mouse wheel enables zooming into the images by default and there doesn't seem to be an option to disable this?

I read that I have to re-build this repo with Gtk ui instead of the QT one? Is that correct?

Any suggestions welcome :)

Kim

**Comment by kimwue** [comment]
Okay, so what I did is I commented out all `scaleView` function calls in opencv/modules/highgui/src/window_QT.cpp. Then rebuilt and no more zoom.

**Comment by skvark** [comment]
Not really related to this repo but yes, you can and you probably should build a custom version if you need custom functionality. I don't know how to disable scrolling.
