### ISSUE TITLE
Newly added donation notification links to a closed campaign

### ISSUE THREAD

**Issue by Avasam** [skvark/opencv-python#945]
### Expected behaviour

A link to a working donation platform, or no link at all

### Actual behaviour

#940 Added a link to https://www.indiegogo.com/projects/opencv-5-support-non-profit-open-source-cv-ai#/, but the campaign is closed
![image](https://github.com/opencv/opencv-python/assets/1350584/afd82ae2-0129-40b6-85ec-9e3cd471f5c2)

### Steps to reproduce

Click the link

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency") (it's related to this repo's own readme, so close enough?)
 - [x] I'm using the latest version of ``opencv-python``

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv-python/pull/983
