### ISSUE TITLE
not fully support the "enum cv::ImreadModes" parameters

### ISSUE THREAD

**Issue by GuanRainy** [skvark/opencv-python#96]
I hope this modules supports the following parameters in future releases because it is already supported in opencv3 and above. For example, if the 'IMREAD_IGNORE_ORIENTATION' parameter not be supported, will encounter the following problems: "https://github.com/opencv/opencv/issues/11586"
`  cv::IMREAD_LOAD_GDAL = 8, 
  cv::IMREAD_REDUCED_GRAYSCALE_2 = 16, 
  cv::IMREAD_REDUCED_COLOR_2 = 17, 
  cv::IMREAD_REDUCED_GRAYSCALE_4 = 32, 
  cv::IMREAD_REDUCED_COLOR_4 = 33, 
  cv::IMREAD_REDUCED_GRAYSCALE_8 = 64, 
  cv::IMREAD_REDUCED_COLOR_8 = 65, 
  cv::IMREAD_IGNORE_ORIENTATION = 128 `

- opencv-python version(3.4.1)

**Comment by skvark** [comment]
These releases are excatly the same as OpenCV releases. This package simply wraps the OpenCV binary in an easily installable forma and those constants are supported like any other core OpenCV functionality:

```
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.IMREAD_IGNORE_ORIENTATION
128
```

Please read OpenCV documentation next time more carefully or ask basic usage questions at http://answers.opencv.org/questions/.

**Comment by GuanRainy** [comment]
@skvark, I am sorry, this is my fault. I also use two versions of opencv-python(2.7, 3.4.1), but my "__init__.py" generate from 2.7.
