### ISSUE TITLE
cv2.findEssentialMat() Error with 2 cameraMatrix

### ISSUE THREAD

**Issue by MikeBrownse** [skvark/opencv-python#960]
Hello, there shows an error when I use function 'cv2.findEssentialMat()'.

I want to calculate the essential matrix between images taken by two cameras with **different camera matrix** , so I wrote my code as follows:
```python
e, mask = cv2.findEssentialMat(points1=pts1, points2=pts2, cameraMatrix1=k1, distCoeffs1=dist1, cameraMatrix2=k2, distCoeffs2=dist2, method=cv2.RANSAC, prob=0.999, threshold=1.0)
```
but I got an **'-215:Assertion failed'**  error:
```bash
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\undistort.dispatch.cpp:592: error: (-215:Assertion failed) npoints >= 0 && src.isContinuous() && (depth == CV_32F || depth == CV_64F) in function 'cv::undistortPoints'
```

Oddly enough, the D drive does not exist in my computer.

Other information (versions):
- conda 23.7.4 (Anaconda)
- python 3.9.7
- opencv-python 4.9.0.80

Did I pass in the wrong parameters or is this due to something else?

It's been bothering me for a long time. Looking forward to a reply... TAT

**Comment by coolashishpt** [comment]
may be this error you are getting because of  incorrect use of arguments in the cv2.findEssentialMat() function

try this :

`e, mask = cv2.findEssentialMat(pts1, pts2, k1, method=cv2.RANSAC, prob=0.999, threshold=1.0)
`

else : refer this [https://stackoverflow.com/questions/54734538/opencv-assertion-failed-215assertion-failed-npoints-0-depth-cv-32](url)

**Comment by MikeBrownse** [comment]
Thank you for your reply. I checked the documentation about this function and the two Points passed in need to be first normalized according to the CameraMatrix in order to use this function. 
[OpenCV: Camera Calibration and 3D Reconstruction](https://docs.opencv.org/4.9.0/d9/d0c/group__calib3d.html#gafafd52c0372b12dd582597bfb1330430)

But what still puzzles me is that if this is the case, why provide the usage of including two CameraMatrix, which I misinterpreted to mean that it is possible to pass in two different CameraMatrix.

> may be this error you are getting because of incorrect use of arguments in the cv2.findEssentialMat() function
> 
> try this :
> 
> `e, mask = cv2.findEssentialMat(pts1, pts2, k1, method=cv2.RANSAC, prob=0.999, threshold=1.0) `
> 
> else : refer this [https://stackoverflow.com/questions/54734538/opencv-assertion-failed-215assertion-failed-npoints-0-depth-cv-32](url)

**Comment by asmorkalov** [comment]
points1 and points2 should be not empty with type CV_32F (float) or CV_64F (double).

**Comment by MikeBrownse** [comment]
> points1 and points2 should be not empty with type CV_32F (float) or CV_64F (double).

Thank you! I found the mistake in my code following your instruction, I was turned points1 and points2 into type int32 mistakenly....
