### ISSUE TITLE
MacOS: pylint confuses the type of cv2.error

### ISSUE THREAD

**Issue by neykov** [skvark/opencv-python#966]
### Expected behaviour

`pylint` should not flag errors in the following code:
```
import cv2

try:
    print('Boom')
except cv2.error:
    pass
```

### Actual behaviour

pylint detects the following error on MacOS:
```
test.py:9: [E0712(catching-non-exception), ] Catching an exception which doesn't inherit from Exception: cv2.error
```

### Steps to reproduce

- example code
```
import cv2

try:
    print('Boom')
except cv2.error:
    pass
```

- operating system: **MacOS**
- architecture (e.g. x86): N/A
- opencv-python version: 4.9.0.80

The reason for the failure is that on MacOS the `cv2/Error/__init__.pyi` stub shadows `class error(Exception):` stub in `cv2/__init__.pyi`. Could be related to the file system on MacOS being case insensitive. pylint gets confused that `cv2.error` is an `cv2::Error` enum and rightfully flags a problem.

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by Pierre-Sassoulas** [comment]
Pylint maintainer here, you should fill that in pylint instead afaiu. ( https://github.com/pylint-dev/pylint )

**Comment by neykov** [comment]
Found https://github.com/pylint-dev/pylint/issues/9332 for the same problem.
