### ISSUE TITLE
How to use 

### ISSUE THREAD

**Issue by sevar83** [skvark/opencv-python#97]
Hi, I'm very new to Python. I wish to use a particular function in OpenCV which was introduced in OpenCV just few months ago. The function is [`warpPolar()`](https://github.com/opencv/opencv/blob/3.4.1/modules/imgproc/src/imgwarp.cpp). However it doesn't seem to be included in the Python package yet. Could you please help me?

- Windows 10 64-bit
- Intel
- opencv-python 3.4.1.15

**Comment by skvark** [comment]
OpenCV 3.4.1 was released on 27 February. The function you are looking for was added on 17 April to OpenCV development branch (https://github.com/opencv/opencv/pull/11323) so it's not in 3.4.1. You'll have to wait for next release or build OpenCV dev version yourself. The packages generated via this repository follow OpenCV releases. Unstable development builds are not provided.
