### ISSUE TITLE
Update dependent numpy version from 1.21.4 -> 1.26.4

### ISSUE THREAD

**Issue by Shubham11Gupta** [skvark/opencv-python#975]
Numpy version 1.21.4 is giving out medium level vulnerabilities while the whitesource testing.
In my code i am using opencv-python-headless:4.9.0.80 as i only need it in the backend code. and this is giving out the vulnerability during the github whitesource testing.
Can we get it working with the latest LTS version i.e. 1.26.4.

**Comment by asmorkalov** [comment]
OpenCV defines minimal version of the dependencies. You can mention newer version of numpy in your requirements.txt and it'll work. I'll take a look if it's reasonable to raise minimal versions for the next release.

**Comment by Shubham11Gupta** [comment]
the issue i am facing is during the white source testing of the code in the github right before merging, it is showing vulnerability in numpy 1.21.4 and asking for update, the opencv-python-headless is working absolutely fine with that version of numpy but it is the vulnerability with the version which is causing problem, please look into it.
Thank you

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv-python/pull/992/files
