### ISSUE TITLE
BUG: cv2.fillPoly() causing segmentation fault on Ubuntu 22.04.4 LTS

### ISSUE THREAD

**Issue by DerOehmer** [skvark/opencv-python#986]
### Expected behaviour

When accidantely providing an empty but correctly shaped numpy array to the pts argument in cv2.fillPoly(), a meaningfull error should be prompted. 

### Actual behaviour

The script crashes with "Segmentation fault (core dumped)" being prompted. This happpens only when providing np.int32 or higher bit data types and when reshaping the array.

##### example code:
``` 
import numpy as np
import cv2

cntls = []
img = np.zeros((100,100,3), dtype=np.uint8)
color = (0,0,0)
cnts = np.array(cntls, dtype=np.int32).reshape((1, -1, 2))
img = cv2.fillPoly(img, cnts, color) 
```
##### operating system:
 Ubuntu 22.04.4 LTS

##### architecture (e.g. x86)
x86_64
#### opencv-python version
opencv-python 4.9.0.80
numpy 1.25.2
python 3.10.12

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [x] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by ziyingsk** [comment]
Hi! May be you should put your issue in the repo opencv/opencv, the source code of fillPoly() is in that repo.

**Comment by ziyingsk** [comment]
Hi! When you search for the keyword fillPoly. It actually doesn't exist in the codes of this repo. May be you should put your issue in the repo opencv/opencv, the source code of fillPoly() is in that repo.

**Comment by asmorkalov** [comment]
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007fffcf8bb6c7 in cv::CollectPolyEdges (img=..., v=0x0, count=0, edges=std::vector of length 0, capacity 1, color=0x7fffffffcaf0, line_type=8, shift=0, offset=...) at /home/alexander/Projects/OpenCV/opencv-master/modules/imgproc/src/drawing.cpp:1267
1267        Point2l pt0 = v[count-1], pt1;
(gdb) bt
#0  0x00007fffcf8bb6c7 in cv::CollectPolyEdges(cv::Mat&, cv::Point2l const*, int, std::vector<cv::PolyEdge, std::allocator<cv::PolyEdge> >&, void const*, int, int, cv::Point) (img=..., v=0x0, count=0, edges=std::vector of length 0, capacity 1, color=0x7fffffffcaf0, line_type=8, shift=0, offset=...) at /home/alexander/Projects/OpenCV/opencv-master/modules/imgproc/src/drawing.cpp:1267
#1  0x00007fffcf8bfde8 in cv::fillPoly(cv::_InputOutputArray const&, cv::Point_<int> const**, int const*, int, cv::Scalar_<double> const&, int, int, cv::Point_<int>) (_img=..., pts=0x7fffffffd0d0, npts=0x7fffffffcca0, ncontours=1, color=..., line_type=8, shift=0, offset=...) at /home/alexander/Projects/OpenCV/opencv-master/modules/imgproc/src/drawing.cpp:2048
#2  0x00007fffcf8c1412 in cv::fillPoly(cv::_InputOutputArray const&, cv::_InputArray const&, cv::Scalar_<double> const&, int, int, cv::Point_<int>) (img=..., pts=..., color=..., lineType=8, shift=0, offset=...)
    at /home/alexander/Projects/OpenCV/opencv-master/modules/imgproc/src/drawing.cpp:2437
#3  0x00007fffd5d5f939 in pyopencv_cv_fillPoly(PyObject*, PyObject*, PyObject*) (py_args=0x7fffaa85d798, kw=0x0) at /home/alexander/Projects/OpenCV/opencv-build/modules/python_bindings_generator/pyopencv_generated_funcs.h:12097
#4  0x000000000050a335 in  ()
#5  0x000000000050bcb4 in _PyEval_EvalFrameDefault ()
#6  0x0000000000507a64 in  ()
#7  0x000000000050ab13 in PyEval_EvalCode ()
#8  0x0000000000634ec2 in  ()
#9  0x0000000000634f77 in PyRun_FileExFlags ()
#10 0x000000000063872f in PyRun_SimpleFileExFlags ()
#11 0x00000000006392d1 in Py_Main ()
#12 0x00000000004b0db0 in main ()
```

**Comment by asmorkalov** [comment]
The reproducer is not correct, actually, because the points array is empty. I tuned asserts a bit in https://github.com/opencv/opencv/pull/25996 to get assert rather than segfault.
